
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.js'
export type * from './prismaNamespace.js'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  BestXI: 'BestXI',
  BestXIPlayer: 'BestXIPlayer',
  Country: 'Country',
  Player: 'Player',
  PlayerTableDefensive: 'PlayerTableDefensive',
  PlayerTableOffensive: 'PlayerTableOffensive',
  PlayerTablePassing: 'PlayerTablePassing',
  PlayerTableSummary: 'PlayerTableSummary',
  PlayerTableXG: 'PlayerTableXG',
  Region: 'Region',
  Season: 'Season',
  TableCategory: 'TableCategory',
  TableDefensive: 'TableDefensive',
  TableOffensive: 'TableOffensive',
  TableSection: 'TableSection',
  TableSummary: 'TableSummary',
  TableType: 'TableType',
  TableXG: 'TableXG',
  Team: 'Team',
  TeamInTournament: 'TeamInTournament',
  TeamPerformanceStat: 'TeamPerformanceStat',
  TeamPositionalStat: 'TeamPositionalStat',
  TeamSituationalStat: 'TeamSituationalStat',
  TeamStreakStat: 'TeamStreakStat',
  TopPlayerAggression: 'TopPlayerAggression',
  TopPlayerAssist: 'TopPlayerAssist',
  TopPlayerGoalContribution: 'TopPlayerGoalContribution',
  TopPlayerRating: 'TopPlayerRating',
  TopPlayerShot: 'TopPlayerShot',
  TopTeamStat: 'TopTeamStat',
  Tournament: 'Tournament',
  TournamentAssistToGoal: 'TournamentAssistToGoal',
  TournamentPlayerTableDefensive: 'TournamentPlayerTableDefensive',
  TournamentPlayerTableOffensive: 'TournamentPlayerTableOffensive',
  TournamentPlayerTablePassing: 'TournamentPlayerTablePassing',
  TournamentPlayerTableSummary: 'TournamentPlayerTableSummary',
  TournamentPlayerTableXG: 'TournamentPlayerTableXG',
  TournamentTableDefensive: 'TournamentTableDefensive',
  TournamentTableOffensive: 'TournamentTableOffensive',
  TournamentTableSummary: 'TournamentTableSummary',
  TournamentTableXG: 'TournamentTableXG',
  TeamCharacteristic: 'TeamCharacteristic',
  TeamSituationalWidget: 'TeamSituationalWidget',
  TeamStyleOfPlay: 'TeamStyleOfPlay',
  TeamTopStatDefensive: 'TeamTopStatDefensive',
  TeamTopStatOffensive: 'TeamTopStatOffensive',
  TeamTopStatSummary: 'TeamTopStatSummary',
  TeamTopStatXG: 'TeamTopStatXG'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const BestXIScalarFieldEnum = {
  id: 'id',
  tournamentId: 'tournamentId',
  timeframe: 'timeframe',
  startDate: 'startDate',
  endDate: 'endDate',
  formation: 'formation',
  createdAt: 'createdAt'
} as const

export type BestXIScalarFieldEnum = (typeof BestXIScalarFieldEnum)[keyof typeof BestXIScalarFieldEnum]


export const BestXIPlayerScalarFieldEnum = {
  id: 'id',
  bestXIId: 'bestXIId',
  teamId: 'teamId',
  playerName: 'playerName',
  rating: 'rating',
  positionLabel: 'positionLabel',
  positionIndex: 'positionIndex',
  playerId: 'playerId'
} as const

export type BestXIPlayerScalarFieldEnum = (typeof BestXIPlayerScalarFieldEnum)[keyof typeof BestXIPlayerScalarFieldEnum]


export const CountryScalarFieldEnum = {
  id: 'id',
  name: 'name',
  code: 'code',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type CountryScalarFieldEnum = (typeof CountryScalarFieldEnum)[keyof typeof CountryScalarFieldEnum]


export const PlayerScalarFieldEnum = {
  id: 'id',
  name: 'name',
  countryId: 'countryId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  minId: 'minId'
} as const

export type PlayerScalarFieldEnum = (typeof PlayerScalarFieldEnum)[keyof typeof PlayerScalarFieldEnum]


export const PlayerTableDefensiveScalarFieldEnum = {
  id: 'id',
  typeId: 'typeId',
  categoryId: 'categoryId',
  playerId: 'playerId',
  teamId: 'teamId',
  rank: 'rank',
  apps: 'apps',
  minsPlayed: 'minsPlayed',
  tackles: 'tackles',
  interceptions: 'interceptions',
  fouls: 'fouls',
  offsidesSaved: 'offsidesSaved',
  clearances: 'clearances',
  dribbledPast: 'dribbledPast',
  outfielderBlock: 'outfielderBlock',
  ownGoals: 'ownGoals',
  rating: 'rating',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type PlayerTableDefensiveScalarFieldEnum = (typeof PlayerTableDefensiveScalarFieldEnum)[keyof typeof PlayerTableDefensiveScalarFieldEnum]


export const PlayerTableOffensiveScalarFieldEnum = {
  id: 'id',
  typeId: 'typeId',
  categoryId: 'categoryId',
  playerId: 'playerId',
  teamId: 'teamId',
  rank: 'rank',
  apps: 'apps',
  minsPlayed: 'minsPlayed',
  shotsPerGame: 'shotsPerGame',
  shotsOnTarget: 'shotsOnTarget',
  keyPasses: 'keyPasses',
  dribbles: 'dribbles',
  fouled: 'fouled',
  offsides: 'offsides',
  dispossessed: 'dispossessed',
  turnover: 'turnover',
  rating: 'rating',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type PlayerTableOffensiveScalarFieldEnum = (typeof PlayerTableOffensiveScalarFieldEnum)[keyof typeof PlayerTableOffensiveScalarFieldEnum]


export const PlayerTablePassingScalarFieldEnum = {
  id: 'id',
  typeId: 'typeId',
  categoryId: 'categoryId',
  playerId: 'playerId',
  teamId: 'teamId',
  rank: 'rank',
  apps: 'apps',
  minsPlayed: 'minsPlayed',
  keyPasses: 'keyPasses',
  passes: 'passes',
  passSuccess: 'passSuccess',
  crosses: 'crosses',
  longBalls: 'longBalls',
  throughBalls: 'throughBalls',
  rating: 'rating',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type PlayerTablePassingScalarFieldEnum = (typeof PlayerTablePassingScalarFieldEnum)[keyof typeof PlayerTablePassingScalarFieldEnum]


export const PlayerTableSummaryScalarFieldEnum = {
  id: 'id',
  typeId: 'typeId',
  categoryId: 'categoryId',
  playerId: 'playerId',
  teamId: 'teamId',
  rank: 'rank',
  apps: 'apps',
  minsPlayed: 'minsPlayed',
  goals: 'goals',
  assists: 'assists',
  yellow: 'yellow',
  red: 'red',
  shotsPerGame: 'shotsPerGame',
  passSuccess: 'passSuccess',
  aerialsWon: 'aerialsWon',
  motm: 'motm',
  rating: 'rating',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type PlayerTableSummaryScalarFieldEnum = (typeof PlayerTableSummaryScalarFieldEnum)[keyof typeof PlayerTableSummaryScalarFieldEnum]


export const PlayerTableXGScalarFieldEnum = {
  id: 'id',
  typeId: 'typeId',
  categoryId: 'categoryId',
  sectionId: 'sectionId',
  playerId: 'playerId',
  teamId: 'teamId',
  rank: 'rank',
  apps: 'apps',
  minsPlayed: 'minsPlayed',
  xG: 'xG',
  rating: 'rating',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  goals: 'goals',
  shots: 'shots',
  xG90: 'xG90',
  xGDiff: 'xGDiff',
  xGPerShot: 'xGPerShot'
} as const

export type PlayerTableXGScalarFieldEnum = (typeof PlayerTableXGScalarFieldEnum)[keyof typeof PlayerTableXGScalarFieldEnum]


export const RegionScalarFieldEnum = {
  id: 'id',
  name: 'name',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type RegionScalarFieldEnum = (typeof RegionScalarFieldEnum)[keyof typeof RegionScalarFieldEnum]


export const SeasonScalarFieldEnum = {
  id: 'id',
  name: 'name',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type SeasonScalarFieldEnum = (typeof SeasonScalarFieldEnum)[keyof typeof SeasonScalarFieldEnum]


export const TableCategoryScalarFieldEnum = {
  id: 'id',
  name: 'name',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type TableCategoryScalarFieldEnum = (typeof TableCategoryScalarFieldEnum)[keyof typeof TableCategoryScalarFieldEnum]


export const TableDefensiveScalarFieldEnum = {
  id: 'id',
  typeId: 'typeId',
  categoryId: 'categoryId',
  teamId: 'teamId',
  tournamentId: 'tournamentId',
  rank: 'rank',
  shotsPg: 'shotsPg',
  tacklesPg: 'tacklesPg',
  interceptionsPg: 'interceptionsPg',
  foulsPg: 'foulsPg',
  offsidesPg: 'offsidesPg',
  rating: 'rating',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  tableSectionId: 'tableSectionId'
} as const

export type TableDefensiveScalarFieldEnum = (typeof TableDefensiveScalarFieldEnum)[keyof typeof TableDefensiveScalarFieldEnum]


export const TableOffensiveScalarFieldEnum = {
  id: 'id',
  typeId: 'typeId',
  categoryId: 'categoryId',
  teamId: 'teamId',
  tournamentId: 'tournamentId',
  rank: 'rank',
  shotsPg: 'shotsPg',
  shotsOTpg: 'shotsOTpg',
  dribblesPg: 'dribblesPg',
  fouledPg: 'fouledPg',
  rating: 'rating',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  tableSectionId: 'tableSectionId'
} as const

export type TableOffensiveScalarFieldEnum = (typeof TableOffensiveScalarFieldEnum)[keyof typeof TableOffensiveScalarFieldEnum]


export const TableSectionScalarFieldEnum = {
  id: 'id',
  name: 'name',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type TableSectionScalarFieldEnum = (typeof TableSectionScalarFieldEnum)[keyof typeof TableSectionScalarFieldEnum]


export const TableSummaryScalarFieldEnum = {
  id: 'id',
  typeId: 'typeId',
  categoryId: 'categoryId',
  teamId: 'teamId',
  tournamentId: 'tournamentId',
  rank: 'rank',
  goals: 'goals',
  shotsPg: 'shotsPg',
  yellow: 'yellow',
  red: 'red',
  possession: 'possession',
  pass: 'pass',
  aerialsWon: 'aerialsWon',
  rating: 'rating',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  tableSectionId: 'tableSectionId'
} as const

export type TableSummaryScalarFieldEnum = (typeof TableSummaryScalarFieldEnum)[keyof typeof TableSummaryScalarFieldEnum]


export const TableTypeScalarFieldEnum = {
  id: 'id',
  name: 'name',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type TableTypeScalarFieldEnum = (typeof TableTypeScalarFieldEnum)[keyof typeof TableTypeScalarFieldEnum]


export const TableXGScalarFieldEnum = {
  id: 'id',
  typeId: 'typeId',
  categoryId: 'categoryId',
  sectionId: 'sectionId',
  teamId: 'teamId',
  tournamentId: 'tournamentId',
  order: 'order',
  xG: 'xG',
  goals: 'goals',
  xGDiff: 'xGDiff',
  shots: 'shots',
  xGShots: 'xGShots',
  rating: 'rating',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  rank: 'rank'
} as const

export type TableXGScalarFieldEnum = (typeof TableXGScalarFieldEnum)[keyof typeof TableXGScalarFieldEnum]


export const TeamScalarFieldEnum = {
  id: 'id',
  name: 'name',
  countryId: 'countryId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  minId: 'minId'
} as const

export type TeamScalarFieldEnum = (typeof TeamScalarFieldEnum)[keyof typeof TeamScalarFieldEnum]


export const TeamInTournamentScalarFieldEnum = {
  id: 'id',
  teamId: 'teamId',
  countryId: 'countryId',
  tournamentId: 'tournamentId',
  seasonId: 'seasonId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type TeamInTournamentScalarFieldEnum = (typeof TeamInTournamentScalarFieldEnum)[keyof typeof TeamInTournamentScalarFieldEnum]


export const TeamPerformanceStatScalarFieldEnum = {
  id: 'id',
  tournamentId: 'tournamentId',
  teamId: 'teamId',
  category: 'category',
  rank: 'rank',
  matchesPlayed: 'matchesPlayed',
  winPercentage: 'winPercentage',
  drawPercentage: 'drawPercentage',
  lossPercentage: 'lossPercentage',
  goalsForPg: 'goalsForPg',
  goalsAgainstPg: 'goalsAgainstPg',
  pointsPg: 'pointsPg',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  mode: 'mode',
  viewTypeId: 'viewTypeId'
} as const

export type TeamPerformanceStatScalarFieldEnum = (typeof TeamPerformanceStatScalarFieldEnum)[keyof typeof TeamPerformanceStatScalarFieldEnum]


export const TeamPositionalStatScalarFieldEnum = {
  id: 'id',
  tournamentId: 'tournamentId',
  teamId: 'teamId',
  category: 'category',
  leftSide: 'leftSide',
  middle: 'middle',
  rightSide: 'rightSide',
  sixYardBox: 'sixYardBox',
  penaltyArea: 'penaltyArea',
  outsideBox: 'outsideBox',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  viewTypeId: 'viewTypeId',
  sectionId: 'sectionId'
} as const

export type TeamPositionalStatScalarFieldEnum = (typeof TeamPositionalStatScalarFieldEnum)[keyof typeof TeamPositionalStatScalarFieldEnum]


export const TeamSituationalStatScalarFieldEnum = {
  id: 'id',
  tournamentId: 'tournamentId',
  teamId: 'teamId',
  category: 'category',
  openPlay: 'openPlay',
  counterAttack: 'counterAttack',
  setPiece: 'setPiece',
  penalty: 'penalty',
  ownGoal: 'ownGoal',
  crosses: 'crosses',
  longBalls: 'longBalls',
  throughBalls: 'throughBalls',
  shortPasses: 'shortPasses',
  fouls: 'fouls',
  unprofessional: 'unprofessional',
  other: 'other',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  viewTypeId: 'viewTypeId',
  sectionId: 'sectionId'
} as const

export type TeamSituationalStatScalarFieldEnum = (typeof TeamSituationalStatScalarFieldEnum)[keyof typeof TeamSituationalStatScalarFieldEnum]


export const TeamStreakStatScalarFieldEnum = {
  id: 'id',
  tournamentId: 'tournamentId',
  teamId: 'teamId',
  streakType: 'streakType',
  scope: 'scope',
  rank: 'rank',
  streakCount: 'streakCount',
  matchesPlayed: 'matchesPlayed',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  mode: 'mode',
  viewTypeId: 'viewTypeId'
} as const

export type TeamStreakStatScalarFieldEnum = (typeof TeamStreakStatScalarFieldEnum)[keyof typeof TeamStreakStatScalarFieldEnum]


export const TopPlayerAggressionScalarFieldEnum = {
  id: 'id',
  tournamentId: 'tournamentId',
  teamId: 'teamId',
  playerId: 'playerId',
  rank: 'rank',
  yellowCards: 'yellowCards',
  redCards: 'redCards',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  viewTypeId: 'viewTypeId'
} as const

export type TopPlayerAggressionScalarFieldEnum = (typeof TopPlayerAggressionScalarFieldEnum)[keyof typeof TopPlayerAggressionScalarFieldEnum]


export const TopPlayerAssistScalarFieldEnum = {
  id: 'id',
  tournamentId: 'tournamentId',
  teamId: 'teamId',
  playerId: 'playerId',
  rank: 'rank',
  assists: 'assists',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  viewTypeId: 'viewTypeId'
} as const

export type TopPlayerAssistScalarFieldEnum = (typeof TopPlayerAssistScalarFieldEnum)[keyof typeof TopPlayerAssistScalarFieldEnum]


export const TopPlayerGoalContributionScalarFieldEnum = {
  id: 'id',
  tournamentId: 'tournamentId',
  teamId: 'teamId',
  playerId: 'playerId',
  rank: 'rank',
  goals: 'goals',
  teamGoalsTotal: 'teamGoalsTotal',
  contributionPercent: 'contributionPercent',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  viewTypeId: 'viewTypeId'
} as const

export type TopPlayerGoalContributionScalarFieldEnum = (typeof TopPlayerGoalContributionScalarFieldEnum)[keyof typeof TopPlayerGoalContributionScalarFieldEnum]


export const TopPlayerRatingScalarFieldEnum = {
  id: 'id',
  tournamentId: 'tournamentId',
  teamId: 'teamId',
  playerId: 'playerId',
  rank: 'rank',
  rating: 'rating',
  apps: 'apps',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  viewTypeId: 'viewTypeId'
} as const

export type TopPlayerRatingScalarFieldEnum = (typeof TopPlayerRatingScalarFieldEnum)[keyof typeof TopPlayerRatingScalarFieldEnum]


export const TopPlayerShotScalarFieldEnum = {
  id: 'id',
  tournamentId: 'tournamentId',
  teamId: 'teamId',
  playerId: 'playerId',
  rank: 'rank',
  shotsPerGame: 'shotsPerGame',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  viewTypeId: 'viewTypeId'
} as const

export type TopPlayerShotScalarFieldEnum = (typeof TopPlayerShotScalarFieldEnum)[keyof typeof TopPlayerShotScalarFieldEnum]


export const TopTeamStatScalarFieldEnum = {
  id: 'id',
  tournamentId: 'tournamentId',
  teamId: 'teamId',
  statType: 'statType',
  rank: 'rank',
  value: 'value',
  subValue1: 'subValue1',
  subValue2: 'subValue2',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  viewTypeId: 'viewTypeId'
} as const

export type TopTeamStatScalarFieldEnum = (typeof TopTeamStatScalarFieldEnum)[keyof typeof TopTeamStatScalarFieldEnum]


export const TournamentScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  regionId: 'regionId',
  countryId: 'countryId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  minId: 'minId'
} as const

export type TournamentScalarFieldEnum = (typeof TournamentScalarFieldEnum)[keyof typeof TournamentScalarFieldEnum]


export const TournamentAssistToGoalScalarFieldEnum = {
  id: 'id',
  tournamentId: 'tournamentId',
  teamId: 'teamId',
  rank: 'rank',
  count: 'count',
  scorerName: 'scorerName',
  scorerId: 'scorerId',
  assistantName: 'assistantName',
  assistantId: 'assistantId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  viewTypeId: 'viewTypeId'
} as const

export type TournamentAssistToGoalScalarFieldEnum = (typeof TournamentAssistToGoalScalarFieldEnum)[keyof typeof TournamentAssistToGoalScalarFieldEnum]


export const TournamentPlayerTableDefensiveScalarFieldEnum = {
  id: 'id',
  tournamentId: 'tournamentId',
  playerId: 'playerId',
  teamId: 'teamId',
  categoryId: 'categoryId',
  typeId: 'typeId',
  sectionId: 'sectionId',
  rank: 'rank',
  apps: 'apps',
  minsPlayed: 'minsPlayed',
  tackles: 'tackles',
  interceptions: 'interceptions',
  fouls: 'fouls',
  offsidesSaved: 'offsidesSaved',
  clearances: 'clearances',
  dribbledPast: 'dribbledPast',
  outfielderBlock: 'outfielderBlock',
  ownGoals: 'ownGoals',
  rating: 'rating',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  viewTypeId: 'viewTypeId'
} as const

export type TournamentPlayerTableDefensiveScalarFieldEnum = (typeof TournamentPlayerTableDefensiveScalarFieldEnum)[keyof typeof TournamentPlayerTableDefensiveScalarFieldEnum]


export const TournamentPlayerTableOffensiveScalarFieldEnum = {
  id: 'id',
  tournamentId: 'tournamentId',
  playerId: 'playerId',
  teamId: 'teamId',
  categoryId: 'categoryId',
  typeId: 'typeId',
  sectionId: 'sectionId',
  rank: 'rank',
  apps: 'apps',
  minsPlayed: 'minsPlayed',
  shotsPerGame: 'shotsPerGame',
  shotsOnTarget: 'shotsOnTarget',
  keyPasses: 'keyPasses',
  dribbles: 'dribbles',
  fouled: 'fouled',
  offsides: 'offsides',
  dispossessed: 'dispossessed',
  turnover: 'turnover',
  rating: 'rating',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  viewTypeId: 'viewTypeId'
} as const

export type TournamentPlayerTableOffensiveScalarFieldEnum = (typeof TournamentPlayerTableOffensiveScalarFieldEnum)[keyof typeof TournamentPlayerTableOffensiveScalarFieldEnum]


export const TournamentPlayerTablePassingScalarFieldEnum = {
  id: 'id',
  tournamentId: 'tournamentId',
  playerId: 'playerId',
  teamId: 'teamId',
  categoryId: 'categoryId',
  typeId: 'typeId',
  sectionId: 'sectionId',
  rank: 'rank',
  apps: 'apps',
  minsPlayed: 'minsPlayed',
  keyPasses: 'keyPasses',
  passes: 'passes',
  passSuccess: 'passSuccess',
  crosses: 'crosses',
  longBalls: 'longBalls',
  throughBalls: 'throughBalls',
  rating: 'rating',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  viewTypeId: 'viewTypeId'
} as const

export type TournamentPlayerTablePassingScalarFieldEnum = (typeof TournamentPlayerTablePassingScalarFieldEnum)[keyof typeof TournamentPlayerTablePassingScalarFieldEnum]


export const TournamentPlayerTableSummaryScalarFieldEnum = {
  id: 'id',
  tournamentId: 'tournamentId',
  playerId: 'playerId',
  teamId: 'teamId',
  categoryId: 'categoryId',
  typeId: 'typeId',
  sectionId: 'sectionId',
  rank: 'rank',
  apps: 'apps',
  minsPlayed: 'minsPlayed',
  goals: 'goals',
  assists: 'assists',
  yellow: 'yellow',
  red: 'red',
  shotsPerGame: 'shotsPerGame',
  passSuccess: 'passSuccess',
  aerialsWon: 'aerialsWon',
  motm: 'motm',
  rating: 'rating',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  viewTypeId: 'viewTypeId'
} as const

export type TournamentPlayerTableSummaryScalarFieldEnum = (typeof TournamentPlayerTableSummaryScalarFieldEnum)[keyof typeof TournamentPlayerTableSummaryScalarFieldEnum]


export const TournamentPlayerTableXGScalarFieldEnum = {
  id: 'id',
  tournamentId: 'tournamentId',
  playerId: 'playerId',
  teamId: 'teamId',
  categoryId: 'categoryId',
  typeId: 'typeId',
  sectionId: 'sectionId',
  rank: 'rank',
  apps: 'apps',
  minsPlayed: 'minsPlayed',
  xG: 'xG',
  npxG: 'npxG',
  xGAssist: 'xGAssist',
  xGChain: 'xGChain',
  xGBuildup: 'xGBuildup',
  rating: 'rating',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  viewTypeId: 'viewTypeId'
} as const

export type TournamentPlayerTableXGScalarFieldEnum = (typeof TournamentPlayerTableXGScalarFieldEnum)[keyof typeof TournamentPlayerTableXGScalarFieldEnum]


export const TournamentTableDefensiveScalarFieldEnum = {
  id: 'id',
  tournamentId: 'tournamentId',
  teamId: 'teamId',
  categoryId: 'categoryId',
  typeId: 'typeId',
  sectionId: 'sectionId',
  rank: 'rank',
  shotsPg: 'shotsPg',
  tacklesPg: 'tacklesPg',
  interceptionsPg: 'interceptionsPg',
  foulsPg: 'foulsPg',
  offsidesPg: 'offsidesPg',
  rating: 'rating',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  viewTypeId: 'viewTypeId'
} as const

export type TournamentTableDefensiveScalarFieldEnum = (typeof TournamentTableDefensiveScalarFieldEnum)[keyof typeof TournamentTableDefensiveScalarFieldEnum]


export const TournamentTableOffensiveScalarFieldEnum = {
  id: 'id',
  tournamentId: 'tournamentId',
  teamId: 'teamId',
  categoryId: 'categoryId',
  typeId: 'typeId',
  sectionId: 'sectionId',
  rank: 'rank',
  shotsPg: 'shotsPg',
  shotsOTpg: 'shotsOTpg',
  dribblesPg: 'dribblesPg',
  fouledPg: 'fouledPg',
  rating: 'rating',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  viewTypeId: 'viewTypeId'
} as const

export type TournamentTableOffensiveScalarFieldEnum = (typeof TournamentTableOffensiveScalarFieldEnum)[keyof typeof TournamentTableOffensiveScalarFieldEnum]


export const TournamentTableSummaryScalarFieldEnum = {
  id: 'id',
  tournamentId: 'tournamentId',
  teamId: 'teamId',
  categoryId: 'categoryId',
  typeId: 'typeId',
  sectionId: 'sectionId',
  rank: 'rank',
  goals: 'goals',
  shotsPg: 'shotsPg',
  yellow: 'yellow',
  red: 'red',
  possession: 'possession',
  pass: 'pass',
  aerialsWon: 'aerialsWon',
  rating: 'rating',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  viewTypeId: 'viewTypeId'
} as const

export type TournamentTableSummaryScalarFieldEnum = (typeof TournamentTableSummaryScalarFieldEnum)[keyof typeof TournamentTableSummaryScalarFieldEnum]


export const TournamentTableXGScalarFieldEnum = {
  id: 'id',
  tournamentId: 'tournamentId',
  teamId: 'teamId',
  categoryId: 'categoryId',
  typeId: 'typeId',
  sectionId: 'sectionId',
  rank: 'rank',
  order: 'order',
  xG: 'xG',
  goals: 'goals',
  xGDiff: 'xGDiff',
  shots: 'shots',
  xGShots: 'xGShots',
  rating: 'rating',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  viewTypeId: 'viewTypeId'
} as const

export type TournamentTableXGScalarFieldEnum = (typeof TournamentTableXGScalarFieldEnum)[keyof typeof TournamentTableXGScalarFieldEnum]


export const TeamCharacteristicScalarFieldEnum = {
  id: 'id',
  teamId: 'teamId',
  kind: 'kind',
  label: 'label',
  area: 'area',
  levelText: 'levelText',
  level: 'level',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type TeamCharacteristicScalarFieldEnum = (typeof TeamCharacteristicScalarFieldEnum)[keyof typeof TeamCharacteristicScalarFieldEnum]


export const TeamSituationalWidgetScalarFieldEnum = {
  id: 'id',
  teamId: 'teamId',
  category: 'category',
  view: 'view',
  side: 'side',
  type: 'type',
  value: 'value',
  effectPct: 'effectPct',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type TeamSituationalWidgetScalarFieldEnum = (typeof TeamSituationalWidgetScalarFieldEnum)[keyof typeof TeamSituationalWidgetScalarFieldEnum]


export const TeamStyleOfPlayScalarFieldEnum = {
  id: 'id',
  teamId: 'teamId',
  label: 'label',
  area: 'area',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type TeamStyleOfPlayScalarFieldEnum = (typeof TeamStyleOfPlayScalarFieldEnum)[keyof typeof TeamStyleOfPlayScalarFieldEnum]


export const TeamTopStatDefensiveScalarFieldEnum = {
  id: 'id',
  teamId: 'teamId',
  tournamentId: 'tournamentId',
  viewTypeId: 'viewTypeId',
  apps: 'apps',
  shotsConcededPg: 'shotsConcededPg',
  tacklesPg: 'tacklesPg',
  interceptionsPg: 'interceptionsPg',
  foulsPg: 'foulsPg',
  offsidesPg: 'offsidesPg',
  rating: 'rating',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type TeamTopStatDefensiveScalarFieldEnum = (typeof TeamTopStatDefensiveScalarFieldEnum)[keyof typeof TeamTopStatDefensiveScalarFieldEnum]


export const TeamTopStatOffensiveScalarFieldEnum = {
  id: 'id',
  teamId: 'teamId',
  tournamentId: 'tournamentId',
  viewTypeId: 'viewTypeId',
  apps: 'apps',
  shotsPg: 'shotsPg',
  shotsOTpg: 'shotsOTpg',
  dribblesPg: 'dribblesPg',
  fouledPg: 'fouledPg',
  rating: 'rating',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type TeamTopStatOffensiveScalarFieldEnum = (typeof TeamTopStatOffensiveScalarFieldEnum)[keyof typeof TeamTopStatOffensiveScalarFieldEnum]


export const TeamTopStatSummaryScalarFieldEnum = {
  id: 'id',
  teamId: 'teamId',
  tournamentId: 'tournamentId',
  viewTypeId: 'viewTypeId',
  apps: 'apps',
  goals: 'goals',
  shotsPg: 'shotsPg',
  yellow: 'yellow',
  red: 'red',
  possession: 'possession',
  passSuccess: 'passSuccess',
  aerialsWonPg: 'aerialsWonPg',
  rating: 'rating',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type TeamTopStatSummaryScalarFieldEnum = (typeof TeamTopStatSummaryScalarFieldEnum)[keyof typeof TeamTopStatSummaryScalarFieldEnum]


export const TeamTopStatXGScalarFieldEnum = {
  id: 'id',
  teamId: 'teamId',
  tournamentId: 'tournamentId',
  viewTypeId: 'viewTypeId',
  side: 'side',
  pensMode: 'pensMode',
  apps: 'apps',
  xG: 'xG',
  goalsExcOwn: 'goalsExcOwn',
  xGDiff: 'xGDiff',
  shots: 'shots',
  xGPerShot: 'xGPerShot',
  rating: 'rating',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type TeamTopStatXGScalarFieldEnum = (typeof TeamTopStatXGScalarFieldEnum)[keyof typeof TeamTopStatXGScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

