export const footballSwaggerExamples = {
  countries: {
    get: "countries",
    parameters: { name: "england" },
    errors: [],
    results: 1,
    paging: { current: 1, total: 1 },
    response: [{ name: "England", code: "GB", flag: "https://media.api-sports.io/flags/gb.svg" }],
  },
  timezone: {
    get: "timezone",
    parameters: [],
    errors: [],
    results: 2,
    paging: { current: 1, total: 1 },
    response: ["Africa/Abidjan", "Africa/Accra"],
  },
  leagues: {
    get: "leagues",
    parameters: { id: "39" },
    errors: [],
    results: 1,
    paging: { current: 1, total: 1 },
    response: [
      {
        league: { id: 39, name: "Premier League", type: "League", logo: "2.png" },
        country: { name: "England", code: "GB", flag: "gb.svg" },
        seasons: [
          {
            year: 2023,
            start: "2023-08-11",
            end: "2024-05-19",
            current: true,
            coverage: {
              fixtures: {
                events: true,
                lineups: true,
                statistics_fixtures: true,
                statistics_players: true,
              },
              standings: true,
              players: true,
              top_scorers: true,
              top_assists: true,
              top_cards: true,
              injuries: true,
              predictions: true,
              odds: true,
            },
          },
        ],
      },
    ],
  },
  leagueSeasons: {
    get: "leagues/seasons",
    parameters: [],
    errors: [],
    results: 6,
    paging: { current: 1, total: 1 },
    response: [2018, 2019, 2020, 2021, 2022, 2023],
  },
  fixtures: {
    get: "fixtures",
    parameters: { live: "all" },
    errors: [],
    results: 1,
    paging: { current: 1, total: 1 },
    response: [
      {
        fixture: {
          id: 239625,
          referee: null,
          timezone: "UTC",
          date: "2020-02-06T14:00:00+00:00",
          timestamp: 1580997600,
          periods: { first: 1580997600, second: null },
          venue: { id: 1887, name: "Stade Municipal", city: "Oued Zem" },
          status: { long: "Halftime", short: "HT", elapsed: 45, extra: null },
        },
        league: {
          id: 200,
          name: "Botola Pro",
          country: "Morocco",
          logo: "115.png",
          flag: "ma.svg",
          season: 2019,
          round: "Regular Season - 14",
        },
        teams: {
          home: { id: 967, name: "Rapide Oued ZEM", logo: "967.png", winner: false },
          away: { id: 968, name: "Wydad AC", logo: "968.png", winner: true },
        },
        goals: { home: 0, away: 1 },
        score: {
          halftime: { home: 0, away: 1 },
          fulltime: { home: null, away: null },
          extratime: { home: null, away: null },
          penalty: { home: null, away: null },
        },
      },
    ],
  },
  fixtureRounds: {
    get: "fixtures/rounds",
    parameters: { league: "39", season: "2019" },
    errors: [],
    results: 3,
    paging: { current: 1, total: 1 },
    response: ["Regular Season - 1", "Regular Season - 2", "Regular Season - 3"],
  },
  fixtureHeadToHead: {
    get: "fixtures/headtohead",
    parameters: { h2h: "33-34", last: "1" },
    errors: [],
    results: 1,
    paging: { current: 1, total: 1 },
    response: [
      {
        fixture: {
          id: 157201,
          referee: "Kevin Friend, England",
          timezone: "UTC",
          date: "2019-12-26T17:30:00+00:00",
          timestamp: 1577381400,
          periods: { first: 1577381400, second: 1577385000 },
          venue: { id: 556, name: "Old Trafford", city: "Manchester" },
          status: { long: "Match Finished", short: "FT", elapsed: 90, extra: null },
        },
        league: {
          id: 39,
          name: "Premier League",
          country: "England",
          logo: "2.png",
          flag: "gb.svg",
          season: 2019,
          round: "Regular Season - 19",
        },
        teams: {
          home: { id: 33, name: "Manchester United", logo: "33.png", winner: true },
          away: { id: 34, name: "Newcastle", logo: "34.png", winner: false },
        },
        goals: { home: 4, away: 1 },
        score: {
          halftime: { home: 3, away: 1 },
          fulltime: { home: 4, away: 1 },
          extratime: { home: null, away: null },
          penalty: { home: null, away: null },
        },
      },
    ],
  },
  fixtureStatistics: {
    get: "fixtures/statistics",
    parameters: { team: "463", fixture: "215662" },
    errors: [],
    results: 1,
    paging: { current: 1, total: 1 },
    response: [
      {
        team: { id: 463, name: "Aldosivi", logo: "463.png" },
        statistics: [
          { type: "Shots on Goal", value: 3 },
          { type: "Ball Possession", value: "32%" },
        ],
      },
    ],
  },
  fixtureEvents: {
    get: "fixtures/events",
    parameters: { fixture: "215662" },
    errors: [],
    results: 1,
    paging: { current: 1, total: 1 },
    response: [
      {
        time: { elapsed: 25, extra: null },
        team: { id: 463, name: "Aldosivi", logo: "463.png" },
        player: { id: 6126, name: "F. Andrada" },
        assist: { id: null, name: null },
        type: "Goal",
        detail: "Normal Goal",
        comments: null,
      },
    ],
  },
  fixtureLineups: {
    get: "fixtures/lineups",
    parameters: { fixture: "592872" },
    errors: [],
    results: 1,
    paging: { current: 1, total: 1 },
    response: [
      {
        team: {
          id: 50,
          name: "Manchester City",
          logo: "50.png",
          colors: {
            player: { primary: "5badff", number: "ffffff", border: "99ff99" },
            goalkeeper: { primary: "99ff99", number: "000000", border: "99ff99" },
          },
        },
        formation: "4-3-3",
        startXI: [{ player: { id: 617, name: "Ederson", number: 31, pos: "G", grid: "1:1" } }],
        substitutes: [
          { player: { id: 50828, name: "Zack Steffen", number: 13, pos: "G", grid: null } },
        ],
        coach: { id: 4, name: "Guardiola", photo: "4.png" },
      },
    ],
  },
  fixturePlayers: {
    get: "fixtures/players",
    parameters: { fixture: "169080" },
    errors: [],
    results: 1,
    paging: { current: 1, total: 1 },
    response: [
      {
        team: { id: 2284, name: "Monarcas", logo: "2284.png", update: "2020-01-13T16:12:12+00:00" },
        players: [
          {
            player: { id: 35931, name: "Sebastian Sosa", photo: "35931.png" },
            statistics: [{ games: { minutes: 90, number: 13, position: "G", rating: "6.3", captain: false, substitute: false } }],
          },
        ],
      },
    ],
  },
  teams: {
    get: "teams",
    parameters: { id: "33" },
    errors: [],
    results: 1,
    paging: { current: 1, total: 1 },
    response: [
      {
        team: {
          id: 33,
          name: "Manchester United",
          code: "MUN",
          country: "England",
          founded: 1878,
          national: false,
          logo: "33.png",
        },
        venue: {
          id: 556,
          name: "Old Trafford",
          address: "Sir Matt Busby Way",
          city: "Manchester",
          capacity: 76212,
          surface: "grass",
          image: "556.png",
        },
      },
    ],
  },
  teamStatistics: {
    get: "teams/statistics",
    parameters: { league: "39", season: "2019", team: "33" },
    errors: [],
    results: 1,
    paging: { current: 1, total: 1 },
    response: {
      league: { id: 39, name: "Premier League", country: "England", logo: "39.png", flag: "gb-eng.svg", season: 2019 },
      team: { id: 33, name: "Manchester United", logo: "33.png" },
      form: "WDLDWLDLDWLWDDWWDLWWLWLLDWWDWDWWWWDWDW",
      fixtures: {
        played: { home: 19, away: 19, total: 38 },
        wins: { home: 10, away: 8, total: 18 },
        draws: { home: 7, away: 5, total: 12 },
        loses: { home: 2, away: 6, total: 8 },
      },
    },
  },
  teamSeasons: {
    get: "teams/seasons",
    parameters: { team: "33" },
    errors: [],
    results: 1,
    paging: { current: 1, total: 1 },
    response: [2010, 2011, 2012],
  },
  teamCountries: {
    get: "teams/countries",
    parameters: [],
    errors: [],
    results: 1,
    paging: { current: 1, total: 1 },
    response: [{ name: "England", code: "GB", flag: "gb.svg" }],
  },
  venues: {
    get: "venues",
    parameters: { id: "556" },
    errors: [],
    results: 1,
    paging: { current: 1, total: 1 },
    response: [
      {
        id: 556,
        name: "Old Trafford",
        address: "Sir Matt Busby Way",
        city: "Manchester",
        country: "England",
        capacity: 76212,
        surface: "grass",
        image: "556.png",
      },
    ],
  },
  standings: {
    get: "standings",
    parameters: { league: "39", season: "2019" },
    errors: [],
    results: 1,
    paging: { current: 1, total: 1 },
    response: [
      {
        league: {
          id: 39,
          name: "Premier League",
          country: "England",
          logo: "2.png",
          flag: "gb.svg",
          season: 2019,
          standings: [[{ rank: 1, team: { id: 40, name: "Liverpool", logo: "40.png" }, points: 70, goalsDiff: 41, group: "Premier League", form: "WWWWW" }]],
        },
      },
    ],
  },
  injuries: {
    get: "injuries",
    parameters: { fixture: "686314" },
    errors: [],
    results: 1,
    paging: { current: 1, total: 1 },
    response: [
      {
        player: { id: 865, name: "D. Costa", photo: "865.png", type: "Missing Fixture", reason: "Broken ankle" },
        team: { id: 157, name: "Bayern Munich", logo: "157.png" },
        fixture: { id: 686314, timezone: "UTC", date: "2021-04-07T19:00:00+00:00", timestamp: 1617822000 },
        league: { id: 2, season: 2020, name: "UEFA Champions League", country: "World", logo: "2.png", flag: null },
      },
    ],
  },
  predictions: {
    get: "predictions",
    parameters: { fixture: "198772" },
    errors: [],
    results: 1,
    paging: { current: 1, total: 1 },
    response: [
      {
        predictions: {
          winner: { id: 1189, name: "Deportivo Santani", comment: "Win or draw" },
          win_or_draw: true,
          under_over: "-3.5",
          goals: { home: "-2.5", away: "-1.5" },
          advice: "Combo Double chance",
          percent: { home: "45%", draw: "45%", away: "10%" },
        },
        league: { id: 252, name: "Primera Division - Clausura", country: "Paraguay", logo: "252.png", flag: "py.svg", season: 2019, round: "Clausura - 3" },
        teams: {
          home: { id: 1189, name: "Deportivo Santani", logo: "1189.png", last_5: { form: "60%", att: "60%", def: "0%", goals: { for: { total: 3, average: 0.6 }, against: { total: 5, average: 1 } } }, league: {} },
          away: { id: 1180, name: "Deportivo Capiata", logo: "1180.png", last_5: { form: "40%", att: "80%", def: "0%", goals: { for: { total: 4, average: 0.8 }, against: { total: 8, average: 1.6 } } }, league: {} },
        },
        comparison: { form: { home: "60%", away: "40%" }, total: { home: "51.5%", away: "48.5%" } },
        h2h: [],
      },
    ],
  },
  coachs: {
    get: "coachs",
    parameters: { team: "85" },
    errors: [],
    results: 1,
    paging: { current: 1, total: 1 },
    response: [
      {
        id: 40,
        name: "T. Tuchel",
        firstname: "Thomas",
        lastname: "Tuchel",
        age: 47,
        birth: { date: "1973-08-29", place: "Krumbach", country: "Germany" },
        nationality: "Germany",
        height: "192 cm",
        weight: "85 kg",
        photo: "40.png",
        team: { id: 85, name: "PSG", logo: "85.png" },
        career: [{ team: { id: 85, name: "PSG", logo: "85.png" }, start: "2018-07-01", end: null }],
      },
    ],
  },
  playersSeasons: {
    get: "players/seasons",
    parameters: [],
    errors: [],
    results: 4,
    paging: { current: 1, total: 1 },
    response: [2019, 2020, 2021, 2022],
  },
  playerProfiles: {
    get: "players/profiles",
    parameters: { player: "276" },
    errors: [],
    results: 1,
    paging: { current: 1, total: 1 },
    response: [{ player: { id: 276, name: "Neymar", firstname: "Neymar", lastname: "da Silva Santos Junior", age: 32, birth: { date: "1992-02-05", place: "Mogi das Cruzes", country: "Brazil" }, nationality: "Brazil", height: "175 cm", weight: "68 kg", number: 10, position: "Attacker", photo: "276.png" } }],
  },
  players: {
    get: "players",
    parameters: { id: "276", season: "2019" },
    errors: [],
    results: 1,
    paging: { current: 1, total: 1 },
    response: [{ player: { id: 276, name: "Neymar", firstname: "Neymar", lastname: "da Silva Santos Junior", age: 28, birth: { date: "1992-02-05", place: "Mogi das Cruzes", country: "Brazil" }, nationality: "Brazil", height: "175 cm", weight: "68 kg", injured: false, photo: "276.png" }, statistics: [{ team: { id: 85, name: "Paris Saint Germain", logo: "85.png" }, league: { id: 61, name: "Ligue 1", country: "France", logo: "61.png", flag: "fr.svg", season: 2019 }, games: { appearences: 15, lineups: 15, minutes: 1322, number: null, position: "Attacker", rating: "8.053333", captain: false } }] }],
  },
  playerSquads: {
    get: "players/squads",
    parameters: { team: "33" },
    errors: [],
    results: 1,
    paging: { current: 1, total: 1 },
    response: [{ team: { id: 33, name: "Manchester United", logo: "33.png" }, players: [{ id: 20319, name: "N. Bishop", age: 22, number: 30, position: "Goalkeeper", photo: "20319.png" }] }],
  },
  playerTeams: {
    get: "players/teams",
    parameters: { player: "276" },
    errors: [],
    results: 1,
    paging: { current: 1, total: 1 },
    response: [{ team: { id: 6, name: "Brazil", logo: "6.png" }, seasons: [2026, 2023, 2022] }],
  },
  topPlayers: {
    get: "players/topscorers",
    parameters: { league: "39", season: "2023" },
    errors: [],
    results: 1,
    paging: { current: 1, total: 1 },
    response: [{ player: { id: 1, name: "Player Example", firstname: "Player", lastname: "Example", age: 28, birth: { date: "1995-01-01", place: "City", country: "Country" }, nationality: "Country", height: "180 cm", weight: "75 kg", injured: false, photo: "1.png" }, statistics: [] }],
  },
  transfers: {
    get: "transfers",
    parameters: { player: "35845" },
    errors: [],
    results: 1,
    paging: { current: 1, total: 1 },
    response: [{ player: { id: 35845, name: "Hernan Dario Burbano" }, update: "2020-02-06T00:08:15+00:00", transfers: [{ date: "2019-07-15", type: "Free", teams: { in: { id: 2283, name: "Atlas", logo: "2283.png" }, out: { id: 2283, name: "Atlas", logo: "2283.png" } } }] }],
  },
  trophies: {
    get: "trophies",
    parameters: { player: "276" },
    errors: [],
    results: 2,
    paging: { current: 1, total: 1 },
    response: [
      { league: "Sudamericano U20", country: "South-America", season: "Peru 2011", place: "Winner" },
      { league: "Trophee des Champions", country: "France", season: "2019/2020", place: "Winner" },
    ],
  },
  sidelined: {
    get: "sidelined",
    parameters: { player: "276" },
    errors: [],
    results: 2,
    paging: { current: 1, total: 1 },
    response: [
      { type: "Suspended", start: "2020-02-26", end: "2020-03-01" },
      { type: "Hip/Thigh Injury", start: "2020-02-02", end: "2020-02-10" },
    ],
  },
  oddsLive: {
    get: "odds/live",
    parameters: { fixture: "721238" },
    errors: [],
    results: 1,
    paging: { current: 1, total: 1 },
    response: [{ fixture: { id: 721238, status: { long: "Second Half", elapsed: 62, seconds: "62:14" } }, league: { id: 30, season: 2022 }, teams: { home: { id: 1563, goals: 1 }, away: { id: 1565, goals: 0 } }, status: { stopped: false, blocked: false, finished: false }, update: "2022-01-27T16:21:01+00:00", odds: [{ id: 20, name: "Match Corners", values: [{ value: "Over", odd: "2.5", handicap: "8", main: null, suspended: false }] }] }],
  },
  oddsLiveBets: {
    get: "odds/live/bets",
    parameters: [],
    errors: [],
    results: 2,
    paging: { current: 1, total: 1 },
    response: [{ id: 1, name: "Over/Under Extra Time" }, { id: 2, name: "1x2 Extra Time" }],
  },
  odds: {
    get: "odds",
    parameters: { fixture: "326090", bookmaker: "6" },
    errors: [],
    results: 1,
    paging: { current: 1, total: 1 },
    response: [{ league: { id: 116, name: "Vysshaya Liga", country: "Belarus", season: 2020 }, fixture: { id: 326090, timezone: "UTC", date: "2020-05-15T15:00:00+00:00", timestamp: 1589554800 }, update: "2020-05-15T09:49:32+00:00", bookmakers: [{ id: 6, name: "Bwin", bets: [{ id: 38, name: "Exact Goals Number", values: [{ value: 4, odd: "7.00" }] }] }] }],
  },
  oddsMapping: {
    get: "odds/mapping",
    parameters: [],
    errors: [],
    results: 1,
    paging: { current: 1, total: 1 },
    response: [{ league: { id: 106, season: 2019 }, fixture: { id: 154507, date: "2020-05-29T18:30:00+00:00", timestamp: 1590777000 }, update: "2020-05-15T09:52:28+00:00" }],
  },
  oddsBookmakers: {
    get: "odds/bookmakers",
    parameters: [],
    errors: [],
    results: 3,
    paging: { current: 1, total: 1 },
    response: [{ id: 1, name: "10Bet" }, { id: 2, name: "Marathonbet" }, { id: 3, name: "Betfair" }],
  },
  oddsBets: {
    get: "odds/bets",
    parameters: { search: "under" },
    errors: [],
    results: 3,
    paging: { current: 1, total: 1 },
    response: [{ id: 5, name: "Goals Over/Under" }, { id: 6, name: "Goals Over/Under First Half" }],
  },
};
