
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `BestXI` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model BestXI
 * 
 */
export type BestXIModel = runtime.Types.Result.DefaultSelection<Prisma.$BestXIPayload>

export type AggregateBestXI = {
  _count: BestXICountAggregateOutputType | null
  _avg: BestXIAvgAggregateOutputType | null
  _sum: BestXISumAggregateOutputType | null
  _min: BestXIMinAggregateOutputType | null
  _max: BestXIMaxAggregateOutputType | null
}

export type BestXIAvgAggregateOutputType = {
  id: number | null
  tournamentId: number | null
}

export type BestXISumAggregateOutputType = {
  id: number | null
  tournamentId: number | null
}

export type BestXIMinAggregateOutputType = {
  id: number | null
  tournamentId: number | null
  timeframe: string | null
  startDate: Date | null
  endDate: Date | null
  formation: string | null
  createdAt: Date | null
}

export type BestXIMaxAggregateOutputType = {
  id: number | null
  tournamentId: number | null
  timeframe: string | null
  startDate: Date | null
  endDate: Date | null
  formation: string | null
  createdAt: Date | null
}

export type BestXICountAggregateOutputType = {
  id: number
  tournamentId: number
  timeframe: number
  startDate: number
  endDate: number
  formation: number
  createdAt: number
  _all: number
}


export type BestXIAvgAggregateInputType = {
  id?: true
  tournamentId?: true
}

export type BestXISumAggregateInputType = {
  id?: true
  tournamentId?: true
}

export type BestXIMinAggregateInputType = {
  id?: true
  tournamentId?: true
  timeframe?: true
  startDate?: true
  endDate?: true
  formation?: true
  createdAt?: true
}

export type BestXIMaxAggregateInputType = {
  id?: true
  tournamentId?: true
  timeframe?: true
  startDate?: true
  endDate?: true
  formation?: true
  createdAt?: true
}

export type BestXICountAggregateInputType = {
  id?: true
  tournamentId?: true
  timeframe?: true
  startDate?: true
  endDate?: true
  formation?: true
  createdAt?: true
  _all?: true
}

export type BestXIAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BestXI to aggregate.
   */
  where?: Prisma.BestXIWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BestXIS to fetch.
   */
  orderBy?: Prisma.BestXIOrderByWithRelationInput | Prisma.BestXIOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.BestXIWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BestXIS from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BestXIS.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned BestXIS
  **/
  _count?: true | BestXICountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: BestXIAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: BestXISumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: BestXIMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: BestXIMaxAggregateInputType
}

export type GetBestXIAggregateType<T extends BestXIAggregateArgs> = {
      [P in keyof T & keyof AggregateBestXI]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateBestXI[P]>
    : Prisma.GetScalarType<T[P], AggregateBestXI[P]>
}




export type BestXIGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BestXIWhereInput
  orderBy?: Prisma.BestXIOrderByWithAggregationInput | Prisma.BestXIOrderByWithAggregationInput[]
  by: Prisma.BestXIScalarFieldEnum[] | Prisma.BestXIScalarFieldEnum
  having?: Prisma.BestXIScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: BestXICountAggregateInputType | true
  _avg?: BestXIAvgAggregateInputType
  _sum?: BestXISumAggregateInputType
  _min?: BestXIMinAggregateInputType
  _max?: BestXIMaxAggregateInputType
}

export type BestXIGroupByOutputType = {
  id: number
  tournamentId: number
  timeframe: string
  startDate: Date
  endDate: Date
  formation: string
  createdAt: Date
  _count: BestXICountAggregateOutputType | null
  _avg: BestXIAvgAggregateOutputType | null
  _sum: BestXISumAggregateOutputType | null
  _min: BestXIMinAggregateOutputType | null
  _max: BestXIMaxAggregateOutputType | null
}

type GetBestXIGroupByPayload<T extends BestXIGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<BestXIGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof BestXIGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], BestXIGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], BestXIGroupByOutputType[P]>
      }
    >
  >



export type BestXIWhereInput = {
  AND?: Prisma.BestXIWhereInput | Prisma.BestXIWhereInput[]
  OR?: Prisma.BestXIWhereInput[]
  NOT?: Prisma.BestXIWhereInput | Prisma.BestXIWhereInput[]
  id?: Prisma.IntFilter<"BestXI"> | number
  tournamentId?: Prisma.IntFilter<"BestXI"> | number
  timeframe?: Prisma.StringFilter<"BestXI"> | string
  startDate?: Prisma.DateTimeFilter<"BestXI"> | Date | string
  endDate?: Prisma.DateTimeFilter<"BestXI"> | Date | string
  formation?: Prisma.StringFilter<"BestXI"> | string
  createdAt?: Prisma.DateTimeFilter<"BestXI"> | Date | string
  Tournament?: Prisma.XOR<Prisma.TournamentScalarRelationFilter, Prisma.TournamentWhereInput>
  BestXIPlayer?: Prisma.BestXIPlayerListRelationFilter
}

export type BestXIOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  tournamentId?: Prisma.SortOrder
  timeframe?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  formation?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  Tournament?: Prisma.TournamentOrderByWithRelationInput
  BestXIPlayer?: Prisma.BestXIPlayerOrderByRelationAggregateInput
}

export type BestXIWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  tournamentId_timeframe_startDate_endDate?: Prisma.BestXITournamentIdTimeframeStartDateEndDateCompoundUniqueInput
  AND?: Prisma.BestXIWhereInput | Prisma.BestXIWhereInput[]
  OR?: Prisma.BestXIWhereInput[]
  NOT?: Prisma.BestXIWhereInput | Prisma.BestXIWhereInput[]
  tournamentId?: Prisma.IntFilter<"BestXI"> | number
  timeframe?: Prisma.StringFilter<"BestXI"> | string
  startDate?: Prisma.DateTimeFilter<"BestXI"> | Date | string
  endDate?: Prisma.DateTimeFilter<"BestXI"> | Date | string
  formation?: Prisma.StringFilter<"BestXI"> | string
  createdAt?: Prisma.DateTimeFilter<"BestXI"> | Date | string
  Tournament?: Prisma.XOR<Prisma.TournamentScalarRelationFilter, Prisma.TournamentWhereInput>
  BestXIPlayer?: Prisma.BestXIPlayerListRelationFilter
}, "id" | "tournamentId_timeframe_startDate_endDate">

export type BestXIOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  tournamentId?: Prisma.SortOrder
  timeframe?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  formation?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.BestXICountOrderByAggregateInput
  _avg?: Prisma.BestXIAvgOrderByAggregateInput
  _max?: Prisma.BestXIMaxOrderByAggregateInput
  _min?: Prisma.BestXIMinOrderByAggregateInput
  _sum?: Prisma.BestXISumOrderByAggregateInput
}

export type BestXIScalarWhereWithAggregatesInput = {
  AND?: Prisma.BestXIScalarWhereWithAggregatesInput | Prisma.BestXIScalarWhereWithAggregatesInput[]
  OR?: Prisma.BestXIScalarWhereWithAggregatesInput[]
  NOT?: Prisma.BestXIScalarWhereWithAggregatesInput | Prisma.BestXIScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"BestXI"> | number
  tournamentId?: Prisma.IntWithAggregatesFilter<"BestXI"> | number
  timeframe?: Prisma.StringWithAggregatesFilter<"BestXI"> | string
  startDate?: Prisma.DateTimeWithAggregatesFilter<"BestXI"> | Date | string
  endDate?: Prisma.DateTimeWithAggregatesFilter<"BestXI"> | Date | string
  formation?: Prisma.StringWithAggregatesFilter<"BestXI"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"BestXI"> | Date | string
}

export type BestXICreateInput = {
  timeframe: string
  startDate: Date | string
  endDate: Date | string
  formation?: string
  createdAt?: Date | string
  Tournament: Prisma.TournamentCreateNestedOneWithoutBestXIInput
  BestXIPlayer?: Prisma.BestXIPlayerCreateNestedManyWithoutBestXIInput
}

export type BestXIUncheckedCreateInput = {
  id?: number
  tournamentId: number
  timeframe: string
  startDate: Date | string
  endDate: Date | string
  formation?: string
  createdAt?: Date | string
  BestXIPlayer?: Prisma.BestXIPlayerUncheckedCreateNestedManyWithoutBestXIInput
}

export type BestXIUpdateInput = {
  timeframe?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  formation?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Tournament?: Prisma.TournamentUpdateOneRequiredWithoutBestXINestedInput
  BestXIPlayer?: Prisma.BestXIPlayerUpdateManyWithoutBestXINestedInput
}

export type BestXIUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  tournamentId?: Prisma.IntFieldUpdateOperationsInput | number
  timeframe?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  formation?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  BestXIPlayer?: Prisma.BestXIPlayerUncheckedUpdateManyWithoutBestXINestedInput
}

export type BestXICreateManyInput = {
  id?: number
  tournamentId: number
  timeframe: string
  startDate: Date | string
  endDate: Date | string
  formation?: string
  createdAt?: Date | string
}

export type BestXIUpdateManyMutationInput = {
  timeframe?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  formation?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BestXIUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  tournamentId?: Prisma.IntFieldUpdateOperationsInput | number
  timeframe?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  formation?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BestXITournamentIdTimeframeStartDateEndDateCompoundUniqueInput = {
  tournamentId: number
  timeframe: string
  startDate: Date | string
  endDate: Date | string
}

export type BestXICountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tournamentId?: Prisma.SortOrder
  timeframe?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  formation?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type BestXIAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tournamentId?: Prisma.SortOrder
}

export type BestXIMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tournamentId?: Prisma.SortOrder
  timeframe?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  formation?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type BestXIMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tournamentId?: Prisma.SortOrder
  timeframe?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  formation?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type BestXISumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tournamentId?: Prisma.SortOrder
}

export type BestXIScalarRelationFilter = {
  is?: Prisma.BestXIWhereInput
  isNot?: Prisma.BestXIWhereInput
}

export type BestXIListRelationFilter = {
  every?: Prisma.BestXIWhereInput
  some?: Prisma.BestXIWhereInput
  none?: Prisma.BestXIWhereInput
}

export type BestXIOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type BestXICreateNestedOneWithoutBestXIPlayerInput = {
  create?: Prisma.XOR<Prisma.BestXICreateWithoutBestXIPlayerInput, Prisma.BestXIUncheckedCreateWithoutBestXIPlayerInput>
  connectOrCreate?: Prisma.BestXICreateOrConnectWithoutBestXIPlayerInput
  connect?: Prisma.BestXIWhereUniqueInput
}

export type BestXIUpdateOneRequiredWithoutBestXIPlayerNestedInput = {
  create?: Prisma.XOR<Prisma.BestXICreateWithoutBestXIPlayerInput, Prisma.BestXIUncheckedCreateWithoutBestXIPlayerInput>
  connectOrCreate?: Prisma.BestXICreateOrConnectWithoutBestXIPlayerInput
  upsert?: Prisma.BestXIUpsertWithoutBestXIPlayerInput
  connect?: Prisma.BestXIWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.BestXIUpdateToOneWithWhereWithoutBestXIPlayerInput, Prisma.BestXIUpdateWithoutBestXIPlayerInput>, Prisma.BestXIUncheckedUpdateWithoutBestXIPlayerInput>
}

export type BestXICreateNestedManyWithoutTournamentInput = {
  create?: Prisma.XOR<Prisma.BestXICreateWithoutTournamentInput, Prisma.BestXIUncheckedCreateWithoutTournamentInput> | Prisma.BestXICreateWithoutTournamentInput[] | Prisma.BestXIUncheckedCreateWithoutTournamentInput[]
  connectOrCreate?: Prisma.BestXICreateOrConnectWithoutTournamentInput | Prisma.BestXICreateOrConnectWithoutTournamentInput[]
  createMany?: Prisma.BestXICreateManyTournamentInputEnvelope
  connect?: Prisma.BestXIWhereUniqueInput | Prisma.BestXIWhereUniqueInput[]
}

export type BestXIUncheckedCreateNestedManyWithoutTournamentInput = {
  create?: Prisma.XOR<Prisma.BestXICreateWithoutTournamentInput, Prisma.BestXIUncheckedCreateWithoutTournamentInput> | Prisma.BestXICreateWithoutTournamentInput[] | Prisma.BestXIUncheckedCreateWithoutTournamentInput[]
  connectOrCreate?: Prisma.BestXICreateOrConnectWithoutTournamentInput | Prisma.BestXICreateOrConnectWithoutTournamentInput[]
  createMany?: Prisma.BestXICreateManyTournamentInputEnvelope
  connect?: Prisma.BestXIWhereUniqueInput | Prisma.BestXIWhereUniqueInput[]
}

export type BestXIUpdateManyWithoutTournamentNestedInput = {
  create?: Prisma.XOR<Prisma.BestXICreateWithoutTournamentInput, Prisma.BestXIUncheckedCreateWithoutTournamentInput> | Prisma.BestXICreateWithoutTournamentInput[] | Prisma.BestXIUncheckedCreateWithoutTournamentInput[]
  connectOrCreate?: Prisma.BestXICreateOrConnectWithoutTournamentInput | Prisma.BestXICreateOrConnectWithoutTournamentInput[]
  upsert?: Prisma.BestXIUpsertWithWhereUniqueWithoutTournamentInput | Prisma.BestXIUpsertWithWhereUniqueWithoutTournamentInput[]
  createMany?: Prisma.BestXICreateManyTournamentInputEnvelope
  set?: Prisma.BestXIWhereUniqueInput | Prisma.BestXIWhereUniqueInput[]
  disconnect?: Prisma.BestXIWhereUniqueInput | Prisma.BestXIWhereUniqueInput[]
  delete?: Prisma.BestXIWhereUniqueInput | Prisma.BestXIWhereUniqueInput[]
  connect?: Prisma.BestXIWhereUniqueInput | Prisma.BestXIWhereUniqueInput[]
  update?: Prisma.BestXIUpdateWithWhereUniqueWithoutTournamentInput | Prisma.BestXIUpdateWithWhereUniqueWithoutTournamentInput[]
  updateMany?: Prisma.BestXIUpdateManyWithWhereWithoutTournamentInput | Prisma.BestXIUpdateManyWithWhereWithoutTournamentInput[]
  deleteMany?: Prisma.BestXIScalarWhereInput | Prisma.BestXIScalarWhereInput[]
}

export type BestXIUncheckedUpdateManyWithoutTournamentNestedInput = {
  create?: Prisma.XOR<Prisma.BestXICreateWithoutTournamentInput, Prisma.BestXIUncheckedCreateWithoutTournamentInput> | Prisma.BestXICreateWithoutTournamentInput[] | Prisma.BestXIUncheckedCreateWithoutTournamentInput[]
  connectOrCreate?: Prisma.BestXICreateOrConnectWithoutTournamentInput | Prisma.BestXICreateOrConnectWithoutTournamentInput[]
  upsert?: Prisma.BestXIUpsertWithWhereUniqueWithoutTournamentInput | Prisma.BestXIUpsertWithWhereUniqueWithoutTournamentInput[]
  createMany?: Prisma.BestXICreateManyTournamentInputEnvelope
  set?: Prisma.BestXIWhereUniqueInput | Prisma.BestXIWhereUniqueInput[]
  disconnect?: Prisma.BestXIWhereUniqueInput | Prisma.BestXIWhereUniqueInput[]
  delete?: Prisma.BestXIWhereUniqueInput | Prisma.BestXIWhereUniqueInput[]
  connect?: Prisma.BestXIWhereUniqueInput | Prisma.BestXIWhereUniqueInput[]
  update?: Prisma.BestXIUpdateWithWhereUniqueWithoutTournamentInput | Prisma.BestXIUpdateWithWhereUniqueWithoutTournamentInput[]
  updateMany?: Prisma.BestXIUpdateManyWithWhereWithoutTournamentInput | Prisma.BestXIUpdateManyWithWhereWithoutTournamentInput[]
  deleteMany?: Prisma.BestXIScalarWhereInput | Prisma.BestXIScalarWhereInput[]
}

export type BestXICreateWithoutBestXIPlayerInput = {
  timeframe: string
  startDate: Date | string
  endDate: Date | string
  formation?: string
  createdAt?: Date | string
  Tournament: Prisma.TournamentCreateNestedOneWithoutBestXIInput
}

export type BestXIUncheckedCreateWithoutBestXIPlayerInput = {
  id?: number
  tournamentId: number
  timeframe: string
  startDate: Date | string
  endDate: Date | string
  formation?: string
  createdAt?: Date | string
}

export type BestXICreateOrConnectWithoutBestXIPlayerInput = {
  where: Prisma.BestXIWhereUniqueInput
  create: Prisma.XOR<Prisma.BestXICreateWithoutBestXIPlayerInput, Prisma.BestXIUncheckedCreateWithoutBestXIPlayerInput>
}

export type BestXIUpsertWithoutBestXIPlayerInput = {
  update: Prisma.XOR<Prisma.BestXIUpdateWithoutBestXIPlayerInput, Prisma.BestXIUncheckedUpdateWithoutBestXIPlayerInput>
  create: Prisma.XOR<Prisma.BestXICreateWithoutBestXIPlayerInput, Prisma.BestXIUncheckedCreateWithoutBestXIPlayerInput>
  where?: Prisma.BestXIWhereInput
}

export type BestXIUpdateToOneWithWhereWithoutBestXIPlayerInput = {
  where?: Prisma.BestXIWhereInput
  data: Prisma.XOR<Prisma.BestXIUpdateWithoutBestXIPlayerInput, Prisma.BestXIUncheckedUpdateWithoutBestXIPlayerInput>
}

export type BestXIUpdateWithoutBestXIPlayerInput = {
  timeframe?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  formation?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Tournament?: Prisma.TournamentUpdateOneRequiredWithoutBestXINestedInput
}

export type BestXIUncheckedUpdateWithoutBestXIPlayerInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  tournamentId?: Prisma.IntFieldUpdateOperationsInput | number
  timeframe?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  formation?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BestXICreateWithoutTournamentInput = {
  timeframe: string
  startDate: Date | string
  endDate: Date | string
  formation?: string
  createdAt?: Date | string
  BestXIPlayer?: Prisma.BestXIPlayerCreateNestedManyWithoutBestXIInput
}

export type BestXIUncheckedCreateWithoutTournamentInput = {
  id?: number
  timeframe: string
  startDate: Date | string
  endDate: Date | string
  formation?: string
  createdAt?: Date | string
  BestXIPlayer?: Prisma.BestXIPlayerUncheckedCreateNestedManyWithoutBestXIInput
}

export type BestXICreateOrConnectWithoutTournamentInput = {
  where: Prisma.BestXIWhereUniqueInput
  create: Prisma.XOR<Prisma.BestXICreateWithoutTournamentInput, Prisma.BestXIUncheckedCreateWithoutTournamentInput>
}

export type BestXICreateManyTournamentInputEnvelope = {
  data: Prisma.BestXICreateManyTournamentInput | Prisma.BestXICreateManyTournamentInput[]
  skipDuplicates?: boolean
}

export type BestXIUpsertWithWhereUniqueWithoutTournamentInput = {
  where: Prisma.BestXIWhereUniqueInput
  update: Prisma.XOR<Prisma.BestXIUpdateWithoutTournamentInput, Prisma.BestXIUncheckedUpdateWithoutTournamentInput>
  create: Prisma.XOR<Prisma.BestXICreateWithoutTournamentInput, Prisma.BestXIUncheckedCreateWithoutTournamentInput>
}

export type BestXIUpdateWithWhereUniqueWithoutTournamentInput = {
  where: Prisma.BestXIWhereUniqueInput
  data: Prisma.XOR<Prisma.BestXIUpdateWithoutTournamentInput, Prisma.BestXIUncheckedUpdateWithoutTournamentInput>
}

export type BestXIUpdateManyWithWhereWithoutTournamentInput = {
  where: Prisma.BestXIScalarWhereInput
  data: Prisma.XOR<Prisma.BestXIUpdateManyMutationInput, Prisma.BestXIUncheckedUpdateManyWithoutTournamentInput>
}

export type BestXIScalarWhereInput = {
  AND?: Prisma.BestXIScalarWhereInput | Prisma.BestXIScalarWhereInput[]
  OR?: Prisma.BestXIScalarWhereInput[]
  NOT?: Prisma.BestXIScalarWhereInput | Prisma.BestXIScalarWhereInput[]
  id?: Prisma.IntFilter<"BestXI"> | number
  tournamentId?: Prisma.IntFilter<"BestXI"> | number
  timeframe?: Prisma.StringFilter<"BestXI"> | string
  startDate?: Prisma.DateTimeFilter<"BestXI"> | Date | string
  endDate?: Prisma.DateTimeFilter<"BestXI"> | Date | string
  formation?: Prisma.StringFilter<"BestXI"> | string
  createdAt?: Prisma.DateTimeFilter<"BestXI"> | Date | string
}

export type BestXICreateManyTournamentInput = {
  id?: number
  timeframe: string
  startDate: Date | string
  endDate: Date | string
  formation?: string
  createdAt?: Date | string
}

export type BestXIUpdateWithoutTournamentInput = {
  timeframe?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  formation?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  BestXIPlayer?: Prisma.BestXIPlayerUpdateManyWithoutBestXINestedInput
}

export type BestXIUncheckedUpdateWithoutTournamentInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  timeframe?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  formation?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  BestXIPlayer?: Prisma.BestXIPlayerUncheckedUpdateManyWithoutBestXINestedInput
}

export type BestXIUncheckedUpdateManyWithoutTournamentInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  timeframe?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  formation?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type BestXICountOutputType
 */

export type BestXICountOutputType = {
  BestXIPlayer: number
}

export type BestXICountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  BestXIPlayer?: boolean | BestXICountOutputTypeCountBestXIPlayerArgs
}

/**
 * BestXICountOutputType without action
 */
export type BestXICountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BestXICountOutputType
   */
  select?: Prisma.BestXICountOutputTypeSelect<ExtArgs> | null
}

/**
 * BestXICountOutputType without action
 */
export type BestXICountOutputTypeCountBestXIPlayerArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BestXIPlayerWhereInput
}


export type BestXISelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tournamentId?: boolean
  timeframe?: boolean
  startDate?: boolean
  endDate?: boolean
  formation?: boolean
  createdAt?: boolean
  Tournament?: boolean | Prisma.TournamentDefaultArgs<ExtArgs>
  BestXIPlayer?: boolean | Prisma.BestXI$BestXIPlayerArgs<ExtArgs>
  _count?: boolean | Prisma.BestXICountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["bestXI"]>

export type BestXISelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tournamentId?: boolean
  timeframe?: boolean
  startDate?: boolean
  endDate?: boolean
  formation?: boolean
  createdAt?: boolean
  Tournament?: boolean | Prisma.TournamentDefaultArgs<ExtArgs>
}, ExtArgs["result"]["bestXI"]>

export type BestXISelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tournamentId?: boolean
  timeframe?: boolean
  startDate?: boolean
  endDate?: boolean
  formation?: boolean
  createdAt?: boolean
  Tournament?: boolean | Prisma.TournamentDefaultArgs<ExtArgs>
}, ExtArgs["result"]["bestXI"]>

export type BestXISelectScalar = {
  id?: boolean
  tournamentId?: boolean
  timeframe?: boolean
  startDate?: boolean
  endDate?: boolean
  formation?: boolean
  createdAt?: boolean
}

export type BestXIOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "tournamentId" | "timeframe" | "startDate" | "endDate" | "formation" | "createdAt", ExtArgs["result"]["bestXI"]>
export type BestXIInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Tournament?: boolean | Prisma.TournamentDefaultArgs<ExtArgs>
  BestXIPlayer?: boolean | Prisma.BestXI$BestXIPlayerArgs<ExtArgs>
  _count?: boolean | Prisma.BestXICountOutputTypeDefaultArgs<ExtArgs>
}
export type BestXIIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Tournament?: boolean | Prisma.TournamentDefaultArgs<ExtArgs>
}
export type BestXIIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Tournament?: boolean | Prisma.TournamentDefaultArgs<ExtArgs>
}

export type $BestXIPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "BestXI"
  objects: {
    Tournament: Prisma.$TournamentPayload<ExtArgs>
    BestXIPlayer: Prisma.$BestXIPlayerPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    tournamentId: number
    timeframe: string
    startDate: Date
    endDate: Date
    formation: string
    createdAt: Date
  }, ExtArgs["result"]["bestXI"]>
  composites: {}
}

export type BestXIGetPayload<S extends boolean | null | undefined | BestXIDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$BestXIPayload, S>

export type BestXICountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<BestXIFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: BestXICountAggregateInputType | true
  }

export interface BestXIDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['BestXI'], meta: { name: 'BestXI' } }
  /**
   * Find zero or one BestXI that matches the filter.
   * @param {BestXIFindUniqueArgs} args - Arguments to find a BestXI
   * @example
   * // Get one BestXI
   * const bestXI = await prisma.bestXI.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends BestXIFindUniqueArgs>(args: Prisma.SelectSubset<T, BestXIFindUniqueArgs<ExtArgs>>): Prisma.Prisma__BestXIClient<runtime.Types.Result.GetResult<Prisma.$BestXIPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one BestXI that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {BestXIFindUniqueOrThrowArgs} args - Arguments to find a BestXI
   * @example
   * // Get one BestXI
   * const bestXI = await prisma.bestXI.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends BestXIFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, BestXIFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__BestXIClient<runtime.Types.Result.GetResult<Prisma.$BestXIPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BestXI that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BestXIFindFirstArgs} args - Arguments to find a BestXI
   * @example
   * // Get one BestXI
   * const bestXI = await prisma.bestXI.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends BestXIFindFirstArgs>(args?: Prisma.SelectSubset<T, BestXIFindFirstArgs<ExtArgs>>): Prisma.Prisma__BestXIClient<runtime.Types.Result.GetResult<Prisma.$BestXIPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BestXI that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BestXIFindFirstOrThrowArgs} args - Arguments to find a BestXI
   * @example
   * // Get one BestXI
   * const bestXI = await prisma.bestXI.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends BestXIFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, BestXIFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__BestXIClient<runtime.Types.Result.GetResult<Prisma.$BestXIPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more BestXIS that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BestXIFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all BestXIS
   * const bestXIS = await prisma.bestXI.findMany()
   * 
   * // Get first 10 BestXIS
   * const bestXIS = await prisma.bestXI.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const bestXIWithIdOnly = await prisma.bestXI.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends BestXIFindManyArgs>(args?: Prisma.SelectSubset<T, BestXIFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BestXIPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a BestXI.
   * @param {BestXICreateArgs} args - Arguments to create a BestXI.
   * @example
   * // Create one BestXI
   * const BestXI = await prisma.bestXI.create({
   *   data: {
   *     // ... data to create a BestXI
   *   }
   * })
   * 
   */
  create<T extends BestXICreateArgs>(args: Prisma.SelectSubset<T, BestXICreateArgs<ExtArgs>>): Prisma.Prisma__BestXIClient<runtime.Types.Result.GetResult<Prisma.$BestXIPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many BestXIS.
   * @param {BestXICreateManyArgs} args - Arguments to create many BestXIS.
   * @example
   * // Create many BestXIS
   * const bestXI = await prisma.bestXI.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends BestXICreateManyArgs>(args?: Prisma.SelectSubset<T, BestXICreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many BestXIS and returns the data saved in the database.
   * @param {BestXICreateManyAndReturnArgs} args - Arguments to create many BestXIS.
   * @example
   * // Create many BestXIS
   * const bestXI = await prisma.bestXI.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many BestXIS and only return the `id`
   * const bestXIWithIdOnly = await prisma.bestXI.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends BestXICreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, BestXICreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BestXIPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a BestXI.
   * @param {BestXIDeleteArgs} args - Arguments to delete one BestXI.
   * @example
   * // Delete one BestXI
   * const BestXI = await prisma.bestXI.delete({
   *   where: {
   *     // ... filter to delete one BestXI
   *   }
   * })
   * 
   */
  delete<T extends BestXIDeleteArgs>(args: Prisma.SelectSubset<T, BestXIDeleteArgs<ExtArgs>>): Prisma.Prisma__BestXIClient<runtime.Types.Result.GetResult<Prisma.$BestXIPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one BestXI.
   * @param {BestXIUpdateArgs} args - Arguments to update one BestXI.
   * @example
   * // Update one BestXI
   * const bestXI = await prisma.bestXI.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends BestXIUpdateArgs>(args: Prisma.SelectSubset<T, BestXIUpdateArgs<ExtArgs>>): Prisma.Prisma__BestXIClient<runtime.Types.Result.GetResult<Prisma.$BestXIPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more BestXIS.
   * @param {BestXIDeleteManyArgs} args - Arguments to filter BestXIS to delete.
   * @example
   * // Delete a few BestXIS
   * const { count } = await prisma.bestXI.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends BestXIDeleteManyArgs>(args?: Prisma.SelectSubset<T, BestXIDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BestXIS.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BestXIUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many BestXIS
   * const bestXI = await prisma.bestXI.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends BestXIUpdateManyArgs>(args: Prisma.SelectSubset<T, BestXIUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BestXIS and returns the data updated in the database.
   * @param {BestXIUpdateManyAndReturnArgs} args - Arguments to update many BestXIS.
   * @example
   * // Update many BestXIS
   * const bestXI = await prisma.bestXI.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more BestXIS and only return the `id`
   * const bestXIWithIdOnly = await prisma.bestXI.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends BestXIUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, BestXIUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BestXIPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one BestXI.
   * @param {BestXIUpsertArgs} args - Arguments to update or create a BestXI.
   * @example
   * // Update or create a BestXI
   * const bestXI = await prisma.bestXI.upsert({
   *   create: {
   *     // ... data to create a BestXI
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the BestXI we want to update
   *   }
   * })
   */
  upsert<T extends BestXIUpsertArgs>(args: Prisma.SelectSubset<T, BestXIUpsertArgs<ExtArgs>>): Prisma.Prisma__BestXIClient<runtime.Types.Result.GetResult<Prisma.$BestXIPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of BestXIS.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BestXICountArgs} args - Arguments to filter BestXIS to count.
   * @example
   * // Count the number of BestXIS
   * const count = await prisma.bestXI.count({
   *   where: {
   *     // ... the filter for the BestXIS we want to count
   *   }
   * })
  **/
  count<T extends BestXICountArgs>(
    args?: Prisma.Subset<T, BestXICountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], BestXICountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a BestXI.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BestXIAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends BestXIAggregateArgs>(args: Prisma.Subset<T, BestXIAggregateArgs>): Prisma.PrismaPromise<GetBestXIAggregateType<T>>

  /**
   * Group by BestXI.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BestXIGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends BestXIGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: BestXIGroupByArgs['orderBy'] }
      : { orderBy?: BestXIGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, BestXIGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetBestXIGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the BestXI model
 */
readonly fields: BestXIFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for BestXI.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__BestXIClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  Tournament<T extends Prisma.TournamentDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TournamentDefaultArgs<ExtArgs>>): Prisma.Prisma__TournamentClient<runtime.Types.Result.GetResult<Prisma.$TournamentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  BestXIPlayer<T extends Prisma.BestXI$BestXIPlayerArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.BestXI$BestXIPlayerArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BestXIPlayerPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the BestXI model
 */
export interface BestXIFieldRefs {
  readonly id: Prisma.FieldRef<"BestXI", 'Int'>
  readonly tournamentId: Prisma.FieldRef<"BestXI", 'Int'>
  readonly timeframe: Prisma.FieldRef<"BestXI", 'String'>
  readonly startDate: Prisma.FieldRef<"BestXI", 'DateTime'>
  readonly endDate: Prisma.FieldRef<"BestXI", 'DateTime'>
  readonly formation: Prisma.FieldRef<"BestXI", 'String'>
  readonly createdAt: Prisma.FieldRef<"BestXI", 'DateTime'>
}
    

// Custom InputTypes
/**
 * BestXI findUnique
 */
export type BestXIFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BestXI
   */
  select?: Prisma.BestXISelect<ExtArgs> | null
  /**
   * Omit specific fields from the BestXI
   */
  omit?: Prisma.BestXIOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestXIInclude<ExtArgs> | null
  /**
   * Filter, which BestXI to fetch.
   */
  where: Prisma.BestXIWhereUniqueInput
}

/**
 * BestXI findUniqueOrThrow
 */
export type BestXIFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BestXI
   */
  select?: Prisma.BestXISelect<ExtArgs> | null
  /**
   * Omit specific fields from the BestXI
   */
  omit?: Prisma.BestXIOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestXIInclude<ExtArgs> | null
  /**
   * Filter, which BestXI to fetch.
   */
  where: Prisma.BestXIWhereUniqueInput
}

/**
 * BestXI findFirst
 */
export type BestXIFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BestXI
   */
  select?: Prisma.BestXISelect<ExtArgs> | null
  /**
   * Omit specific fields from the BestXI
   */
  omit?: Prisma.BestXIOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestXIInclude<ExtArgs> | null
  /**
   * Filter, which BestXI to fetch.
   */
  where?: Prisma.BestXIWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BestXIS to fetch.
   */
  orderBy?: Prisma.BestXIOrderByWithRelationInput | Prisma.BestXIOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BestXIS.
   */
  cursor?: Prisma.BestXIWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BestXIS from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BestXIS.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BestXIS.
   */
  distinct?: Prisma.BestXIScalarFieldEnum | Prisma.BestXIScalarFieldEnum[]
}

/**
 * BestXI findFirstOrThrow
 */
export type BestXIFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BestXI
   */
  select?: Prisma.BestXISelect<ExtArgs> | null
  /**
   * Omit specific fields from the BestXI
   */
  omit?: Prisma.BestXIOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestXIInclude<ExtArgs> | null
  /**
   * Filter, which BestXI to fetch.
   */
  where?: Prisma.BestXIWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BestXIS to fetch.
   */
  orderBy?: Prisma.BestXIOrderByWithRelationInput | Prisma.BestXIOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BestXIS.
   */
  cursor?: Prisma.BestXIWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BestXIS from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BestXIS.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BestXIS.
   */
  distinct?: Prisma.BestXIScalarFieldEnum | Prisma.BestXIScalarFieldEnum[]
}

/**
 * BestXI findMany
 */
export type BestXIFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BestXI
   */
  select?: Prisma.BestXISelect<ExtArgs> | null
  /**
   * Omit specific fields from the BestXI
   */
  omit?: Prisma.BestXIOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestXIInclude<ExtArgs> | null
  /**
   * Filter, which BestXIS to fetch.
   */
  where?: Prisma.BestXIWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BestXIS to fetch.
   */
  orderBy?: Prisma.BestXIOrderByWithRelationInput | Prisma.BestXIOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing BestXIS.
   */
  cursor?: Prisma.BestXIWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BestXIS from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BestXIS.
   */
  skip?: number
  distinct?: Prisma.BestXIScalarFieldEnum | Prisma.BestXIScalarFieldEnum[]
}

/**
 * BestXI create
 */
export type BestXICreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BestXI
   */
  select?: Prisma.BestXISelect<ExtArgs> | null
  /**
   * Omit specific fields from the BestXI
   */
  omit?: Prisma.BestXIOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestXIInclude<ExtArgs> | null
  /**
   * The data needed to create a BestXI.
   */
  data: Prisma.XOR<Prisma.BestXICreateInput, Prisma.BestXIUncheckedCreateInput>
}

/**
 * BestXI createMany
 */
export type BestXICreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many BestXIS.
   */
  data: Prisma.BestXICreateManyInput | Prisma.BestXICreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * BestXI createManyAndReturn
 */
export type BestXICreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BestXI
   */
  select?: Prisma.BestXISelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BestXI
   */
  omit?: Prisma.BestXIOmit<ExtArgs> | null
  /**
   * The data used to create many BestXIS.
   */
  data: Prisma.BestXICreateManyInput | Prisma.BestXICreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestXIIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * BestXI update
 */
export type BestXIUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BestXI
   */
  select?: Prisma.BestXISelect<ExtArgs> | null
  /**
   * Omit specific fields from the BestXI
   */
  omit?: Prisma.BestXIOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestXIInclude<ExtArgs> | null
  /**
   * The data needed to update a BestXI.
   */
  data: Prisma.XOR<Prisma.BestXIUpdateInput, Prisma.BestXIUncheckedUpdateInput>
  /**
   * Choose, which BestXI to update.
   */
  where: Prisma.BestXIWhereUniqueInput
}

/**
 * BestXI updateMany
 */
export type BestXIUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update BestXIS.
   */
  data: Prisma.XOR<Prisma.BestXIUpdateManyMutationInput, Prisma.BestXIUncheckedUpdateManyInput>
  /**
   * Filter which BestXIS to update
   */
  where?: Prisma.BestXIWhereInput
  /**
   * Limit how many BestXIS to update.
   */
  limit?: number
}

/**
 * BestXI updateManyAndReturn
 */
export type BestXIUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BestXI
   */
  select?: Prisma.BestXISelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BestXI
   */
  omit?: Prisma.BestXIOmit<ExtArgs> | null
  /**
   * The data used to update BestXIS.
   */
  data: Prisma.XOR<Prisma.BestXIUpdateManyMutationInput, Prisma.BestXIUncheckedUpdateManyInput>
  /**
   * Filter which BestXIS to update
   */
  where?: Prisma.BestXIWhereInput
  /**
   * Limit how many BestXIS to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestXIIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * BestXI upsert
 */
export type BestXIUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BestXI
   */
  select?: Prisma.BestXISelect<ExtArgs> | null
  /**
   * Omit specific fields from the BestXI
   */
  omit?: Prisma.BestXIOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestXIInclude<ExtArgs> | null
  /**
   * The filter to search for the BestXI to update in case it exists.
   */
  where: Prisma.BestXIWhereUniqueInput
  /**
   * In case the BestXI found by the `where` argument doesn't exist, create a new BestXI with this data.
   */
  create: Prisma.XOR<Prisma.BestXICreateInput, Prisma.BestXIUncheckedCreateInput>
  /**
   * In case the BestXI was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.BestXIUpdateInput, Prisma.BestXIUncheckedUpdateInput>
}

/**
 * BestXI delete
 */
export type BestXIDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BestXI
   */
  select?: Prisma.BestXISelect<ExtArgs> | null
  /**
   * Omit specific fields from the BestXI
   */
  omit?: Prisma.BestXIOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestXIInclude<ExtArgs> | null
  /**
   * Filter which BestXI to delete.
   */
  where: Prisma.BestXIWhereUniqueInput
}

/**
 * BestXI deleteMany
 */
export type BestXIDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BestXIS to delete
   */
  where?: Prisma.BestXIWhereInput
  /**
   * Limit how many BestXIS to delete.
   */
  limit?: number
}

/**
 * BestXI.BestXIPlayer
 */
export type BestXI$BestXIPlayerArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BestXIPlayer
   */
  select?: Prisma.BestXIPlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BestXIPlayer
   */
  omit?: Prisma.BestXIPlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestXIPlayerInclude<ExtArgs> | null
  where?: Prisma.BestXIPlayerWhereInput
  orderBy?: Prisma.BestXIPlayerOrderByWithRelationInput | Prisma.BestXIPlayerOrderByWithRelationInput[]
  cursor?: Prisma.BestXIPlayerWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.BestXIPlayerScalarFieldEnum | Prisma.BestXIPlayerScalarFieldEnum[]
}

/**
 * BestXI without action
 */
export type BestXIDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BestXI
   */
  select?: Prisma.BestXISelect<ExtArgs> | null
  /**
   * Omit specific fields from the BestXI
   */
  omit?: Prisma.BestXIOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestXIInclude<ExtArgs> | null
}
