
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `BestXIPlayer` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model BestXIPlayer
 * 
 */
export type BestXIPlayerModel = runtime.Types.Result.DefaultSelection<Prisma.$BestXIPlayerPayload>

export type AggregateBestXIPlayer = {
  _count: BestXIPlayerCountAggregateOutputType | null
  _avg: BestXIPlayerAvgAggregateOutputType | null
  _sum: BestXIPlayerSumAggregateOutputType | null
  _min: BestXIPlayerMinAggregateOutputType | null
  _max: BestXIPlayerMaxAggregateOutputType | null
}

export type BestXIPlayerAvgAggregateOutputType = {
  id: number | null
  bestXIId: number | null
  teamId: number | null
  rating: number | null
  positionIndex: number | null
  playerId: number | null
}

export type BestXIPlayerSumAggregateOutputType = {
  id: number | null
  bestXIId: number | null
  teamId: number | null
  rating: number | null
  positionIndex: number | null
  playerId: number | null
}

export type BestXIPlayerMinAggregateOutputType = {
  id: number | null
  bestXIId: number | null
  teamId: number | null
  playerName: string | null
  rating: number | null
  positionLabel: string | null
  positionIndex: number | null
  playerId: number | null
}

export type BestXIPlayerMaxAggregateOutputType = {
  id: number | null
  bestXIId: number | null
  teamId: number | null
  playerName: string | null
  rating: number | null
  positionLabel: string | null
  positionIndex: number | null
  playerId: number | null
}

export type BestXIPlayerCountAggregateOutputType = {
  id: number
  bestXIId: number
  teamId: number
  playerName: number
  rating: number
  positionLabel: number
  positionIndex: number
  playerId: number
  _all: number
}


export type BestXIPlayerAvgAggregateInputType = {
  id?: true
  bestXIId?: true
  teamId?: true
  rating?: true
  positionIndex?: true
  playerId?: true
}

export type BestXIPlayerSumAggregateInputType = {
  id?: true
  bestXIId?: true
  teamId?: true
  rating?: true
  positionIndex?: true
  playerId?: true
}

export type BestXIPlayerMinAggregateInputType = {
  id?: true
  bestXIId?: true
  teamId?: true
  playerName?: true
  rating?: true
  positionLabel?: true
  positionIndex?: true
  playerId?: true
}

export type BestXIPlayerMaxAggregateInputType = {
  id?: true
  bestXIId?: true
  teamId?: true
  playerName?: true
  rating?: true
  positionLabel?: true
  positionIndex?: true
  playerId?: true
}

export type BestXIPlayerCountAggregateInputType = {
  id?: true
  bestXIId?: true
  teamId?: true
  playerName?: true
  rating?: true
  positionLabel?: true
  positionIndex?: true
  playerId?: true
  _all?: true
}

export type BestXIPlayerAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BestXIPlayer to aggregate.
   */
  where?: Prisma.BestXIPlayerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BestXIPlayers to fetch.
   */
  orderBy?: Prisma.BestXIPlayerOrderByWithRelationInput | Prisma.BestXIPlayerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.BestXIPlayerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BestXIPlayers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BestXIPlayers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned BestXIPlayers
  **/
  _count?: true | BestXIPlayerCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: BestXIPlayerAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: BestXIPlayerSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: BestXIPlayerMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: BestXIPlayerMaxAggregateInputType
}

export type GetBestXIPlayerAggregateType<T extends BestXIPlayerAggregateArgs> = {
      [P in keyof T & keyof AggregateBestXIPlayer]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateBestXIPlayer[P]>
    : Prisma.GetScalarType<T[P], AggregateBestXIPlayer[P]>
}




export type BestXIPlayerGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BestXIPlayerWhereInput
  orderBy?: Prisma.BestXIPlayerOrderByWithAggregationInput | Prisma.BestXIPlayerOrderByWithAggregationInput[]
  by: Prisma.BestXIPlayerScalarFieldEnum[] | Prisma.BestXIPlayerScalarFieldEnum
  having?: Prisma.BestXIPlayerScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: BestXIPlayerCountAggregateInputType | true
  _avg?: BestXIPlayerAvgAggregateInputType
  _sum?: BestXIPlayerSumAggregateInputType
  _min?: BestXIPlayerMinAggregateInputType
  _max?: BestXIPlayerMaxAggregateInputType
}

export type BestXIPlayerGroupByOutputType = {
  id: number
  bestXIId: number
  teamId: number
  playerName: string
  rating: number
  positionLabel: string
  positionIndex: number
  playerId: number | null
  _count: BestXIPlayerCountAggregateOutputType | null
  _avg: BestXIPlayerAvgAggregateOutputType | null
  _sum: BestXIPlayerSumAggregateOutputType | null
  _min: BestXIPlayerMinAggregateOutputType | null
  _max: BestXIPlayerMaxAggregateOutputType | null
}

type GetBestXIPlayerGroupByPayload<T extends BestXIPlayerGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<BestXIPlayerGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof BestXIPlayerGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], BestXIPlayerGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], BestXIPlayerGroupByOutputType[P]>
      }
    >
  >



export type BestXIPlayerWhereInput = {
  AND?: Prisma.BestXIPlayerWhereInput | Prisma.BestXIPlayerWhereInput[]
  OR?: Prisma.BestXIPlayerWhereInput[]
  NOT?: Prisma.BestXIPlayerWhereInput | Prisma.BestXIPlayerWhereInput[]
  id?: Prisma.IntFilter<"BestXIPlayer"> | number
  bestXIId?: Prisma.IntFilter<"BestXIPlayer"> | number
  teamId?: Prisma.IntFilter<"BestXIPlayer"> | number
  playerName?: Prisma.StringFilter<"BestXIPlayer"> | string
  rating?: Prisma.FloatFilter<"BestXIPlayer"> | number
  positionLabel?: Prisma.StringFilter<"BestXIPlayer"> | string
  positionIndex?: Prisma.IntFilter<"BestXIPlayer"> | number
  playerId?: Prisma.IntNullableFilter<"BestXIPlayer"> | number | null
  BestXI?: Prisma.XOR<Prisma.BestXIScalarRelationFilter, Prisma.BestXIWhereInput>
  Player?: Prisma.XOR<Prisma.PlayerNullableScalarRelationFilter, Prisma.PlayerWhereInput> | null
  Team?: Prisma.XOR<Prisma.TeamScalarRelationFilter, Prisma.TeamWhereInput>
}

export type BestXIPlayerOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  bestXIId?: Prisma.SortOrder
  teamId?: Prisma.SortOrder
  playerName?: Prisma.SortOrder
  rating?: Prisma.SortOrder
  positionLabel?: Prisma.SortOrder
  positionIndex?: Prisma.SortOrder
  playerId?: Prisma.SortOrderInput | Prisma.SortOrder
  BestXI?: Prisma.BestXIOrderByWithRelationInput
  Player?: Prisma.PlayerOrderByWithRelationInput
  Team?: Prisma.TeamOrderByWithRelationInput
}

export type BestXIPlayerWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.BestXIPlayerWhereInput | Prisma.BestXIPlayerWhereInput[]
  OR?: Prisma.BestXIPlayerWhereInput[]
  NOT?: Prisma.BestXIPlayerWhereInput | Prisma.BestXIPlayerWhereInput[]
  bestXIId?: Prisma.IntFilter<"BestXIPlayer"> | number
  teamId?: Prisma.IntFilter<"BestXIPlayer"> | number
  playerName?: Prisma.StringFilter<"BestXIPlayer"> | string
  rating?: Prisma.FloatFilter<"BestXIPlayer"> | number
  positionLabel?: Prisma.StringFilter<"BestXIPlayer"> | string
  positionIndex?: Prisma.IntFilter<"BestXIPlayer"> | number
  playerId?: Prisma.IntNullableFilter<"BestXIPlayer"> | number | null
  BestXI?: Prisma.XOR<Prisma.BestXIScalarRelationFilter, Prisma.BestXIWhereInput>
  Player?: Prisma.XOR<Prisma.PlayerNullableScalarRelationFilter, Prisma.PlayerWhereInput> | null
  Team?: Prisma.XOR<Prisma.TeamScalarRelationFilter, Prisma.TeamWhereInput>
}, "id">

export type BestXIPlayerOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  bestXIId?: Prisma.SortOrder
  teamId?: Prisma.SortOrder
  playerName?: Prisma.SortOrder
  rating?: Prisma.SortOrder
  positionLabel?: Prisma.SortOrder
  positionIndex?: Prisma.SortOrder
  playerId?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.BestXIPlayerCountOrderByAggregateInput
  _avg?: Prisma.BestXIPlayerAvgOrderByAggregateInput
  _max?: Prisma.BestXIPlayerMaxOrderByAggregateInput
  _min?: Prisma.BestXIPlayerMinOrderByAggregateInput
  _sum?: Prisma.BestXIPlayerSumOrderByAggregateInput
}

export type BestXIPlayerScalarWhereWithAggregatesInput = {
  AND?: Prisma.BestXIPlayerScalarWhereWithAggregatesInput | Prisma.BestXIPlayerScalarWhereWithAggregatesInput[]
  OR?: Prisma.BestXIPlayerScalarWhereWithAggregatesInput[]
  NOT?: Prisma.BestXIPlayerScalarWhereWithAggregatesInput | Prisma.BestXIPlayerScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"BestXIPlayer"> | number
  bestXIId?: Prisma.IntWithAggregatesFilter<"BestXIPlayer"> | number
  teamId?: Prisma.IntWithAggregatesFilter<"BestXIPlayer"> | number
  playerName?: Prisma.StringWithAggregatesFilter<"BestXIPlayer"> | string
  rating?: Prisma.FloatWithAggregatesFilter<"BestXIPlayer"> | number
  positionLabel?: Prisma.StringWithAggregatesFilter<"BestXIPlayer"> | string
  positionIndex?: Prisma.IntWithAggregatesFilter<"BestXIPlayer"> | number
  playerId?: Prisma.IntNullableWithAggregatesFilter<"BestXIPlayer"> | number | null
}

export type BestXIPlayerCreateInput = {
  playerName: string
  rating: number
  positionLabel: string
  positionIndex: number
  BestXI: Prisma.BestXICreateNestedOneWithoutBestXIPlayerInput
  Player?: Prisma.PlayerCreateNestedOneWithoutBestXIPlayerInput
  Team: Prisma.TeamCreateNestedOneWithoutBestXIPlayerInput
}

export type BestXIPlayerUncheckedCreateInput = {
  id?: number
  bestXIId: number
  teamId: number
  playerName: string
  rating: number
  positionLabel: string
  positionIndex: number
  playerId?: number | null
}

export type BestXIPlayerUpdateInput = {
  playerName?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.FloatFieldUpdateOperationsInput | number
  positionLabel?: Prisma.StringFieldUpdateOperationsInput | string
  positionIndex?: Prisma.IntFieldUpdateOperationsInput | number
  BestXI?: Prisma.BestXIUpdateOneRequiredWithoutBestXIPlayerNestedInput
  Player?: Prisma.PlayerUpdateOneWithoutBestXIPlayerNestedInput
  Team?: Prisma.TeamUpdateOneRequiredWithoutBestXIPlayerNestedInput
}

export type BestXIPlayerUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  bestXIId?: Prisma.IntFieldUpdateOperationsInput | number
  teamId?: Prisma.IntFieldUpdateOperationsInput | number
  playerName?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.FloatFieldUpdateOperationsInput | number
  positionLabel?: Prisma.StringFieldUpdateOperationsInput | string
  positionIndex?: Prisma.IntFieldUpdateOperationsInput | number
  playerId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type BestXIPlayerCreateManyInput = {
  id?: number
  bestXIId: number
  teamId: number
  playerName: string
  rating: number
  positionLabel: string
  positionIndex: number
  playerId?: number | null
}

export type BestXIPlayerUpdateManyMutationInput = {
  playerName?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.FloatFieldUpdateOperationsInput | number
  positionLabel?: Prisma.StringFieldUpdateOperationsInput | string
  positionIndex?: Prisma.IntFieldUpdateOperationsInput | number
}

export type BestXIPlayerUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  bestXIId?: Prisma.IntFieldUpdateOperationsInput | number
  teamId?: Prisma.IntFieldUpdateOperationsInput | number
  playerName?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.FloatFieldUpdateOperationsInput | number
  positionLabel?: Prisma.StringFieldUpdateOperationsInput | string
  positionIndex?: Prisma.IntFieldUpdateOperationsInput | number
  playerId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type BestXIPlayerListRelationFilter = {
  every?: Prisma.BestXIPlayerWhereInput
  some?: Prisma.BestXIPlayerWhereInput
  none?: Prisma.BestXIPlayerWhereInput
}

export type BestXIPlayerOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type BestXIPlayerCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  bestXIId?: Prisma.SortOrder
  teamId?: Prisma.SortOrder
  playerName?: Prisma.SortOrder
  rating?: Prisma.SortOrder
  positionLabel?: Prisma.SortOrder
  positionIndex?: Prisma.SortOrder
  playerId?: Prisma.SortOrder
}

export type BestXIPlayerAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  bestXIId?: Prisma.SortOrder
  teamId?: Prisma.SortOrder
  rating?: Prisma.SortOrder
  positionIndex?: Prisma.SortOrder
  playerId?: Prisma.SortOrder
}

export type BestXIPlayerMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  bestXIId?: Prisma.SortOrder
  teamId?: Prisma.SortOrder
  playerName?: Prisma.SortOrder
  rating?: Prisma.SortOrder
  positionLabel?: Prisma.SortOrder
  positionIndex?: Prisma.SortOrder
  playerId?: Prisma.SortOrder
}

export type BestXIPlayerMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  bestXIId?: Prisma.SortOrder
  teamId?: Prisma.SortOrder
  playerName?: Prisma.SortOrder
  rating?: Prisma.SortOrder
  positionLabel?: Prisma.SortOrder
  positionIndex?: Prisma.SortOrder
  playerId?: Prisma.SortOrder
}

export type BestXIPlayerSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  bestXIId?: Prisma.SortOrder
  teamId?: Prisma.SortOrder
  rating?: Prisma.SortOrder
  positionIndex?: Prisma.SortOrder
  playerId?: Prisma.SortOrder
}

export type BestXIPlayerCreateNestedManyWithoutBestXIInput = {
  create?: Prisma.XOR<Prisma.BestXIPlayerCreateWithoutBestXIInput, Prisma.BestXIPlayerUncheckedCreateWithoutBestXIInput> | Prisma.BestXIPlayerCreateWithoutBestXIInput[] | Prisma.BestXIPlayerUncheckedCreateWithoutBestXIInput[]
  connectOrCreate?: Prisma.BestXIPlayerCreateOrConnectWithoutBestXIInput | Prisma.BestXIPlayerCreateOrConnectWithoutBestXIInput[]
  createMany?: Prisma.BestXIPlayerCreateManyBestXIInputEnvelope
  connect?: Prisma.BestXIPlayerWhereUniqueInput | Prisma.BestXIPlayerWhereUniqueInput[]
}

export type BestXIPlayerUncheckedCreateNestedManyWithoutBestXIInput = {
  create?: Prisma.XOR<Prisma.BestXIPlayerCreateWithoutBestXIInput, Prisma.BestXIPlayerUncheckedCreateWithoutBestXIInput> | Prisma.BestXIPlayerCreateWithoutBestXIInput[] | Prisma.BestXIPlayerUncheckedCreateWithoutBestXIInput[]
  connectOrCreate?: Prisma.BestXIPlayerCreateOrConnectWithoutBestXIInput | Prisma.BestXIPlayerCreateOrConnectWithoutBestXIInput[]
  createMany?: Prisma.BestXIPlayerCreateManyBestXIInputEnvelope
  connect?: Prisma.BestXIPlayerWhereUniqueInput | Prisma.BestXIPlayerWhereUniqueInput[]
}

export type BestXIPlayerUpdateManyWithoutBestXINestedInput = {
  create?: Prisma.XOR<Prisma.BestXIPlayerCreateWithoutBestXIInput, Prisma.BestXIPlayerUncheckedCreateWithoutBestXIInput> | Prisma.BestXIPlayerCreateWithoutBestXIInput[] | Prisma.BestXIPlayerUncheckedCreateWithoutBestXIInput[]
  connectOrCreate?: Prisma.BestXIPlayerCreateOrConnectWithoutBestXIInput | Prisma.BestXIPlayerCreateOrConnectWithoutBestXIInput[]
  upsert?: Prisma.BestXIPlayerUpsertWithWhereUniqueWithoutBestXIInput | Prisma.BestXIPlayerUpsertWithWhereUniqueWithoutBestXIInput[]
  createMany?: Prisma.BestXIPlayerCreateManyBestXIInputEnvelope
  set?: Prisma.BestXIPlayerWhereUniqueInput | Prisma.BestXIPlayerWhereUniqueInput[]
  disconnect?: Prisma.BestXIPlayerWhereUniqueInput | Prisma.BestXIPlayerWhereUniqueInput[]
  delete?: Prisma.BestXIPlayerWhereUniqueInput | Prisma.BestXIPlayerWhereUniqueInput[]
  connect?: Prisma.BestXIPlayerWhereUniqueInput | Prisma.BestXIPlayerWhereUniqueInput[]
  update?: Prisma.BestXIPlayerUpdateWithWhereUniqueWithoutBestXIInput | Prisma.BestXIPlayerUpdateWithWhereUniqueWithoutBestXIInput[]
  updateMany?: Prisma.BestXIPlayerUpdateManyWithWhereWithoutBestXIInput | Prisma.BestXIPlayerUpdateManyWithWhereWithoutBestXIInput[]
  deleteMany?: Prisma.BestXIPlayerScalarWhereInput | Prisma.BestXIPlayerScalarWhereInput[]
}

export type BestXIPlayerUncheckedUpdateManyWithoutBestXINestedInput = {
  create?: Prisma.XOR<Prisma.BestXIPlayerCreateWithoutBestXIInput, Prisma.BestXIPlayerUncheckedCreateWithoutBestXIInput> | Prisma.BestXIPlayerCreateWithoutBestXIInput[] | Prisma.BestXIPlayerUncheckedCreateWithoutBestXIInput[]
  connectOrCreate?: Prisma.BestXIPlayerCreateOrConnectWithoutBestXIInput | Prisma.BestXIPlayerCreateOrConnectWithoutBestXIInput[]
  upsert?: Prisma.BestXIPlayerUpsertWithWhereUniqueWithoutBestXIInput | Prisma.BestXIPlayerUpsertWithWhereUniqueWithoutBestXIInput[]
  createMany?: Prisma.BestXIPlayerCreateManyBestXIInputEnvelope
  set?: Prisma.BestXIPlayerWhereUniqueInput | Prisma.BestXIPlayerWhereUniqueInput[]
  disconnect?: Prisma.BestXIPlayerWhereUniqueInput | Prisma.BestXIPlayerWhereUniqueInput[]
  delete?: Prisma.BestXIPlayerWhereUniqueInput | Prisma.BestXIPlayerWhereUniqueInput[]
  connect?: Prisma.BestXIPlayerWhereUniqueInput | Prisma.BestXIPlayerWhereUniqueInput[]
  update?: Prisma.BestXIPlayerUpdateWithWhereUniqueWithoutBestXIInput | Prisma.BestXIPlayerUpdateWithWhereUniqueWithoutBestXIInput[]
  updateMany?: Prisma.BestXIPlayerUpdateManyWithWhereWithoutBestXIInput | Prisma.BestXIPlayerUpdateManyWithWhereWithoutBestXIInput[]
  deleteMany?: Prisma.BestXIPlayerScalarWhereInput | Prisma.BestXIPlayerScalarWhereInput[]
}

export type FloatFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type BestXIPlayerCreateNestedManyWithoutPlayerInput = {
  create?: Prisma.XOR<Prisma.BestXIPlayerCreateWithoutPlayerInput, Prisma.BestXIPlayerUncheckedCreateWithoutPlayerInput> | Prisma.BestXIPlayerCreateWithoutPlayerInput[] | Prisma.BestXIPlayerUncheckedCreateWithoutPlayerInput[]
  connectOrCreate?: Prisma.BestXIPlayerCreateOrConnectWithoutPlayerInput | Prisma.BestXIPlayerCreateOrConnectWithoutPlayerInput[]
  createMany?: Prisma.BestXIPlayerCreateManyPlayerInputEnvelope
  connect?: Prisma.BestXIPlayerWhereUniqueInput | Prisma.BestXIPlayerWhereUniqueInput[]
}

export type BestXIPlayerUncheckedCreateNestedManyWithoutPlayerInput = {
  create?: Prisma.XOR<Prisma.BestXIPlayerCreateWithoutPlayerInput, Prisma.BestXIPlayerUncheckedCreateWithoutPlayerInput> | Prisma.BestXIPlayerCreateWithoutPlayerInput[] | Prisma.BestXIPlayerUncheckedCreateWithoutPlayerInput[]
  connectOrCreate?: Prisma.BestXIPlayerCreateOrConnectWithoutPlayerInput | Prisma.BestXIPlayerCreateOrConnectWithoutPlayerInput[]
  createMany?: Prisma.BestXIPlayerCreateManyPlayerInputEnvelope
  connect?: Prisma.BestXIPlayerWhereUniqueInput | Prisma.BestXIPlayerWhereUniqueInput[]
}

export type BestXIPlayerUpdateManyWithoutPlayerNestedInput = {
  create?: Prisma.XOR<Prisma.BestXIPlayerCreateWithoutPlayerInput, Prisma.BestXIPlayerUncheckedCreateWithoutPlayerInput> | Prisma.BestXIPlayerCreateWithoutPlayerInput[] | Prisma.BestXIPlayerUncheckedCreateWithoutPlayerInput[]
  connectOrCreate?: Prisma.BestXIPlayerCreateOrConnectWithoutPlayerInput | Prisma.BestXIPlayerCreateOrConnectWithoutPlayerInput[]
  upsert?: Prisma.BestXIPlayerUpsertWithWhereUniqueWithoutPlayerInput | Prisma.BestXIPlayerUpsertWithWhereUniqueWithoutPlayerInput[]
  createMany?: Prisma.BestXIPlayerCreateManyPlayerInputEnvelope
  set?: Prisma.BestXIPlayerWhereUniqueInput | Prisma.BestXIPlayerWhereUniqueInput[]
  disconnect?: Prisma.BestXIPlayerWhereUniqueInput | Prisma.BestXIPlayerWhereUniqueInput[]
  delete?: Prisma.BestXIPlayerWhereUniqueInput | Prisma.BestXIPlayerWhereUniqueInput[]
  connect?: Prisma.BestXIPlayerWhereUniqueInput | Prisma.BestXIPlayerWhereUniqueInput[]
  update?: Prisma.BestXIPlayerUpdateWithWhereUniqueWithoutPlayerInput | Prisma.BestXIPlayerUpdateWithWhereUniqueWithoutPlayerInput[]
  updateMany?: Prisma.BestXIPlayerUpdateManyWithWhereWithoutPlayerInput | Prisma.BestXIPlayerUpdateManyWithWhereWithoutPlayerInput[]
  deleteMany?: Prisma.BestXIPlayerScalarWhereInput | Prisma.BestXIPlayerScalarWhereInput[]
}

export type BestXIPlayerUncheckedUpdateManyWithoutPlayerNestedInput = {
  create?: Prisma.XOR<Prisma.BestXIPlayerCreateWithoutPlayerInput, Prisma.BestXIPlayerUncheckedCreateWithoutPlayerInput> | Prisma.BestXIPlayerCreateWithoutPlayerInput[] | Prisma.BestXIPlayerUncheckedCreateWithoutPlayerInput[]
  connectOrCreate?: Prisma.BestXIPlayerCreateOrConnectWithoutPlayerInput | Prisma.BestXIPlayerCreateOrConnectWithoutPlayerInput[]
  upsert?: Prisma.BestXIPlayerUpsertWithWhereUniqueWithoutPlayerInput | Prisma.BestXIPlayerUpsertWithWhereUniqueWithoutPlayerInput[]
  createMany?: Prisma.BestXIPlayerCreateManyPlayerInputEnvelope
  set?: Prisma.BestXIPlayerWhereUniqueInput | Prisma.BestXIPlayerWhereUniqueInput[]
  disconnect?: Prisma.BestXIPlayerWhereUniqueInput | Prisma.BestXIPlayerWhereUniqueInput[]
  delete?: Prisma.BestXIPlayerWhereUniqueInput | Prisma.BestXIPlayerWhereUniqueInput[]
  connect?: Prisma.BestXIPlayerWhereUniqueInput | Prisma.BestXIPlayerWhereUniqueInput[]
  update?: Prisma.BestXIPlayerUpdateWithWhereUniqueWithoutPlayerInput | Prisma.BestXIPlayerUpdateWithWhereUniqueWithoutPlayerInput[]
  updateMany?: Prisma.BestXIPlayerUpdateManyWithWhereWithoutPlayerInput | Prisma.BestXIPlayerUpdateManyWithWhereWithoutPlayerInput[]
  deleteMany?: Prisma.BestXIPlayerScalarWhereInput | Prisma.BestXIPlayerScalarWhereInput[]
}

export type BestXIPlayerCreateNestedManyWithoutTeamInput = {
  create?: Prisma.XOR<Prisma.BestXIPlayerCreateWithoutTeamInput, Prisma.BestXIPlayerUncheckedCreateWithoutTeamInput> | Prisma.BestXIPlayerCreateWithoutTeamInput[] | Prisma.BestXIPlayerUncheckedCreateWithoutTeamInput[]
  connectOrCreate?: Prisma.BestXIPlayerCreateOrConnectWithoutTeamInput | Prisma.BestXIPlayerCreateOrConnectWithoutTeamInput[]
  createMany?: Prisma.BestXIPlayerCreateManyTeamInputEnvelope
  connect?: Prisma.BestXIPlayerWhereUniqueInput | Prisma.BestXIPlayerWhereUniqueInput[]
}

export type BestXIPlayerUncheckedCreateNestedManyWithoutTeamInput = {
  create?: Prisma.XOR<Prisma.BestXIPlayerCreateWithoutTeamInput, Prisma.BestXIPlayerUncheckedCreateWithoutTeamInput> | Prisma.BestXIPlayerCreateWithoutTeamInput[] | Prisma.BestXIPlayerUncheckedCreateWithoutTeamInput[]
  connectOrCreate?: Prisma.BestXIPlayerCreateOrConnectWithoutTeamInput | Prisma.BestXIPlayerCreateOrConnectWithoutTeamInput[]
  createMany?: Prisma.BestXIPlayerCreateManyTeamInputEnvelope
  connect?: Prisma.BestXIPlayerWhereUniqueInput | Prisma.BestXIPlayerWhereUniqueInput[]
}

export type BestXIPlayerUpdateManyWithoutTeamNestedInput = {
  create?: Prisma.XOR<Prisma.BestXIPlayerCreateWithoutTeamInput, Prisma.BestXIPlayerUncheckedCreateWithoutTeamInput> | Prisma.BestXIPlayerCreateWithoutTeamInput[] | Prisma.BestXIPlayerUncheckedCreateWithoutTeamInput[]
  connectOrCreate?: Prisma.BestXIPlayerCreateOrConnectWithoutTeamInput | Prisma.BestXIPlayerCreateOrConnectWithoutTeamInput[]
  upsert?: Prisma.BestXIPlayerUpsertWithWhereUniqueWithoutTeamInput | Prisma.BestXIPlayerUpsertWithWhereUniqueWithoutTeamInput[]
  createMany?: Prisma.BestXIPlayerCreateManyTeamInputEnvelope
  set?: Prisma.BestXIPlayerWhereUniqueInput | Prisma.BestXIPlayerWhereUniqueInput[]
  disconnect?: Prisma.BestXIPlayerWhereUniqueInput | Prisma.BestXIPlayerWhereUniqueInput[]
  delete?: Prisma.BestXIPlayerWhereUniqueInput | Prisma.BestXIPlayerWhereUniqueInput[]
  connect?: Prisma.BestXIPlayerWhereUniqueInput | Prisma.BestXIPlayerWhereUniqueInput[]
  update?: Prisma.BestXIPlayerUpdateWithWhereUniqueWithoutTeamInput | Prisma.BestXIPlayerUpdateWithWhereUniqueWithoutTeamInput[]
  updateMany?: Prisma.BestXIPlayerUpdateManyWithWhereWithoutTeamInput | Prisma.BestXIPlayerUpdateManyWithWhereWithoutTeamInput[]
  deleteMany?: Prisma.BestXIPlayerScalarWhereInput | Prisma.BestXIPlayerScalarWhereInput[]
}

export type BestXIPlayerUncheckedUpdateManyWithoutTeamNestedInput = {
  create?: Prisma.XOR<Prisma.BestXIPlayerCreateWithoutTeamInput, Prisma.BestXIPlayerUncheckedCreateWithoutTeamInput> | Prisma.BestXIPlayerCreateWithoutTeamInput[] | Prisma.BestXIPlayerUncheckedCreateWithoutTeamInput[]
  connectOrCreate?: Prisma.BestXIPlayerCreateOrConnectWithoutTeamInput | Prisma.BestXIPlayerCreateOrConnectWithoutTeamInput[]
  upsert?: Prisma.BestXIPlayerUpsertWithWhereUniqueWithoutTeamInput | Prisma.BestXIPlayerUpsertWithWhereUniqueWithoutTeamInput[]
  createMany?: Prisma.BestXIPlayerCreateManyTeamInputEnvelope
  set?: Prisma.BestXIPlayerWhereUniqueInput | Prisma.BestXIPlayerWhereUniqueInput[]
  disconnect?: Prisma.BestXIPlayerWhereUniqueInput | Prisma.BestXIPlayerWhereUniqueInput[]
  delete?: Prisma.BestXIPlayerWhereUniqueInput | Prisma.BestXIPlayerWhereUniqueInput[]
  connect?: Prisma.BestXIPlayerWhereUniqueInput | Prisma.BestXIPlayerWhereUniqueInput[]
  update?: Prisma.BestXIPlayerUpdateWithWhereUniqueWithoutTeamInput | Prisma.BestXIPlayerUpdateWithWhereUniqueWithoutTeamInput[]
  updateMany?: Prisma.BestXIPlayerUpdateManyWithWhereWithoutTeamInput | Prisma.BestXIPlayerUpdateManyWithWhereWithoutTeamInput[]
  deleteMany?: Prisma.BestXIPlayerScalarWhereInput | Prisma.BestXIPlayerScalarWhereInput[]
}

export type BestXIPlayerCreateWithoutBestXIInput = {
  playerName: string
  rating: number
  positionLabel: string
  positionIndex: number
  Player?: Prisma.PlayerCreateNestedOneWithoutBestXIPlayerInput
  Team: Prisma.TeamCreateNestedOneWithoutBestXIPlayerInput
}

export type BestXIPlayerUncheckedCreateWithoutBestXIInput = {
  id?: number
  teamId: number
  playerName: string
  rating: number
  positionLabel: string
  positionIndex: number
  playerId?: number | null
}

export type BestXIPlayerCreateOrConnectWithoutBestXIInput = {
  where: Prisma.BestXIPlayerWhereUniqueInput
  create: Prisma.XOR<Prisma.BestXIPlayerCreateWithoutBestXIInput, Prisma.BestXIPlayerUncheckedCreateWithoutBestXIInput>
}

export type BestXIPlayerCreateManyBestXIInputEnvelope = {
  data: Prisma.BestXIPlayerCreateManyBestXIInput | Prisma.BestXIPlayerCreateManyBestXIInput[]
  skipDuplicates?: boolean
}

export type BestXIPlayerUpsertWithWhereUniqueWithoutBestXIInput = {
  where: Prisma.BestXIPlayerWhereUniqueInput
  update: Prisma.XOR<Prisma.BestXIPlayerUpdateWithoutBestXIInput, Prisma.BestXIPlayerUncheckedUpdateWithoutBestXIInput>
  create: Prisma.XOR<Prisma.BestXIPlayerCreateWithoutBestXIInput, Prisma.BestXIPlayerUncheckedCreateWithoutBestXIInput>
}

export type BestXIPlayerUpdateWithWhereUniqueWithoutBestXIInput = {
  where: Prisma.BestXIPlayerWhereUniqueInput
  data: Prisma.XOR<Prisma.BestXIPlayerUpdateWithoutBestXIInput, Prisma.BestXIPlayerUncheckedUpdateWithoutBestXIInput>
}

export type BestXIPlayerUpdateManyWithWhereWithoutBestXIInput = {
  where: Prisma.BestXIPlayerScalarWhereInput
  data: Prisma.XOR<Prisma.BestXIPlayerUpdateManyMutationInput, Prisma.BestXIPlayerUncheckedUpdateManyWithoutBestXIInput>
}

export type BestXIPlayerScalarWhereInput = {
  AND?: Prisma.BestXIPlayerScalarWhereInput | Prisma.BestXIPlayerScalarWhereInput[]
  OR?: Prisma.BestXIPlayerScalarWhereInput[]
  NOT?: Prisma.BestXIPlayerScalarWhereInput | Prisma.BestXIPlayerScalarWhereInput[]
  id?: Prisma.IntFilter<"BestXIPlayer"> | number
  bestXIId?: Prisma.IntFilter<"BestXIPlayer"> | number
  teamId?: Prisma.IntFilter<"BestXIPlayer"> | number
  playerName?: Prisma.StringFilter<"BestXIPlayer"> | string
  rating?: Prisma.FloatFilter<"BestXIPlayer"> | number
  positionLabel?: Prisma.StringFilter<"BestXIPlayer"> | string
  positionIndex?: Prisma.IntFilter<"BestXIPlayer"> | number
  playerId?: Prisma.IntNullableFilter<"BestXIPlayer"> | number | null
}

export type BestXIPlayerCreateWithoutPlayerInput = {
  playerName: string
  rating: number
  positionLabel: string
  positionIndex: number
  BestXI: Prisma.BestXICreateNestedOneWithoutBestXIPlayerInput
  Team: Prisma.TeamCreateNestedOneWithoutBestXIPlayerInput
}

export type BestXIPlayerUncheckedCreateWithoutPlayerInput = {
  id?: number
  bestXIId: number
  teamId: number
  playerName: string
  rating: number
  positionLabel: string
  positionIndex: number
}

export type BestXIPlayerCreateOrConnectWithoutPlayerInput = {
  where: Prisma.BestXIPlayerWhereUniqueInput
  create: Prisma.XOR<Prisma.BestXIPlayerCreateWithoutPlayerInput, Prisma.BestXIPlayerUncheckedCreateWithoutPlayerInput>
}

export type BestXIPlayerCreateManyPlayerInputEnvelope = {
  data: Prisma.BestXIPlayerCreateManyPlayerInput | Prisma.BestXIPlayerCreateManyPlayerInput[]
  skipDuplicates?: boolean
}

export type BestXIPlayerUpsertWithWhereUniqueWithoutPlayerInput = {
  where: Prisma.BestXIPlayerWhereUniqueInput
  update: Prisma.XOR<Prisma.BestXIPlayerUpdateWithoutPlayerInput, Prisma.BestXIPlayerUncheckedUpdateWithoutPlayerInput>
  create: Prisma.XOR<Prisma.BestXIPlayerCreateWithoutPlayerInput, Prisma.BestXIPlayerUncheckedCreateWithoutPlayerInput>
}

export type BestXIPlayerUpdateWithWhereUniqueWithoutPlayerInput = {
  where: Prisma.BestXIPlayerWhereUniqueInput
  data: Prisma.XOR<Prisma.BestXIPlayerUpdateWithoutPlayerInput, Prisma.BestXIPlayerUncheckedUpdateWithoutPlayerInput>
}

export type BestXIPlayerUpdateManyWithWhereWithoutPlayerInput = {
  where: Prisma.BestXIPlayerScalarWhereInput
  data: Prisma.XOR<Prisma.BestXIPlayerUpdateManyMutationInput, Prisma.BestXIPlayerUncheckedUpdateManyWithoutPlayerInput>
}

export type BestXIPlayerCreateWithoutTeamInput = {
  playerName: string
  rating: number
  positionLabel: string
  positionIndex: number
  BestXI: Prisma.BestXICreateNestedOneWithoutBestXIPlayerInput
  Player?: Prisma.PlayerCreateNestedOneWithoutBestXIPlayerInput
}

export type BestXIPlayerUncheckedCreateWithoutTeamInput = {
  id?: number
  bestXIId: number
  playerName: string
  rating: number
  positionLabel: string
  positionIndex: number
  playerId?: number | null
}

export type BestXIPlayerCreateOrConnectWithoutTeamInput = {
  where: Prisma.BestXIPlayerWhereUniqueInput
  create: Prisma.XOR<Prisma.BestXIPlayerCreateWithoutTeamInput, Prisma.BestXIPlayerUncheckedCreateWithoutTeamInput>
}

export type BestXIPlayerCreateManyTeamInputEnvelope = {
  data: Prisma.BestXIPlayerCreateManyTeamInput | Prisma.BestXIPlayerCreateManyTeamInput[]
  skipDuplicates?: boolean
}

export type BestXIPlayerUpsertWithWhereUniqueWithoutTeamInput = {
  where: Prisma.BestXIPlayerWhereUniqueInput
  update: Prisma.XOR<Prisma.BestXIPlayerUpdateWithoutTeamInput, Prisma.BestXIPlayerUncheckedUpdateWithoutTeamInput>
  create: Prisma.XOR<Prisma.BestXIPlayerCreateWithoutTeamInput, Prisma.BestXIPlayerUncheckedCreateWithoutTeamInput>
}

export type BestXIPlayerUpdateWithWhereUniqueWithoutTeamInput = {
  where: Prisma.BestXIPlayerWhereUniqueInput
  data: Prisma.XOR<Prisma.BestXIPlayerUpdateWithoutTeamInput, Prisma.BestXIPlayerUncheckedUpdateWithoutTeamInput>
}

export type BestXIPlayerUpdateManyWithWhereWithoutTeamInput = {
  where: Prisma.BestXIPlayerScalarWhereInput
  data: Prisma.XOR<Prisma.BestXIPlayerUpdateManyMutationInput, Prisma.BestXIPlayerUncheckedUpdateManyWithoutTeamInput>
}

export type BestXIPlayerCreateManyBestXIInput = {
  id?: number
  teamId: number
  playerName: string
  rating: number
  positionLabel: string
  positionIndex: number
  playerId?: number | null
}

export type BestXIPlayerUpdateWithoutBestXIInput = {
  playerName?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.FloatFieldUpdateOperationsInput | number
  positionLabel?: Prisma.StringFieldUpdateOperationsInput | string
  positionIndex?: Prisma.IntFieldUpdateOperationsInput | number
  Player?: Prisma.PlayerUpdateOneWithoutBestXIPlayerNestedInput
  Team?: Prisma.TeamUpdateOneRequiredWithoutBestXIPlayerNestedInput
}

export type BestXIPlayerUncheckedUpdateWithoutBestXIInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  teamId?: Prisma.IntFieldUpdateOperationsInput | number
  playerName?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.FloatFieldUpdateOperationsInput | number
  positionLabel?: Prisma.StringFieldUpdateOperationsInput | string
  positionIndex?: Prisma.IntFieldUpdateOperationsInput | number
  playerId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type BestXIPlayerUncheckedUpdateManyWithoutBestXIInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  teamId?: Prisma.IntFieldUpdateOperationsInput | number
  playerName?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.FloatFieldUpdateOperationsInput | number
  positionLabel?: Prisma.StringFieldUpdateOperationsInput | string
  positionIndex?: Prisma.IntFieldUpdateOperationsInput | number
  playerId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type BestXIPlayerCreateManyPlayerInput = {
  id?: number
  bestXIId: number
  teamId: number
  playerName: string
  rating: number
  positionLabel: string
  positionIndex: number
}

export type BestXIPlayerUpdateWithoutPlayerInput = {
  playerName?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.FloatFieldUpdateOperationsInput | number
  positionLabel?: Prisma.StringFieldUpdateOperationsInput | string
  positionIndex?: Prisma.IntFieldUpdateOperationsInput | number
  BestXI?: Prisma.BestXIUpdateOneRequiredWithoutBestXIPlayerNestedInput
  Team?: Prisma.TeamUpdateOneRequiredWithoutBestXIPlayerNestedInput
}

export type BestXIPlayerUncheckedUpdateWithoutPlayerInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  bestXIId?: Prisma.IntFieldUpdateOperationsInput | number
  teamId?: Prisma.IntFieldUpdateOperationsInput | number
  playerName?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.FloatFieldUpdateOperationsInput | number
  positionLabel?: Prisma.StringFieldUpdateOperationsInput | string
  positionIndex?: Prisma.IntFieldUpdateOperationsInput | number
}

export type BestXIPlayerUncheckedUpdateManyWithoutPlayerInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  bestXIId?: Prisma.IntFieldUpdateOperationsInput | number
  teamId?: Prisma.IntFieldUpdateOperationsInput | number
  playerName?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.FloatFieldUpdateOperationsInput | number
  positionLabel?: Prisma.StringFieldUpdateOperationsInput | string
  positionIndex?: Prisma.IntFieldUpdateOperationsInput | number
}

export type BestXIPlayerCreateManyTeamInput = {
  id?: number
  bestXIId: number
  playerName: string
  rating: number
  positionLabel: string
  positionIndex: number
  playerId?: number | null
}

export type BestXIPlayerUpdateWithoutTeamInput = {
  playerName?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.FloatFieldUpdateOperationsInput | number
  positionLabel?: Prisma.StringFieldUpdateOperationsInput | string
  positionIndex?: Prisma.IntFieldUpdateOperationsInput | number
  BestXI?: Prisma.BestXIUpdateOneRequiredWithoutBestXIPlayerNestedInput
  Player?: Prisma.PlayerUpdateOneWithoutBestXIPlayerNestedInput
}

export type BestXIPlayerUncheckedUpdateWithoutTeamInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  bestXIId?: Prisma.IntFieldUpdateOperationsInput | number
  playerName?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.FloatFieldUpdateOperationsInput | number
  positionLabel?: Prisma.StringFieldUpdateOperationsInput | string
  positionIndex?: Prisma.IntFieldUpdateOperationsInput | number
  playerId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type BestXIPlayerUncheckedUpdateManyWithoutTeamInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  bestXIId?: Prisma.IntFieldUpdateOperationsInput | number
  playerName?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.FloatFieldUpdateOperationsInput | number
  positionLabel?: Prisma.StringFieldUpdateOperationsInput | string
  positionIndex?: Prisma.IntFieldUpdateOperationsInput | number
  playerId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}



export type BestXIPlayerSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  bestXIId?: boolean
  teamId?: boolean
  playerName?: boolean
  rating?: boolean
  positionLabel?: boolean
  positionIndex?: boolean
  playerId?: boolean
  BestXI?: boolean | Prisma.BestXIDefaultArgs<ExtArgs>
  Player?: boolean | Prisma.BestXIPlayer$PlayerArgs<ExtArgs>
  Team?: boolean | Prisma.TeamDefaultArgs<ExtArgs>
}, ExtArgs["result"]["bestXIPlayer"]>

export type BestXIPlayerSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  bestXIId?: boolean
  teamId?: boolean
  playerName?: boolean
  rating?: boolean
  positionLabel?: boolean
  positionIndex?: boolean
  playerId?: boolean
  BestXI?: boolean | Prisma.BestXIDefaultArgs<ExtArgs>
  Player?: boolean | Prisma.BestXIPlayer$PlayerArgs<ExtArgs>
  Team?: boolean | Prisma.TeamDefaultArgs<ExtArgs>
}, ExtArgs["result"]["bestXIPlayer"]>

export type BestXIPlayerSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  bestXIId?: boolean
  teamId?: boolean
  playerName?: boolean
  rating?: boolean
  positionLabel?: boolean
  positionIndex?: boolean
  playerId?: boolean
  BestXI?: boolean | Prisma.BestXIDefaultArgs<ExtArgs>
  Player?: boolean | Prisma.BestXIPlayer$PlayerArgs<ExtArgs>
  Team?: boolean | Prisma.TeamDefaultArgs<ExtArgs>
}, ExtArgs["result"]["bestXIPlayer"]>

export type BestXIPlayerSelectScalar = {
  id?: boolean
  bestXIId?: boolean
  teamId?: boolean
  playerName?: boolean
  rating?: boolean
  positionLabel?: boolean
  positionIndex?: boolean
  playerId?: boolean
}

export type BestXIPlayerOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "bestXIId" | "teamId" | "playerName" | "rating" | "positionLabel" | "positionIndex" | "playerId", ExtArgs["result"]["bestXIPlayer"]>
export type BestXIPlayerInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  BestXI?: boolean | Prisma.BestXIDefaultArgs<ExtArgs>
  Player?: boolean | Prisma.BestXIPlayer$PlayerArgs<ExtArgs>
  Team?: boolean | Prisma.TeamDefaultArgs<ExtArgs>
}
export type BestXIPlayerIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  BestXI?: boolean | Prisma.BestXIDefaultArgs<ExtArgs>
  Player?: boolean | Prisma.BestXIPlayer$PlayerArgs<ExtArgs>
  Team?: boolean | Prisma.TeamDefaultArgs<ExtArgs>
}
export type BestXIPlayerIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  BestXI?: boolean | Prisma.BestXIDefaultArgs<ExtArgs>
  Player?: boolean | Prisma.BestXIPlayer$PlayerArgs<ExtArgs>
  Team?: boolean | Prisma.TeamDefaultArgs<ExtArgs>
}

export type $BestXIPlayerPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "BestXIPlayer"
  objects: {
    BestXI: Prisma.$BestXIPayload<ExtArgs>
    Player: Prisma.$PlayerPayload<ExtArgs> | null
    Team: Prisma.$TeamPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    bestXIId: number
    teamId: number
    playerName: string
    rating: number
    positionLabel: string
    positionIndex: number
    playerId: number | null
  }, ExtArgs["result"]["bestXIPlayer"]>
  composites: {}
}

export type BestXIPlayerGetPayload<S extends boolean | null | undefined | BestXIPlayerDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$BestXIPlayerPayload, S>

export type BestXIPlayerCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<BestXIPlayerFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: BestXIPlayerCountAggregateInputType | true
  }

export interface BestXIPlayerDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['BestXIPlayer'], meta: { name: 'BestXIPlayer' } }
  /**
   * Find zero or one BestXIPlayer that matches the filter.
   * @param {BestXIPlayerFindUniqueArgs} args - Arguments to find a BestXIPlayer
   * @example
   * // Get one BestXIPlayer
   * const bestXIPlayer = await prisma.bestXIPlayer.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends BestXIPlayerFindUniqueArgs>(args: Prisma.SelectSubset<T, BestXIPlayerFindUniqueArgs<ExtArgs>>): Prisma.Prisma__BestXIPlayerClient<runtime.Types.Result.GetResult<Prisma.$BestXIPlayerPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one BestXIPlayer that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {BestXIPlayerFindUniqueOrThrowArgs} args - Arguments to find a BestXIPlayer
   * @example
   * // Get one BestXIPlayer
   * const bestXIPlayer = await prisma.bestXIPlayer.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends BestXIPlayerFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, BestXIPlayerFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__BestXIPlayerClient<runtime.Types.Result.GetResult<Prisma.$BestXIPlayerPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BestXIPlayer that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BestXIPlayerFindFirstArgs} args - Arguments to find a BestXIPlayer
   * @example
   * // Get one BestXIPlayer
   * const bestXIPlayer = await prisma.bestXIPlayer.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends BestXIPlayerFindFirstArgs>(args?: Prisma.SelectSubset<T, BestXIPlayerFindFirstArgs<ExtArgs>>): Prisma.Prisma__BestXIPlayerClient<runtime.Types.Result.GetResult<Prisma.$BestXIPlayerPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BestXIPlayer that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BestXIPlayerFindFirstOrThrowArgs} args - Arguments to find a BestXIPlayer
   * @example
   * // Get one BestXIPlayer
   * const bestXIPlayer = await prisma.bestXIPlayer.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends BestXIPlayerFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, BestXIPlayerFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__BestXIPlayerClient<runtime.Types.Result.GetResult<Prisma.$BestXIPlayerPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more BestXIPlayers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BestXIPlayerFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all BestXIPlayers
   * const bestXIPlayers = await prisma.bestXIPlayer.findMany()
   * 
   * // Get first 10 BestXIPlayers
   * const bestXIPlayers = await prisma.bestXIPlayer.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const bestXIPlayerWithIdOnly = await prisma.bestXIPlayer.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends BestXIPlayerFindManyArgs>(args?: Prisma.SelectSubset<T, BestXIPlayerFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BestXIPlayerPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a BestXIPlayer.
   * @param {BestXIPlayerCreateArgs} args - Arguments to create a BestXIPlayer.
   * @example
   * // Create one BestXIPlayer
   * const BestXIPlayer = await prisma.bestXIPlayer.create({
   *   data: {
   *     // ... data to create a BestXIPlayer
   *   }
   * })
   * 
   */
  create<T extends BestXIPlayerCreateArgs>(args: Prisma.SelectSubset<T, BestXIPlayerCreateArgs<ExtArgs>>): Prisma.Prisma__BestXIPlayerClient<runtime.Types.Result.GetResult<Prisma.$BestXIPlayerPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many BestXIPlayers.
   * @param {BestXIPlayerCreateManyArgs} args - Arguments to create many BestXIPlayers.
   * @example
   * // Create many BestXIPlayers
   * const bestXIPlayer = await prisma.bestXIPlayer.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends BestXIPlayerCreateManyArgs>(args?: Prisma.SelectSubset<T, BestXIPlayerCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many BestXIPlayers and returns the data saved in the database.
   * @param {BestXIPlayerCreateManyAndReturnArgs} args - Arguments to create many BestXIPlayers.
   * @example
   * // Create many BestXIPlayers
   * const bestXIPlayer = await prisma.bestXIPlayer.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many BestXIPlayers and only return the `id`
   * const bestXIPlayerWithIdOnly = await prisma.bestXIPlayer.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends BestXIPlayerCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, BestXIPlayerCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BestXIPlayerPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a BestXIPlayer.
   * @param {BestXIPlayerDeleteArgs} args - Arguments to delete one BestXIPlayer.
   * @example
   * // Delete one BestXIPlayer
   * const BestXIPlayer = await prisma.bestXIPlayer.delete({
   *   where: {
   *     // ... filter to delete one BestXIPlayer
   *   }
   * })
   * 
   */
  delete<T extends BestXIPlayerDeleteArgs>(args: Prisma.SelectSubset<T, BestXIPlayerDeleteArgs<ExtArgs>>): Prisma.Prisma__BestXIPlayerClient<runtime.Types.Result.GetResult<Prisma.$BestXIPlayerPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one BestXIPlayer.
   * @param {BestXIPlayerUpdateArgs} args - Arguments to update one BestXIPlayer.
   * @example
   * // Update one BestXIPlayer
   * const bestXIPlayer = await prisma.bestXIPlayer.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends BestXIPlayerUpdateArgs>(args: Prisma.SelectSubset<T, BestXIPlayerUpdateArgs<ExtArgs>>): Prisma.Prisma__BestXIPlayerClient<runtime.Types.Result.GetResult<Prisma.$BestXIPlayerPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more BestXIPlayers.
   * @param {BestXIPlayerDeleteManyArgs} args - Arguments to filter BestXIPlayers to delete.
   * @example
   * // Delete a few BestXIPlayers
   * const { count } = await prisma.bestXIPlayer.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends BestXIPlayerDeleteManyArgs>(args?: Prisma.SelectSubset<T, BestXIPlayerDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BestXIPlayers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BestXIPlayerUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many BestXIPlayers
   * const bestXIPlayer = await prisma.bestXIPlayer.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends BestXIPlayerUpdateManyArgs>(args: Prisma.SelectSubset<T, BestXIPlayerUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BestXIPlayers and returns the data updated in the database.
   * @param {BestXIPlayerUpdateManyAndReturnArgs} args - Arguments to update many BestXIPlayers.
   * @example
   * // Update many BestXIPlayers
   * const bestXIPlayer = await prisma.bestXIPlayer.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more BestXIPlayers and only return the `id`
   * const bestXIPlayerWithIdOnly = await prisma.bestXIPlayer.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends BestXIPlayerUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, BestXIPlayerUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BestXIPlayerPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one BestXIPlayer.
   * @param {BestXIPlayerUpsertArgs} args - Arguments to update or create a BestXIPlayer.
   * @example
   * // Update or create a BestXIPlayer
   * const bestXIPlayer = await prisma.bestXIPlayer.upsert({
   *   create: {
   *     // ... data to create a BestXIPlayer
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the BestXIPlayer we want to update
   *   }
   * })
   */
  upsert<T extends BestXIPlayerUpsertArgs>(args: Prisma.SelectSubset<T, BestXIPlayerUpsertArgs<ExtArgs>>): Prisma.Prisma__BestXIPlayerClient<runtime.Types.Result.GetResult<Prisma.$BestXIPlayerPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of BestXIPlayers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BestXIPlayerCountArgs} args - Arguments to filter BestXIPlayers to count.
   * @example
   * // Count the number of BestXIPlayers
   * const count = await prisma.bestXIPlayer.count({
   *   where: {
   *     // ... the filter for the BestXIPlayers we want to count
   *   }
   * })
  **/
  count<T extends BestXIPlayerCountArgs>(
    args?: Prisma.Subset<T, BestXIPlayerCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], BestXIPlayerCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a BestXIPlayer.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BestXIPlayerAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends BestXIPlayerAggregateArgs>(args: Prisma.Subset<T, BestXIPlayerAggregateArgs>): Prisma.PrismaPromise<GetBestXIPlayerAggregateType<T>>

  /**
   * Group by BestXIPlayer.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BestXIPlayerGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends BestXIPlayerGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: BestXIPlayerGroupByArgs['orderBy'] }
      : { orderBy?: BestXIPlayerGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, BestXIPlayerGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetBestXIPlayerGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the BestXIPlayer model
 */
readonly fields: BestXIPlayerFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for BestXIPlayer.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__BestXIPlayerClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  BestXI<T extends Prisma.BestXIDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.BestXIDefaultArgs<ExtArgs>>): Prisma.Prisma__BestXIClient<runtime.Types.Result.GetResult<Prisma.$BestXIPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  Player<T extends Prisma.BestXIPlayer$PlayerArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.BestXIPlayer$PlayerArgs<ExtArgs>>): Prisma.Prisma__PlayerClient<runtime.Types.Result.GetResult<Prisma.$PlayerPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  Team<T extends Prisma.TeamDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TeamDefaultArgs<ExtArgs>>): Prisma.Prisma__TeamClient<runtime.Types.Result.GetResult<Prisma.$TeamPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the BestXIPlayer model
 */
export interface BestXIPlayerFieldRefs {
  readonly id: Prisma.FieldRef<"BestXIPlayer", 'Int'>
  readonly bestXIId: Prisma.FieldRef<"BestXIPlayer", 'Int'>
  readonly teamId: Prisma.FieldRef<"BestXIPlayer", 'Int'>
  readonly playerName: Prisma.FieldRef<"BestXIPlayer", 'String'>
  readonly rating: Prisma.FieldRef<"BestXIPlayer", 'Float'>
  readonly positionLabel: Prisma.FieldRef<"BestXIPlayer", 'String'>
  readonly positionIndex: Prisma.FieldRef<"BestXIPlayer", 'Int'>
  readonly playerId: Prisma.FieldRef<"BestXIPlayer", 'Int'>
}
    

// Custom InputTypes
/**
 * BestXIPlayer findUnique
 */
export type BestXIPlayerFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BestXIPlayer
   */
  select?: Prisma.BestXIPlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BestXIPlayer
   */
  omit?: Prisma.BestXIPlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestXIPlayerInclude<ExtArgs> | null
  /**
   * Filter, which BestXIPlayer to fetch.
   */
  where: Prisma.BestXIPlayerWhereUniqueInput
}

/**
 * BestXIPlayer findUniqueOrThrow
 */
export type BestXIPlayerFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BestXIPlayer
   */
  select?: Prisma.BestXIPlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BestXIPlayer
   */
  omit?: Prisma.BestXIPlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestXIPlayerInclude<ExtArgs> | null
  /**
   * Filter, which BestXIPlayer to fetch.
   */
  where: Prisma.BestXIPlayerWhereUniqueInput
}

/**
 * BestXIPlayer findFirst
 */
export type BestXIPlayerFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BestXIPlayer
   */
  select?: Prisma.BestXIPlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BestXIPlayer
   */
  omit?: Prisma.BestXIPlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestXIPlayerInclude<ExtArgs> | null
  /**
   * Filter, which BestXIPlayer to fetch.
   */
  where?: Prisma.BestXIPlayerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BestXIPlayers to fetch.
   */
  orderBy?: Prisma.BestXIPlayerOrderByWithRelationInput | Prisma.BestXIPlayerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BestXIPlayers.
   */
  cursor?: Prisma.BestXIPlayerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BestXIPlayers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BestXIPlayers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BestXIPlayers.
   */
  distinct?: Prisma.BestXIPlayerScalarFieldEnum | Prisma.BestXIPlayerScalarFieldEnum[]
}

/**
 * BestXIPlayer findFirstOrThrow
 */
export type BestXIPlayerFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BestXIPlayer
   */
  select?: Prisma.BestXIPlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BestXIPlayer
   */
  omit?: Prisma.BestXIPlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestXIPlayerInclude<ExtArgs> | null
  /**
   * Filter, which BestXIPlayer to fetch.
   */
  where?: Prisma.BestXIPlayerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BestXIPlayers to fetch.
   */
  orderBy?: Prisma.BestXIPlayerOrderByWithRelationInput | Prisma.BestXIPlayerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BestXIPlayers.
   */
  cursor?: Prisma.BestXIPlayerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BestXIPlayers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BestXIPlayers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BestXIPlayers.
   */
  distinct?: Prisma.BestXIPlayerScalarFieldEnum | Prisma.BestXIPlayerScalarFieldEnum[]
}

/**
 * BestXIPlayer findMany
 */
export type BestXIPlayerFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BestXIPlayer
   */
  select?: Prisma.BestXIPlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BestXIPlayer
   */
  omit?: Prisma.BestXIPlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestXIPlayerInclude<ExtArgs> | null
  /**
   * Filter, which BestXIPlayers to fetch.
   */
  where?: Prisma.BestXIPlayerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BestXIPlayers to fetch.
   */
  orderBy?: Prisma.BestXIPlayerOrderByWithRelationInput | Prisma.BestXIPlayerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing BestXIPlayers.
   */
  cursor?: Prisma.BestXIPlayerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BestXIPlayers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BestXIPlayers.
   */
  skip?: number
  distinct?: Prisma.BestXIPlayerScalarFieldEnum | Prisma.BestXIPlayerScalarFieldEnum[]
}

/**
 * BestXIPlayer create
 */
export type BestXIPlayerCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BestXIPlayer
   */
  select?: Prisma.BestXIPlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BestXIPlayer
   */
  omit?: Prisma.BestXIPlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestXIPlayerInclude<ExtArgs> | null
  /**
   * The data needed to create a BestXIPlayer.
   */
  data: Prisma.XOR<Prisma.BestXIPlayerCreateInput, Prisma.BestXIPlayerUncheckedCreateInput>
}

/**
 * BestXIPlayer createMany
 */
export type BestXIPlayerCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many BestXIPlayers.
   */
  data: Prisma.BestXIPlayerCreateManyInput | Prisma.BestXIPlayerCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * BestXIPlayer createManyAndReturn
 */
export type BestXIPlayerCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BestXIPlayer
   */
  select?: Prisma.BestXIPlayerSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BestXIPlayer
   */
  omit?: Prisma.BestXIPlayerOmit<ExtArgs> | null
  /**
   * The data used to create many BestXIPlayers.
   */
  data: Prisma.BestXIPlayerCreateManyInput | Prisma.BestXIPlayerCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestXIPlayerIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * BestXIPlayer update
 */
export type BestXIPlayerUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BestXIPlayer
   */
  select?: Prisma.BestXIPlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BestXIPlayer
   */
  omit?: Prisma.BestXIPlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestXIPlayerInclude<ExtArgs> | null
  /**
   * The data needed to update a BestXIPlayer.
   */
  data: Prisma.XOR<Prisma.BestXIPlayerUpdateInput, Prisma.BestXIPlayerUncheckedUpdateInput>
  /**
   * Choose, which BestXIPlayer to update.
   */
  where: Prisma.BestXIPlayerWhereUniqueInput
}

/**
 * BestXIPlayer updateMany
 */
export type BestXIPlayerUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update BestXIPlayers.
   */
  data: Prisma.XOR<Prisma.BestXIPlayerUpdateManyMutationInput, Prisma.BestXIPlayerUncheckedUpdateManyInput>
  /**
   * Filter which BestXIPlayers to update
   */
  where?: Prisma.BestXIPlayerWhereInput
  /**
   * Limit how many BestXIPlayers to update.
   */
  limit?: number
}

/**
 * BestXIPlayer updateManyAndReturn
 */
export type BestXIPlayerUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BestXIPlayer
   */
  select?: Prisma.BestXIPlayerSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BestXIPlayer
   */
  omit?: Prisma.BestXIPlayerOmit<ExtArgs> | null
  /**
   * The data used to update BestXIPlayers.
   */
  data: Prisma.XOR<Prisma.BestXIPlayerUpdateManyMutationInput, Prisma.BestXIPlayerUncheckedUpdateManyInput>
  /**
   * Filter which BestXIPlayers to update
   */
  where?: Prisma.BestXIPlayerWhereInput
  /**
   * Limit how many BestXIPlayers to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestXIPlayerIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * BestXIPlayer upsert
 */
export type BestXIPlayerUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BestXIPlayer
   */
  select?: Prisma.BestXIPlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BestXIPlayer
   */
  omit?: Prisma.BestXIPlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestXIPlayerInclude<ExtArgs> | null
  /**
   * The filter to search for the BestXIPlayer to update in case it exists.
   */
  where: Prisma.BestXIPlayerWhereUniqueInput
  /**
   * In case the BestXIPlayer found by the `where` argument doesn't exist, create a new BestXIPlayer with this data.
   */
  create: Prisma.XOR<Prisma.BestXIPlayerCreateInput, Prisma.BestXIPlayerUncheckedCreateInput>
  /**
   * In case the BestXIPlayer was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.BestXIPlayerUpdateInput, Prisma.BestXIPlayerUncheckedUpdateInput>
}

/**
 * BestXIPlayer delete
 */
export type BestXIPlayerDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BestXIPlayer
   */
  select?: Prisma.BestXIPlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BestXIPlayer
   */
  omit?: Prisma.BestXIPlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestXIPlayerInclude<ExtArgs> | null
  /**
   * Filter which BestXIPlayer to delete.
   */
  where: Prisma.BestXIPlayerWhereUniqueInput
}

/**
 * BestXIPlayer deleteMany
 */
export type BestXIPlayerDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BestXIPlayers to delete
   */
  where?: Prisma.BestXIPlayerWhereInput
  /**
   * Limit how many BestXIPlayers to delete.
   */
  limit?: number
}

/**
 * BestXIPlayer.Player
 */
export type BestXIPlayer$PlayerArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Player
   */
  select?: Prisma.PlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Player
   */
  omit?: Prisma.PlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlayerInclude<ExtArgs> | null
  where?: Prisma.PlayerWhereInput
}

/**
 * BestXIPlayer without action
 */
export type BestXIPlayerDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BestXIPlayer
   */
  select?: Prisma.BestXIPlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BestXIPlayer
   */
  omit?: Prisma.BestXIPlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestXIPlayerInclude<ExtArgs> | null
}
