
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TeamPerformanceStat` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model TeamPerformanceStat
 * 
 */
export type TeamPerformanceStatModel = runtime.Types.Result.DefaultSelection<Prisma.$TeamPerformanceStatPayload>

export type AggregateTeamPerformanceStat = {
  _count: TeamPerformanceStatCountAggregateOutputType | null
  _avg: TeamPerformanceStatAvgAggregateOutputType | null
  _sum: TeamPerformanceStatSumAggregateOutputType | null
  _min: TeamPerformanceStatMinAggregateOutputType | null
  _max: TeamPerformanceStatMaxAggregateOutputType | null
}

export type TeamPerformanceStatAvgAggregateOutputType = {
  id: number | null
  tournamentId: number | null
  teamId: number | null
  rank: number | null
  matchesPlayed: number | null
  winPercentage: number | null
  drawPercentage: number | null
  lossPercentage: number | null
  goalsForPg: number | null
  goalsAgainstPg: number | null
  pointsPg: number | null
  viewTypeId: number | null
}

export type TeamPerformanceStatSumAggregateOutputType = {
  id: number | null
  tournamentId: number | null
  teamId: number | null
  rank: number | null
  matchesPlayed: number | null
  winPercentage: number | null
  drawPercentage: number | null
  lossPercentage: number | null
  goalsForPg: number | null
  goalsAgainstPg: number | null
  pointsPg: number | null
  viewTypeId: number | null
}

export type TeamPerformanceStatMinAggregateOutputType = {
  id: number | null
  tournamentId: number | null
  teamId: number | null
  category: string | null
  rank: number | null
  matchesPlayed: number | null
  winPercentage: number | null
  drawPercentage: number | null
  lossPercentage: number | null
  goalsForPg: number | null
  goalsAgainstPg: number | null
  pointsPg: number | null
  createdAt: Date | null
  updatedAt: Date | null
  mode: string | null
  viewTypeId: number | null
}

export type TeamPerformanceStatMaxAggregateOutputType = {
  id: number | null
  tournamentId: number | null
  teamId: number | null
  category: string | null
  rank: number | null
  matchesPlayed: number | null
  winPercentage: number | null
  drawPercentage: number | null
  lossPercentage: number | null
  goalsForPg: number | null
  goalsAgainstPg: number | null
  pointsPg: number | null
  createdAt: Date | null
  updatedAt: Date | null
  mode: string | null
  viewTypeId: number | null
}

export type TeamPerformanceStatCountAggregateOutputType = {
  id: number
  tournamentId: number
  teamId: number
  category: number
  rank: number
  matchesPlayed: number
  winPercentage: number
  drawPercentage: number
  lossPercentage: number
  goalsForPg: number
  goalsAgainstPg: number
  pointsPg: number
  createdAt: number
  updatedAt: number
  mode: number
  viewTypeId: number
  _all: number
}


export type TeamPerformanceStatAvgAggregateInputType = {
  id?: true
  tournamentId?: true
  teamId?: true
  rank?: true
  matchesPlayed?: true
  winPercentage?: true
  drawPercentage?: true
  lossPercentage?: true
  goalsForPg?: true
  goalsAgainstPg?: true
  pointsPg?: true
  viewTypeId?: true
}

export type TeamPerformanceStatSumAggregateInputType = {
  id?: true
  tournamentId?: true
  teamId?: true
  rank?: true
  matchesPlayed?: true
  winPercentage?: true
  drawPercentage?: true
  lossPercentage?: true
  goalsForPg?: true
  goalsAgainstPg?: true
  pointsPg?: true
  viewTypeId?: true
}

export type TeamPerformanceStatMinAggregateInputType = {
  id?: true
  tournamentId?: true
  teamId?: true
  category?: true
  rank?: true
  matchesPlayed?: true
  winPercentage?: true
  drawPercentage?: true
  lossPercentage?: true
  goalsForPg?: true
  goalsAgainstPg?: true
  pointsPg?: true
  createdAt?: true
  updatedAt?: true
  mode?: true
  viewTypeId?: true
}

export type TeamPerformanceStatMaxAggregateInputType = {
  id?: true
  tournamentId?: true
  teamId?: true
  category?: true
  rank?: true
  matchesPlayed?: true
  winPercentage?: true
  drawPercentage?: true
  lossPercentage?: true
  goalsForPg?: true
  goalsAgainstPg?: true
  pointsPg?: true
  createdAt?: true
  updatedAt?: true
  mode?: true
  viewTypeId?: true
}

export type TeamPerformanceStatCountAggregateInputType = {
  id?: true
  tournamentId?: true
  teamId?: true
  category?: true
  rank?: true
  matchesPlayed?: true
  winPercentage?: true
  drawPercentage?: true
  lossPercentage?: true
  goalsForPg?: true
  goalsAgainstPg?: true
  pointsPg?: true
  createdAt?: true
  updatedAt?: true
  mode?: true
  viewTypeId?: true
  _all?: true
}

export type TeamPerformanceStatAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TeamPerformanceStat to aggregate.
   */
  where?: Prisma.TeamPerformanceStatWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TeamPerformanceStats to fetch.
   */
  orderBy?: Prisma.TeamPerformanceStatOrderByWithRelationInput | Prisma.TeamPerformanceStatOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TeamPerformanceStatWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TeamPerformanceStats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TeamPerformanceStats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TeamPerformanceStats
  **/
  _count?: true | TeamPerformanceStatCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TeamPerformanceStatAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TeamPerformanceStatSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TeamPerformanceStatMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TeamPerformanceStatMaxAggregateInputType
}

export type GetTeamPerformanceStatAggregateType<T extends TeamPerformanceStatAggregateArgs> = {
      [P in keyof T & keyof AggregateTeamPerformanceStat]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTeamPerformanceStat[P]>
    : Prisma.GetScalarType<T[P], AggregateTeamPerformanceStat[P]>
}




export type TeamPerformanceStatGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TeamPerformanceStatWhereInput
  orderBy?: Prisma.TeamPerformanceStatOrderByWithAggregationInput | Prisma.TeamPerformanceStatOrderByWithAggregationInput[]
  by: Prisma.TeamPerformanceStatScalarFieldEnum[] | Prisma.TeamPerformanceStatScalarFieldEnum
  having?: Prisma.TeamPerformanceStatScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TeamPerformanceStatCountAggregateInputType | true
  _avg?: TeamPerformanceStatAvgAggregateInputType
  _sum?: TeamPerformanceStatSumAggregateInputType
  _min?: TeamPerformanceStatMinAggregateInputType
  _max?: TeamPerformanceStatMaxAggregateInputType
}

export type TeamPerformanceStatGroupByOutputType = {
  id: number
  tournamentId: number
  teamId: number
  category: string
  rank: number
  matchesPlayed: number
  winPercentage: number
  drawPercentage: number
  lossPercentage: number
  goalsForPg: number
  goalsAgainstPg: number
  pointsPg: number
  createdAt: Date
  updatedAt: Date
  mode: string
  viewTypeId: number
  _count: TeamPerformanceStatCountAggregateOutputType | null
  _avg: TeamPerformanceStatAvgAggregateOutputType | null
  _sum: TeamPerformanceStatSumAggregateOutputType | null
  _min: TeamPerformanceStatMinAggregateOutputType | null
  _max: TeamPerformanceStatMaxAggregateOutputType | null
}

type GetTeamPerformanceStatGroupByPayload<T extends TeamPerformanceStatGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TeamPerformanceStatGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TeamPerformanceStatGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TeamPerformanceStatGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TeamPerformanceStatGroupByOutputType[P]>
      }
    >
  >



export type TeamPerformanceStatWhereInput = {
  AND?: Prisma.TeamPerformanceStatWhereInput | Prisma.TeamPerformanceStatWhereInput[]
  OR?: Prisma.TeamPerformanceStatWhereInput[]
  NOT?: Prisma.TeamPerformanceStatWhereInput | Prisma.TeamPerformanceStatWhereInput[]
  id?: Prisma.IntFilter<"TeamPerformanceStat"> | number
  tournamentId?: Prisma.IntFilter<"TeamPerformanceStat"> | number
  teamId?: Prisma.IntFilter<"TeamPerformanceStat"> | number
  category?: Prisma.StringFilter<"TeamPerformanceStat"> | string
  rank?: Prisma.IntFilter<"TeamPerformanceStat"> | number
  matchesPlayed?: Prisma.IntFilter<"TeamPerformanceStat"> | number
  winPercentage?: Prisma.IntFilter<"TeamPerformanceStat"> | number
  drawPercentage?: Prisma.IntFilter<"TeamPerformanceStat"> | number
  lossPercentage?: Prisma.IntFilter<"TeamPerformanceStat"> | number
  goalsForPg?: Prisma.FloatFilter<"TeamPerformanceStat"> | number
  goalsAgainstPg?: Prisma.FloatFilter<"TeamPerformanceStat"> | number
  pointsPg?: Prisma.FloatFilter<"TeamPerformanceStat"> | number
  createdAt?: Prisma.DateTimeFilter<"TeamPerformanceStat"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TeamPerformanceStat"> | Date | string
  mode?: Prisma.StringFilter<"TeamPerformanceStat"> | string
  viewTypeId?: Prisma.IntFilter<"TeamPerformanceStat"> | number
  Team?: Prisma.XOR<Prisma.TeamScalarRelationFilter, Prisma.TeamWhereInput>
  Tournament?: Prisma.XOR<Prisma.TournamentScalarRelationFilter, Prisma.TournamentWhereInput>
  TableType?: Prisma.XOR<Prisma.TableTypeScalarRelationFilter, Prisma.TableTypeWhereInput>
}

export type TeamPerformanceStatOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  tournamentId?: Prisma.SortOrder
  teamId?: Prisma.SortOrder
  category?: Prisma.SortOrder
  rank?: Prisma.SortOrder
  matchesPlayed?: Prisma.SortOrder
  winPercentage?: Prisma.SortOrder
  drawPercentage?: Prisma.SortOrder
  lossPercentage?: Prisma.SortOrder
  goalsForPg?: Prisma.SortOrder
  goalsAgainstPg?: Prisma.SortOrder
  pointsPg?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  mode?: Prisma.SortOrder
  viewTypeId?: Prisma.SortOrder
  Team?: Prisma.TeamOrderByWithRelationInput
  Tournament?: Prisma.TournamentOrderByWithRelationInput
  TableType?: Prisma.TableTypeOrderByWithRelationInput
}

export type TeamPerformanceStatWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  tournamentId_teamId_category_mode_viewTypeId?: Prisma.TeamPerformanceStatTournamentIdTeamIdCategoryModeViewTypeIdCompoundUniqueInput
  AND?: Prisma.TeamPerformanceStatWhereInput | Prisma.TeamPerformanceStatWhereInput[]
  OR?: Prisma.TeamPerformanceStatWhereInput[]
  NOT?: Prisma.TeamPerformanceStatWhereInput | Prisma.TeamPerformanceStatWhereInput[]
  tournamentId?: Prisma.IntFilter<"TeamPerformanceStat"> | number
  teamId?: Prisma.IntFilter<"TeamPerformanceStat"> | number
  category?: Prisma.StringFilter<"TeamPerformanceStat"> | string
  rank?: Prisma.IntFilter<"TeamPerformanceStat"> | number
  matchesPlayed?: Prisma.IntFilter<"TeamPerformanceStat"> | number
  winPercentage?: Prisma.IntFilter<"TeamPerformanceStat"> | number
  drawPercentage?: Prisma.IntFilter<"TeamPerformanceStat"> | number
  lossPercentage?: Prisma.IntFilter<"TeamPerformanceStat"> | number
  goalsForPg?: Prisma.FloatFilter<"TeamPerformanceStat"> | number
  goalsAgainstPg?: Prisma.FloatFilter<"TeamPerformanceStat"> | number
  pointsPg?: Prisma.FloatFilter<"TeamPerformanceStat"> | number
  createdAt?: Prisma.DateTimeFilter<"TeamPerformanceStat"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TeamPerformanceStat"> | Date | string
  mode?: Prisma.StringFilter<"TeamPerformanceStat"> | string
  viewTypeId?: Prisma.IntFilter<"TeamPerformanceStat"> | number
  Team?: Prisma.XOR<Prisma.TeamScalarRelationFilter, Prisma.TeamWhereInput>
  Tournament?: Prisma.XOR<Prisma.TournamentScalarRelationFilter, Prisma.TournamentWhereInput>
  TableType?: Prisma.XOR<Prisma.TableTypeScalarRelationFilter, Prisma.TableTypeWhereInput>
}, "id" | "tournamentId_teamId_category_mode_viewTypeId">

export type TeamPerformanceStatOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  tournamentId?: Prisma.SortOrder
  teamId?: Prisma.SortOrder
  category?: Prisma.SortOrder
  rank?: Prisma.SortOrder
  matchesPlayed?: Prisma.SortOrder
  winPercentage?: Prisma.SortOrder
  drawPercentage?: Prisma.SortOrder
  lossPercentage?: Prisma.SortOrder
  goalsForPg?: Prisma.SortOrder
  goalsAgainstPg?: Prisma.SortOrder
  pointsPg?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  mode?: Prisma.SortOrder
  viewTypeId?: Prisma.SortOrder
  _count?: Prisma.TeamPerformanceStatCountOrderByAggregateInput
  _avg?: Prisma.TeamPerformanceStatAvgOrderByAggregateInput
  _max?: Prisma.TeamPerformanceStatMaxOrderByAggregateInput
  _min?: Prisma.TeamPerformanceStatMinOrderByAggregateInput
  _sum?: Prisma.TeamPerformanceStatSumOrderByAggregateInput
}

export type TeamPerformanceStatScalarWhereWithAggregatesInput = {
  AND?: Prisma.TeamPerformanceStatScalarWhereWithAggregatesInput | Prisma.TeamPerformanceStatScalarWhereWithAggregatesInput[]
  OR?: Prisma.TeamPerformanceStatScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TeamPerformanceStatScalarWhereWithAggregatesInput | Prisma.TeamPerformanceStatScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"TeamPerformanceStat"> | number
  tournamentId?: Prisma.IntWithAggregatesFilter<"TeamPerformanceStat"> | number
  teamId?: Prisma.IntWithAggregatesFilter<"TeamPerformanceStat"> | number
  category?: Prisma.StringWithAggregatesFilter<"TeamPerformanceStat"> | string
  rank?: Prisma.IntWithAggregatesFilter<"TeamPerformanceStat"> | number
  matchesPlayed?: Prisma.IntWithAggregatesFilter<"TeamPerformanceStat"> | number
  winPercentage?: Prisma.IntWithAggregatesFilter<"TeamPerformanceStat"> | number
  drawPercentage?: Prisma.IntWithAggregatesFilter<"TeamPerformanceStat"> | number
  lossPercentage?: Prisma.IntWithAggregatesFilter<"TeamPerformanceStat"> | number
  goalsForPg?: Prisma.FloatWithAggregatesFilter<"TeamPerformanceStat"> | number
  goalsAgainstPg?: Prisma.FloatWithAggregatesFilter<"TeamPerformanceStat"> | number
  pointsPg?: Prisma.FloatWithAggregatesFilter<"TeamPerformanceStat"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"TeamPerformanceStat"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"TeamPerformanceStat"> | Date | string
  mode?: Prisma.StringWithAggregatesFilter<"TeamPerformanceStat"> | string
  viewTypeId?: Prisma.IntWithAggregatesFilter<"TeamPerformanceStat"> | number
}

export type TeamPerformanceStatCreateInput = {
  category: string
  rank: number
  matchesPlayed: number
  winPercentage: number
  drawPercentage: number
  lossPercentage: number
  goalsForPg: number
  goalsAgainstPg: number
  pointsPg: number
  createdAt?: Date | string
  updatedAt: Date | string
  mode?: string
  Team: Prisma.TeamCreateNestedOneWithoutTeamPerformanceStatInput
  Tournament: Prisma.TournamentCreateNestedOneWithoutTeamPerformanceStatInput
  TableType: Prisma.TableTypeCreateNestedOneWithoutTeamPerformanceStatInput
}

export type TeamPerformanceStatUncheckedCreateInput = {
  id?: number
  tournamentId: number
  teamId: number
  category: string
  rank: number
  matchesPlayed: number
  winPercentage: number
  drawPercentage: number
  lossPercentage: number
  goalsForPg: number
  goalsAgainstPg: number
  pointsPg: number
  createdAt?: Date | string
  updatedAt: Date | string
  mode?: string
  viewTypeId: number
}

export type TeamPerformanceStatUpdateInput = {
  category?: Prisma.StringFieldUpdateOperationsInput | string
  rank?: Prisma.IntFieldUpdateOperationsInput | number
  matchesPlayed?: Prisma.IntFieldUpdateOperationsInput | number
  winPercentage?: Prisma.IntFieldUpdateOperationsInput | number
  drawPercentage?: Prisma.IntFieldUpdateOperationsInput | number
  lossPercentage?: Prisma.IntFieldUpdateOperationsInput | number
  goalsForPg?: Prisma.FloatFieldUpdateOperationsInput | number
  goalsAgainstPg?: Prisma.FloatFieldUpdateOperationsInput | number
  pointsPg?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mode?: Prisma.StringFieldUpdateOperationsInput | string
  Team?: Prisma.TeamUpdateOneRequiredWithoutTeamPerformanceStatNestedInput
  Tournament?: Prisma.TournamentUpdateOneRequiredWithoutTeamPerformanceStatNestedInput
  TableType?: Prisma.TableTypeUpdateOneRequiredWithoutTeamPerformanceStatNestedInput
}

export type TeamPerformanceStatUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  tournamentId?: Prisma.IntFieldUpdateOperationsInput | number
  teamId?: Prisma.IntFieldUpdateOperationsInput | number
  category?: Prisma.StringFieldUpdateOperationsInput | string
  rank?: Prisma.IntFieldUpdateOperationsInput | number
  matchesPlayed?: Prisma.IntFieldUpdateOperationsInput | number
  winPercentage?: Prisma.IntFieldUpdateOperationsInput | number
  drawPercentage?: Prisma.IntFieldUpdateOperationsInput | number
  lossPercentage?: Prisma.IntFieldUpdateOperationsInput | number
  goalsForPg?: Prisma.FloatFieldUpdateOperationsInput | number
  goalsAgainstPg?: Prisma.FloatFieldUpdateOperationsInput | number
  pointsPg?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mode?: Prisma.StringFieldUpdateOperationsInput | string
  viewTypeId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type TeamPerformanceStatCreateManyInput = {
  id?: number
  tournamentId: number
  teamId: number
  category: string
  rank: number
  matchesPlayed: number
  winPercentage: number
  drawPercentage: number
  lossPercentage: number
  goalsForPg: number
  goalsAgainstPg: number
  pointsPg: number
  createdAt?: Date | string
  updatedAt: Date | string
  mode?: string
  viewTypeId: number
}

export type TeamPerformanceStatUpdateManyMutationInput = {
  category?: Prisma.StringFieldUpdateOperationsInput | string
  rank?: Prisma.IntFieldUpdateOperationsInput | number
  matchesPlayed?: Prisma.IntFieldUpdateOperationsInput | number
  winPercentage?: Prisma.IntFieldUpdateOperationsInput | number
  drawPercentage?: Prisma.IntFieldUpdateOperationsInput | number
  lossPercentage?: Prisma.IntFieldUpdateOperationsInput | number
  goalsForPg?: Prisma.FloatFieldUpdateOperationsInput | number
  goalsAgainstPg?: Prisma.FloatFieldUpdateOperationsInput | number
  pointsPg?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mode?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TeamPerformanceStatUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  tournamentId?: Prisma.IntFieldUpdateOperationsInput | number
  teamId?: Prisma.IntFieldUpdateOperationsInput | number
  category?: Prisma.StringFieldUpdateOperationsInput | string
  rank?: Prisma.IntFieldUpdateOperationsInput | number
  matchesPlayed?: Prisma.IntFieldUpdateOperationsInput | number
  winPercentage?: Prisma.IntFieldUpdateOperationsInput | number
  drawPercentage?: Prisma.IntFieldUpdateOperationsInput | number
  lossPercentage?: Prisma.IntFieldUpdateOperationsInput | number
  goalsForPg?: Prisma.FloatFieldUpdateOperationsInput | number
  goalsAgainstPg?: Prisma.FloatFieldUpdateOperationsInput | number
  pointsPg?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mode?: Prisma.StringFieldUpdateOperationsInput | string
  viewTypeId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type TeamPerformanceStatListRelationFilter = {
  every?: Prisma.TeamPerformanceStatWhereInput
  some?: Prisma.TeamPerformanceStatWhereInput
  none?: Prisma.TeamPerformanceStatWhereInput
}

export type TeamPerformanceStatOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TeamPerformanceStatTournamentIdTeamIdCategoryModeViewTypeIdCompoundUniqueInput = {
  tournamentId: number
  teamId: number
  category: string
  mode: string
  viewTypeId: number
}

export type TeamPerformanceStatCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tournamentId?: Prisma.SortOrder
  teamId?: Prisma.SortOrder
  category?: Prisma.SortOrder
  rank?: Prisma.SortOrder
  matchesPlayed?: Prisma.SortOrder
  winPercentage?: Prisma.SortOrder
  drawPercentage?: Prisma.SortOrder
  lossPercentage?: Prisma.SortOrder
  goalsForPg?: Prisma.SortOrder
  goalsAgainstPg?: Prisma.SortOrder
  pointsPg?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  mode?: Prisma.SortOrder
  viewTypeId?: Prisma.SortOrder
}

export type TeamPerformanceStatAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tournamentId?: Prisma.SortOrder
  teamId?: Prisma.SortOrder
  rank?: Prisma.SortOrder
  matchesPlayed?: Prisma.SortOrder
  winPercentage?: Prisma.SortOrder
  drawPercentage?: Prisma.SortOrder
  lossPercentage?: Prisma.SortOrder
  goalsForPg?: Prisma.SortOrder
  goalsAgainstPg?: Prisma.SortOrder
  pointsPg?: Prisma.SortOrder
  viewTypeId?: Prisma.SortOrder
}

export type TeamPerformanceStatMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tournamentId?: Prisma.SortOrder
  teamId?: Prisma.SortOrder
  category?: Prisma.SortOrder
  rank?: Prisma.SortOrder
  matchesPlayed?: Prisma.SortOrder
  winPercentage?: Prisma.SortOrder
  drawPercentage?: Prisma.SortOrder
  lossPercentage?: Prisma.SortOrder
  goalsForPg?: Prisma.SortOrder
  goalsAgainstPg?: Prisma.SortOrder
  pointsPg?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  mode?: Prisma.SortOrder
  viewTypeId?: Prisma.SortOrder
}

export type TeamPerformanceStatMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tournamentId?: Prisma.SortOrder
  teamId?: Prisma.SortOrder
  category?: Prisma.SortOrder
  rank?: Prisma.SortOrder
  matchesPlayed?: Prisma.SortOrder
  winPercentage?: Prisma.SortOrder
  drawPercentage?: Prisma.SortOrder
  lossPercentage?: Prisma.SortOrder
  goalsForPg?: Prisma.SortOrder
  goalsAgainstPg?: Prisma.SortOrder
  pointsPg?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  mode?: Prisma.SortOrder
  viewTypeId?: Prisma.SortOrder
}

export type TeamPerformanceStatSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tournamentId?: Prisma.SortOrder
  teamId?: Prisma.SortOrder
  rank?: Prisma.SortOrder
  matchesPlayed?: Prisma.SortOrder
  winPercentage?: Prisma.SortOrder
  drawPercentage?: Prisma.SortOrder
  lossPercentage?: Prisma.SortOrder
  goalsForPg?: Prisma.SortOrder
  goalsAgainstPg?: Prisma.SortOrder
  pointsPg?: Prisma.SortOrder
  viewTypeId?: Prisma.SortOrder
}

export type TeamPerformanceStatCreateNestedManyWithoutTableTypeInput = {
  create?: Prisma.XOR<Prisma.TeamPerformanceStatCreateWithoutTableTypeInput, Prisma.TeamPerformanceStatUncheckedCreateWithoutTableTypeInput> | Prisma.TeamPerformanceStatCreateWithoutTableTypeInput[] | Prisma.TeamPerformanceStatUncheckedCreateWithoutTableTypeInput[]
  connectOrCreate?: Prisma.TeamPerformanceStatCreateOrConnectWithoutTableTypeInput | Prisma.TeamPerformanceStatCreateOrConnectWithoutTableTypeInput[]
  createMany?: Prisma.TeamPerformanceStatCreateManyTableTypeInputEnvelope
  connect?: Prisma.TeamPerformanceStatWhereUniqueInput | Prisma.TeamPerformanceStatWhereUniqueInput[]
}

export type TeamPerformanceStatUncheckedCreateNestedManyWithoutTableTypeInput = {
  create?: Prisma.XOR<Prisma.TeamPerformanceStatCreateWithoutTableTypeInput, Prisma.TeamPerformanceStatUncheckedCreateWithoutTableTypeInput> | Prisma.TeamPerformanceStatCreateWithoutTableTypeInput[] | Prisma.TeamPerformanceStatUncheckedCreateWithoutTableTypeInput[]
  connectOrCreate?: Prisma.TeamPerformanceStatCreateOrConnectWithoutTableTypeInput | Prisma.TeamPerformanceStatCreateOrConnectWithoutTableTypeInput[]
  createMany?: Prisma.TeamPerformanceStatCreateManyTableTypeInputEnvelope
  connect?: Prisma.TeamPerformanceStatWhereUniqueInput | Prisma.TeamPerformanceStatWhereUniqueInput[]
}

export type TeamPerformanceStatUpdateManyWithoutTableTypeNestedInput = {
  create?: Prisma.XOR<Prisma.TeamPerformanceStatCreateWithoutTableTypeInput, Prisma.TeamPerformanceStatUncheckedCreateWithoutTableTypeInput> | Prisma.TeamPerformanceStatCreateWithoutTableTypeInput[] | Prisma.TeamPerformanceStatUncheckedCreateWithoutTableTypeInput[]
  connectOrCreate?: Prisma.TeamPerformanceStatCreateOrConnectWithoutTableTypeInput | Prisma.TeamPerformanceStatCreateOrConnectWithoutTableTypeInput[]
  upsert?: Prisma.TeamPerformanceStatUpsertWithWhereUniqueWithoutTableTypeInput | Prisma.TeamPerformanceStatUpsertWithWhereUniqueWithoutTableTypeInput[]
  createMany?: Prisma.TeamPerformanceStatCreateManyTableTypeInputEnvelope
  set?: Prisma.TeamPerformanceStatWhereUniqueInput | Prisma.TeamPerformanceStatWhereUniqueInput[]
  disconnect?: Prisma.TeamPerformanceStatWhereUniqueInput | Prisma.TeamPerformanceStatWhereUniqueInput[]
  delete?: Prisma.TeamPerformanceStatWhereUniqueInput | Prisma.TeamPerformanceStatWhereUniqueInput[]
  connect?: Prisma.TeamPerformanceStatWhereUniqueInput | Prisma.TeamPerformanceStatWhereUniqueInput[]
  update?: Prisma.TeamPerformanceStatUpdateWithWhereUniqueWithoutTableTypeInput | Prisma.TeamPerformanceStatUpdateWithWhereUniqueWithoutTableTypeInput[]
  updateMany?: Prisma.TeamPerformanceStatUpdateManyWithWhereWithoutTableTypeInput | Prisma.TeamPerformanceStatUpdateManyWithWhereWithoutTableTypeInput[]
  deleteMany?: Prisma.TeamPerformanceStatScalarWhereInput | Prisma.TeamPerformanceStatScalarWhereInput[]
}

export type TeamPerformanceStatUncheckedUpdateManyWithoutTableTypeNestedInput = {
  create?: Prisma.XOR<Prisma.TeamPerformanceStatCreateWithoutTableTypeInput, Prisma.TeamPerformanceStatUncheckedCreateWithoutTableTypeInput> | Prisma.TeamPerformanceStatCreateWithoutTableTypeInput[] | Prisma.TeamPerformanceStatUncheckedCreateWithoutTableTypeInput[]
  connectOrCreate?: Prisma.TeamPerformanceStatCreateOrConnectWithoutTableTypeInput | Prisma.TeamPerformanceStatCreateOrConnectWithoutTableTypeInput[]
  upsert?: Prisma.TeamPerformanceStatUpsertWithWhereUniqueWithoutTableTypeInput | Prisma.TeamPerformanceStatUpsertWithWhereUniqueWithoutTableTypeInput[]
  createMany?: Prisma.TeamPerformanceStatCreateManyTableTypeInputEnvelope
  set?: Prisma.TeamPerformanceStatWhereUniqueInput | Prisma.TeamPerformanceStatWhereUniqueInput[]
  disconnect?: Prisma.TeamPerformanceStatWhereUniqueInput | Prisma.TeamPerformanceStatWhereUniqueInput[]
  delete?: Prisma.TeamPerformanceStatWhereUniqueInput | Prisma.TeamPerformanceStatWhereUniqueInput[]
  connect?: Prisma.TeamPerformanceStatWhereUniqueInput | Prisma.TeamPerformanceStatWhereUniqueInput[]
  update?: Prisma.TeamPerformanceStatUpdateWithWhereUniqueWithoutTableTypeInput | Prisma.TeamPerformanceStatUpdateWithWhereUniqueWithoutTableTypeInput[]
  updateMany?: Prisma.TeamPerformanceStatUpdateManyWithWhereWithoutTableTypeInput | Prisma.TeamPerformanceStatUpdateManyWithWhereWithoutTableTypeInput[]
  deleteMany?: Prisma.TeamPerformanceStatScalarWhereInput | Prisma.TeamPerformanceStatScalarWhereInput[]
}

export type TeamPerformanceStatCreateNestedManyWithoutTeamInput = {
  create?: Prisma.XOR<Prisma.TeamPerformanceStatCreateWithoutTeamInput, Prisma.TeamPerformanceStatUncheckedCreateWithoutTeamInput> | Prisma.TeamPerformanceStatCreateWithoutTeamInput[] | Prisma.TeamPerformanceStatUncheckedCreateWithoutTeamInput[]
  connectOrCreate?: Prisma.TeamPerformanceStatCreateOrConnectWithoutTeamInput | Prisma.TeamPerformanceStatCreateOrConnectWithoutTeamInput[]
  createMany?: Prisma.TeamPerformanceStatCreateManyTeamInputEnvelope
  connect?: Prisma.TeamPerformanceStatWhereUniqueInput | Prisma.TeamPerformanceStatWhereUniqueInput[]
}

export type TeamPerformanceStatUncheckedCreateNestedManyWithoutTeamInput = {
  create?: Prisma.XOR<Prisma.TeamPerformanceStatCreateWithoutTeamInput, Prisma.TeamPerformanceStatUncheckedCreateWithoutTeamInput> | Prisma.TeamPerformanceStatCreateWithoutTeamInput[] | Prisma.TeamPerformanceStatUncheckedCreateWithoutTeamInput[]
  connectOrCreate?: Prisma.TeamPerformanceStatCreateOrConnectWithoutTeamInput | Prisma.TeamPerformanceStatCreateOrConnectWithoutTeamInput[]
  createMany?: Prisma.TeamPerformanceStatCreateManyTeamInputEnvelope
  connect?: Prisma.TeamPerformanceStatWhereUniqueInput | Prisma.TeamPerformanceStatWhereUniqueInput[]
}

export type TeamPerformanceStatUpdateManyWithoutTeamNestedInput = {
  create?: Prisma.XOR<Prisma.TeamPerformanceStatCreateWithoutTeamInput, Prisma.TeamPerformanceStatUncheckedCreateWithoutTeamInput> | Prisma.TeamPerformanceStatCreateWithoutTeamInput[] | Prisma.TeamPerformanceStatUncheckedCreateWithoutTeamInput[]
  connectOrCreate?: Prisma.TeamPerformanceStatCreateOrConnectWithoutTeamInput | Prisma.TeamPerformanceStatCreateOrConnectWithoutTeamInput[]
  upsert?: Prisma.TeamPerformanceStatUpsertWithWhereUniqueWithoutTeamInput | Prisma.TeamPerformanceStatUpsertWithWhereUniqueWithoutTeamInput[]
  createMany?: Prisma.TeamPerformanceStatCreateManyTeamInputEnvelope
  set?: Prisma.TeamPerformanceStatWhereUniqueInput | Prisma.TeamPerformanceStatWhereUniqueInput[]
  disconnect?: Prisma.TeamPerformanceStatWhereUniqueInput | Prisma.TeamPerformanceStatWhereUniqueInput[]
  delete?: Prisma.TeamPerformanceStatWhereUniqueInput | Prisma.TeamPerformanceStatWhereUniqueInput[]
  connect?: Prisma.TeamPerformanceStatWhereUniqueInput | Prisma.TeamPerformanceStatWhereUniqueInput[]
  update?: Prisma.TeamPerformanceStatUpdateWithWhereUniqueWithoutTeamInput | Prisma.TeamPerformanceStatUpdateWithWhereUniqueWithoutTeamInput[]
  updateMany?: Prisma.TeamPerformanceStatUpdateManyWithWhereWithoutTeamInput | Prisma.TeamPerformanceStatUpdateManyWithWhereWithoutTeamInput[]
  deleteMany?: Prisma.TeamPerformanceStatScalarWhereInput | Prisma.TeamPerformanceStatScalarWhereInput[]
}

export type TeamPerformanceStatUncheckedUpdateManyWithoutTeamNestedInput = {
  create?: Prisma.XOR<Prisma.TeamPerformanceStatCreateWithoutTeamInput, Prisma.TeamPerformanceStatUncheckedCreateWithoutTeamInput> | Prisma.TeamPerformanceStatCreateWithoutTeamInput[] | Prisma.TeamPerformanceStatUncheckedCreateWithoutTeamInput[]
  connectOrCreate?: Prisma.TeamPerformanceStatCreateOrConnectWithoutTeamInput | Prisma.TeamPerformanceStatCreateOrConnectWithoutTeamInput[]
  upsert?: Prisma.TeamPerformanceStatUpsertWithWhereUniqueWithoutTeamInput | Prisma.TeamPerformanceStatUpsertWithWhereUniqueWithoutTeamInput[]
  createMany?: Prisma.TeamPerformanceStatCreateManyTeamInputEnvelope
  set?: Prisma.TeamPerformanceStatWhereUniqueInput | Prisma.TeamPerformanceStatWhereUniqueInput[]
  disconnect?: Prisma.TeamPerformanceStatWhereUniqueInput | Prisma.TeamPerformanceStatWhereUniqueInput[]
  delete?: Prisma.TeamPerformanceStatWhereUniqueInput | Prisma.TeamPerformanceStatWhereUniqueInput[]
  connect?: Prisma.TeamPerformanceStatWhereUniqueInput | Prisma.TeamPerformanceStatWhereUniqueInput[]
  update?: Prisma.TeamPerformanceStatUpdateWithWhereUniqueWithoutTeamInput | Prisma.TeamPerformanceStatUpdateWithWhereUniqueWithoutTeamInput[]
  updateMany?: Prisma.TeamPerformanceStatUpdateManyWithWhereWithoutTeamInput | Prisma.TeamPerformanceStatUpdateManyWithWhereWithoutTeamInput[]
  deleteMany?: Prisma.TeamPerformanceStatScalarWhereInput | Prisma.TeamPerformanceStatScalarWhereInput[]
}

export type TeamPerformanceStatCreateNestedManyWithoutTournamentInput = {
  create?: Prisma.XOR<Prisma.TeamPerformanceStatCreateWithoutTournamentInput, Prisma.TeamPerformanceStatUncheckedCreateWithoutTournamentInput> | Prisma.TeamPerformanceStatCreateWithoutTournamentInput[] | Prisma.TeamPerformanceStatUncheckedCreateWithoutTournamentInput[]
  connectOrCreate?: Prisma.TeamPerformanceStatCreateOrConnectWithoutTournamentInput | Prisma.TeamPerformanceStatCreateOrConnectWithoutTournamentInput[]
  createMany?: Prisma.TeamPerformanceStatCreateManyTournamentInputEnvelope
  connect?: Prisma.TeamPerformanceStatWhereUniqueInput | Prisma.TeamPerformanceStatWhereUniqueInput[]
}

export type TeamPerformanceStatUncheckedCreateNestedManyWithoutTournamentInput = {
  create?: Prisma.XOR<Prisma.TeamPerformanceStatCreateWithoutTournamentInput, Prisma.TeamPerformanceStatUncheckedCreateWithoutTournamentInput> | Prisma.TeamPerformanceStatCreateWithoutTournamentInput[] | Prisma.TeamPerformanceStatUncheckedCreateWithoutTournamentInput[]
  connectOrCreate?: Prisma.TeamPerformanceStatCreateOrConnectWithoutTournamentInput | Prisma.TeamPerformanceStatCreateOrConnectWithoutTournamentInput[]
  createMany?: Prisma.TeamPerformanceStatCreateManyTournamentInputEnvelope
  connect?: Prisma.TeamPerformanceStatWhereUniqueInput | Prisma.TeamPerformanceStatWhereUniqueInput[]
}

export type TeamPerformanceStatUpdateManyWithoutTournamentNestedInput = {
  create?: Prisma.XOR<Prisma.TeamPerformanceStatCreateWithoutTournamentInput, Prisma.TeamPerformanceStatUncheckedCreateWithoutTournamentInput> | Prisma.TeamPerformanceStatCreateWithoutTournamentInput[] | Prisma.TeamPerformanceStatUncheckedCreateWithoutTournamentInput[]
  connectOrCreate?: Prisma.TeamPerformanceStatCreateOrConnectWithoutTournamentInput | Prisma.TeamPerformanceStatCreateOrConnectWithoutTournamentInput[]
  upsert?: Prisma.TeamPerformanceStatUpsertWithWhereUniqueWithoutTournamentInput | Prisma.TeamPerformanceStatUpsertWithWhereUniqueWithoutTournamentInput[]
  createMany?: Prisma.TeamPerformanceStatCreateManyTournamentInputEnvelope
  set?: Prisma.TeamPerformanceStatWhereUniqueInput | Prisma.TeamPerformanceStatWhereUniqueInput[]
  disconnect?: Prisma.TeamPerformanceStatWhereUniqueInput | Prisma.TeamPerformanceStatWhereUniqueInput[]
  delete?: Prisma.TeamPerformanceStatWhereUniqueInput | Prisma.TeamPerformanceStatWhereUniqueInput[]
  connect?: Prisma.TeamPerformanceStatWhereUniqueInput | Prisma.TeamPerformanceStatWhereUniqueInput[]
  update?: Prisma.TeamPerformanceStatUpdateWithWhereUniqueWithoutTournamentInput | Prisma.TeamPerformanceStatUpdateWithWhereUniqueWithoutTournamentInput[]
  updateMany?: Prisma.TeamPerformanceStatUpdateManyWithWhereWithoutTournamentInput | Prisma.TeamPerformanceStatUpdateManyWithWhereWithoutTournamentInput[]
  deleteMany?: Prisma.TeamPerformanceStatScalarWhereInput | Prisma.TeamPerformanceStatScalarWhereInput[]
}

export type TeamPerformanceStatUncheckedUpdateManyWithoutTournamentNestedInput = {
  create?: Prisma.XOR<Prisma.TeamPerformanceStatCreateWithoutTournamentInput, Prisma.TeamPerformanceStatUncheckedCreateWithoutTournamentInput> | Prisma.TeamPerformanceStatCreateWithoutTournamentInput[] | Prisma.TeamPerformanceStatUncheckedCreateWithoutTournamentInput[]
  connectOrCreate?: Prisma.TeamPerformanceStatCreateOrConnectWithoutTournamentInput | Prisma.TeamPerformanceStatCreateOrConnectWithoutTournamentInput[]
  upsert?: Prisma.TeamPerformanceStatUpsertWithWhereUniqueWithoutTournamentInput | Prisma.TeamPerformanceStatUpsertWithWhereUniqueWithoutTournamentInput[]
  createMany?: Prisma.TeamPerformanceStatCreateManyTournamentInputEnvelope
  set?: Prisma.TeamPerformanceStatWhereUniqueInput | Prisma.TeamPerformanceStatWhereUniqueInput[]
  disconnect?: Prisma.TeamPerformanceStatWhereUniqueInput | Prisma.TeamPerformanceStatWhereUniqueInput[]
  delete?: Prisma.TeamPerformanceStatWhereUniqueInput | Prisma.TeamPerformanceStatWhereUniqueInput[]
  connect?: Prisma.TeamPerformanceStatWhereUniqueInput | Prisma.TeamPerformanceStatWhereUniqueInput[]
  update?: Prisma.TeamPerformanceStatUpdateWithWhereUniqueWithoutTournamentInput | Prisma.TeamPerformanceStatUpdateWithWhereUniqueWithoutTournamentInput[]
  updateMany?: Prisma.TeamPerformanceStatUpdateManyWithWhereWithoutTournamentInput | Prisma.TeamPerformanceStatUpdateManyWithWhereWithoutTournamentInput[]
  deleteMany?: Prisma.TeamPerformanceStatScalarWhereInput | Prisma.TeamPerformanceStatScalarWhereInput[]
}

export type TeamPerformanceStatCreateWithoutTableTypeInput = {
  category: string
  rank: number
  matchesPlayed: number
  winPercentage: number
  drawPercentage: number
  lossPercentage: number
  goalsForPg: number
  goalsAgainstPg: number
  pointsPg: number
  createdAt?: Date | string
  updatedAt: Date | string
  mode?: string
  Team: Prisma.TeamCreateNestedOneWithoutTeamPerformanceStatInput
  Tournament: Prisma.TournamentCreateNestedOneWithoutTeamPerformanceStatInput
}

export type TeamPerformanceStatUncheckedCreateWithoutTableTypeInput = {
  id?: number
  tournamentId: number
  teamId: number
  category: string
  rank: number
  matchesPlayed: number
  winPercentage: number
  drawPercentage: number
  lossPercentage: number
  goalsForPg: number
  goalsAgainstPg: number
  pointsPg: number
  createdAt?: Date | string
  updatedAt: Date | string
  mode?: string
}

export type TeamPerformanceStatCreateOrConnectWithoutTableTypeInput = {
  where: Prisma.TeamPerformanceStatWhereUniqueInput
  create: Prisma.XOR<Prisma.TeamPerformanceStatCreateWithoutTableTypeInput, Prisma.TeamPerformanceStatUncheckedCreateWithoutTableTypeInput>
}

export type TeamPerformanceStatCreateManyTableTypeInputEnvelope = {
  data: Prisma.TeamPerformanceStatCreateManyTableTypeInput | Prisma.TeamPerformanceStatCreateManyTableTypeInput[]
  skipDuplicates?: boolean
}

export type TeamPerformanceStatUpsertWithWhereUniqueWithoutTableTypeInput = {
  where: Prisma.TeamPerformanceStatWhereUniqueInput
  update: Prisma.XOR<Prisma.TeamPerformanceStatUpdateWithoutTableTypeInput, Prisma.TeamPerformanceStatUncheckedUpdateWithoutTableTypeInput>
  create: Prisma.XOR<Prisma.TeamPerformanceStatCreateWithoutTableTypeInput, Prisma.TeamPerformanceStatUncheckedCreateWithoutTableTypeInput>
}

export type TeamPerformanceStatUpdateWithWhereUniqueWithoutTableTypeInput = {
  where: Prisma.TeamPerformanceStatWhereUniqueInput
  data: Prisma.XOR<Prisma.TeamPerformanceStatUpdateWithoutTableTypeInput, Prisma.TeamPerformanceStatUncheckedUpdateWithoutTableTypeInput>
}

export type TeamPerformanceStatUpdateManyWithWhereWithoutTableTypeInput = {
  where: Prisma.TeamPerformanceStatScalarWhereInput
  data: Prisma.XOR<Prisma.TeamPerformanceStatUpdateManyMutationInput, Prisma.TeamPerformanceStatUncheckedUpdateManyWithoutTableTypeInput>
}

export type TeamPerformanceStatScalarWhereInput = {
  AND?: Prisma.TeamPerformanceStatScalarWhereInput | Prisma.TeamPerformanceStatScalarWhereInput[]
  OR?: Prisma.TeamPerformanceStatScalarWhereInput[]
  NOT?: Prisma.TeamPerformanceStatScalarWhereInput | Prisma.TeamPerformanceStatScalarWhereInput[]
  id?: Prisma.IntFilter<"TeamPerformanceStat"> | number
  tournamentId?: Prisma.IntFilter<"TeamPerformanceStat"> | number
  teamId?: Prisma.IntFilter<"TeamPerformanceStat"> | number
  category?: Prisma.StringFilter<"TeamPerformanceStat"> | string
  rank?: Prisma.IntFilter<"TeamPerformanceStat"> | number
  matchesPlayed?: Prisma.IntFilter<"TeamPerformanceStat"> | number
  winPercentage?: Prisma.IntFilter<"TeamPerformanceStat"> | number
  drawPercentage?: Prisma.IntFilter<"TeamPerformanceStat"> | number
  lossPercentage?: Prisma.IntFilter<"TeamPerformanceStat"> | number
  goalsForPg?: Prisma.FloatFilter<"TeamPerformanceStat"> | number
  goalsAgainstPg?: Prisma.FloatFilter<"TeamPerformanceStat"> | number
  pointsPg?: Prisma.FloatFilter<"TeamPerformanceStat"> | number
  createdAt?: Prisma.DateTimeFilter<"TeamPerformanceStat"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TeamPerformanceStat"> | Date | string
  mode?: Prisma.StringFilter<"TeamPerformanceStat"> | string
  viewTypeId?: Prisma.IntFilter<"TeamPerformanceStat"> | number
}

export type TeamPerformanceStatCreateWithoutTeamInput = {
  category: string
  rank: number
  matchesPlayed: number
  winPercentage: number
  drawPercentage: number
  lossPercentage: number
  goalsForPg: number
  goalsAgainstPg: number
  pointsPg: number
  createdAt?: Date | string
  updatedAt: Date | string
  mode?: string
  Tournament: Prisma.TournamentCreateNestedOneWithoutTeamPerformanceStatInput
  TableType: Prisma.TableTypeCreateNestedOneWithoutTeamPerformanceStatInput
}

export type TeamPerformanceStatUncheckedCreateWithoutTeamInput = {
  id?: number
  tournamentId: number
  category: string
  rank: number
  matchesPlayed: number
  winPercentage: number
  drawPercentage: number
  lossPercentage: number
  goalsForPg: number
  goalsAgainstPg: number
  pointsPg: number
  createdAt?: Date | string
  updatedAt: Date | string
  mode?: string
  viewTypeId: number
}

export type TeamPerformanceStatCreateOrConnectWithoutTeamInput = {
  where: Prisma.TeamPerformanceStatWhereUniqueInput
  create: Prisma.XOR<Prisma.TeamPerformanceStatCreateWithoutTeamInput, Prisma.TeamPerformanceStatUncheckedCreateWithoutTeamInput>
}

export type TeamPerformanceStatCreateManyTeamInputEnvelope = {
  data: Prisma.TeamPerformanceStatCreateManyTeamInput | Prisma.TeamPerformanceStatCreateManyTeamInput[]
  skipDuplicates?: boolean
}

export type TeamPerformanceStatUpsertWithWhereUniqueWithoutTeamInput = {
  where: Prisma.TeamPerformanceStatWhereUniqueInput
  update: Prisma.XOR<Prisma.TeamPerformanceStatUpdateWithoutTeamInput, Prisma.TeamPerformanceStatUncheckedUpdateWithoutTeamInput>
  create: Prisma.XOR<Prisma.TeamPerformanceStatCreateWithoutTeamInput, Prisma.TeamPerformanceStatUncheckedCreateWithoutTeamInput>
}

export type TeamPerformanceStatUpdateWithWhereUniqueWithoutTeamInput = {
  where: Prisma.TeamPerformanceStatWhereUniqueInput
  data: Prisma.XOR<Prisma.TeamPerformanceStatUpdateWithoutTeamInput, Prisma.TeamPerformanceStatUncheckedUpdateWithoutTeamInput>
}

export type TeamPerformanceStatUpdateManyWithWhereWithoutTeamInput = {
  where: Prisma.TeamPerformanceStatScalarWhereInput
  data: Prisma.XOR<Prisma.TeamPerformanceStatUpdateManyMutationInput, Prisma.TeamPerformanceStatUncheckedUpdateManyWithoutTeamInput>
}

export type TeamPerformanceStatCreateWithoutTournamentInput = {
  category: string
  rank: number
  matchesPlayed: number
  winPercentage: number
  drawPercentage: number
  lossPercentage: number
  goalsForPg: number
  goalsAgainstPg: number
  pointsPg: number
  createdAt?: Date | string
  updatedAt: Date | string
  mode?: string
  Team: Prisma.TeamCreateNestedOneWithoutTeamPerformanceStatInput
  TableType: Prisma.TableTypeCreateNestedOneWithoutTeamPerformanceStatInput
}

export type TeamPerformanceStatUncheckedCreateWithoutTournamentInput = {
  id?: number
  teamId: number
  category: string
  rank: number
  matchesPlayed: number
  winPercentage: number
  drawPercentage: number
  lossPercentage: number
  goalsForPg: number
  goalsAgainstPg: number
  pointsPg: number
  createdAt?: Date | string
  updatedAt: Date | string
  mode?: string
  viewTypeId: number
}

export type TeamPerformanceStatCreateOrConnectWithoutTournamentInput = {
  where: Prisma.TeamPerformanceStatWhereUniqueInput
  create: Prisma.XOR<Prisma.TeamPerformanceStatCreateWithoutTournamentInput, Prisma.TeamPerformanceStatUncheckedCreateWithoutTournamentInput>
}

export type TeamPerformanceStatCreateManyTournamentInputEnvelope = {
  data: Prisma.TeamPerformanceStatCreateManyTournamentInput | Prisma.TeamPerformanceStatCreateManyTournamentInput[]
  skipDuplicates?: boolean
}

export type TeamPerformanceStatUpsertWithWhereUniqueWithoutTournamentInput = {
  where: Prisma.TeamPerformanceStatWhereUniqueInput
  update: Prisma.XOR<Prisma.TeamPerformanceStatUpdateWithoutTournamentInput, Prisma.TeamPerformanceStatUncheckedUpdateWithoutTournamentInput>
  create: Prisma.XOR<Prisma.TeamPerformanceStatCreateWithoutTournamentInput, Prisma.TeamPerformanceStatUncheckedCreateWithoutTournamentInput>
}

export type TeamPerformanceStatUpdateWithWhereUniqueWithoutTournamentInput = {
  where: Prisma.TeamPerformanceStatWhereUniqueInput
  data: Prisma.XOR<Prisma.TeamPerformanceStatUpdateWithoutTournamentInput, Prisma.TeamPerformanceStatUncheckedUpdateWithoutTournamentInput>
}

export type TeamPerformanceStatUpdateManyWithWhereWithoutTournamentInput = {
  where: Prisma.TeamPerformanceStatScalarWhereInput
  data: Prisma.XOR<Prisma.TeamPerformanceStatUpdateManyMutationInput, Prisma.TeamPerformanceStatUncheckedUpdateManyWithoutTournamentInput>
}

export type TeamPerformanceStatCreateManyTableTypeInput = {
  id?: number
  tournamentId: number
  teamId: number
  category: string
  rank: number
  matchesPlayed: number
  winPercentage: number
  drawPercentage: number
  lossPercentage: number
  goalsForPg: number
  goalsAgainstPg: number
  pointsPg: number
  createdAt?: Date | string
  updatedAt: Date | string
  mode?: string
}

export type TeamPerformanceStatUpdateWithoutTableTypeInput = {
  category?: Prisma.StringFieldUpdateOperationsInput | string
  rank?: Prisma.IntFieldUpdateOperationsInput | number
  matchesPlayed?: Prisma.IntFieldUpdateOperationsInput | number
  winPercentage?: Prisma.IntFieldUpdateOperationsInput | number
  drawPercentage?: Prisma.IntFieldUpdateOperationsInput | number
  lossPercentage?: Prisma.IntFieldUpdateOperationsInput | number
  goalsForPg?: Prisma.FloatFieldUpdateOperationsInput | number
  goalsAgainstPg?: Prisma.FloatFieldUpdateOperationsInput | number
  pointsPg?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mode?: Prisma.StringFieldUpdateOperationsInput | string
  Team?: Prisma.TeamUpdateOneRequiredWithoutTeamPerformanceStatNestedInput
  Tournament?: Prisma.TournamentUpdateOneRequiredWithoutTeamPerformanceStatNestedInput
}

export type TeamPerformanceStatUncheckedUpdateWithoutTableTypeInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  tournamentId?: Prisma.IntFieldUpdateOperationsInput | number
  teamId?: Prisma.IntFieldUpdateOperationsInput | number
  category?: Prisma.StringFieldUpdateOperationsInput | string
  rank?: Prisma.IntFieldUpdateOperationsInput | number
  matchesPlayed?: Prisma.IntFieldUpdateOperationsInput | number
  winPercentage?: Prisma.IntFieldUpdateOperationsInput | number
  drawPercentage?: Prisma.IntFieldUpdateOperationsInput | number
  lossPercentage?: Prisma.IntFieldUpdateOperationsInput | number
  goalsForPg?: Prisma.FloatFieldUpdateOperationsInput | number
  goalsAgainstPg?: Prisma.FloatFieldUpdateOperationsInput | number
  pointsPg?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mode?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TeamPerformanceStatUncheckedUpdateManyWithoutTableTypeInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  tournamentId?: Prisma.IntFieldUpdateOperationsInput | number
  teamId?: Prisma.IntFieldUpdateOperationsInput | number
  category?: Prisma.StringFieldUpdateOperationsInput | string
  rank?: Prisma.IntFieldUpdateOperationsInput | number
  matchesPlayed?: Prisma.IntFieldUpdateOperationsInput | number
  winPercentage?: Prisma.IntFieldUpdateOperationsInput | number
  drawPercentage?: Prisma.IntFieldUpdateOperationsInput | number
  lossPercentage?: Prisma.IntFieldUpdateOperationsInput | number
  goalsForPg?: Prisma.FloatFieldUpdateOperationsInput | number
  goalsAgainstPg?: Prisma.FloatFieldUpdateOperationsInput | number
  pointsPg?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mode?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TeamPerformanceStatCreateManyTeamInput = {
  id?: number
  tournamentId: number
  category: string
  rank: number
  matchesPlayed: number
  winPercentage: number
  drawPercentage: number
  lossPercentage: number
  goalsForPg: number
  goalsAgainstPg: number
  pointsPg: number
  createdAt?: Date | string
  updatedAt: Date | string
  mode?: string
  viewTypeId: number
}

export type TeamPerformanceStatUpdateWithoutTeamInput = {
  category?: Prisma.StringFieldUpdateOperationsInput | string
  rank?: Prisma.IntFieldUpdateOperationsInput | number
  matchesPlayed?: Prisma.IntFieldUpdateOperationsInput | number
  winPercentage?: Prisma.IntFieldUpdateOperationsInput | number
  drawPercentage?: Prisma.IntFieldUpdateOperationsInput | number
  lossPercentage?: Prisma.IntFieldUpdateOperationsInput | number
  goalsForPg?: Prisma.FloatFieldUpdateOperationsInput | number
  goalsAgainstPg?: Prisma.FloatFieldUpdateOperationsInput | number
  pointsPg?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mode?: Prisma.StringFieldUpdateOperationsInput | string
  Tournament?: Prisma.TournamentUpdateOneRequiredWithoutTeamPerformanceStatNestedInput
  TableType?: Prisma.TableTypeUpdateOneRequiredWithoutTeamPerformanceStatNestedInput
}

export type TeamPerformanceStatUncheckedUpdateWithoutTeamInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  tournamentId?: Prisma.IntFieldUpdateOperationsInput | number
  category?: Prisma.StringFieldUpdateOperationsInput | string
  rank?: Prisma.IntFieldUpdateOperationsInput | number
  matchesPlayed?: Prisma.IntFieldUpdateOperationsInput | number
  winPercentage?: Prisma.IntFieldUpdateOperationsInput | number
  drawPercentage?: Prisma.IntFieldUpdateOperationsInput | number
  lossPercentage?: Prisma.IntFieldUpdateOperationsInput | number
  goalsForPg?: Prisma.FloatFieldUpdateOperationsInput | number
  goalsAgainstPg?: Prisma.FloatFieldUpdateOperationsInput | number
  pointsPg?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mode?: Prisma.StringFieldUpdateOperationsInput | string
  viewTypeId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type TeamPerformanceStatUncheckedUpdateManyWithoutTeamInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  tournamentId?: Prisma.IntFieldUpdateOperationsInput | number
  category?: Prisma.StringFieldUpdateOperationsInput | string
  rank?: Prisma.IntFieldUpdateOperationsInput | number
  matchesPlayed?: Prisma.IntFieldUpdateOperationsInput | number
  winPercentage?: Prisma.IntFieldUpdateOperationsInput | number
  drawPercentage?: Prisma.IntFieldUpdateOperationsInput | number
  lossPercentage?: Prisma.IntFieldUpdateOperationsInput | number
  goalsForPg?: Prisma.FloatFieldUpdateOperationsInput | number
  goalsAgainstPg?: Prisma.FloatFieldUpdateOperationsInput | number
  pointsPg?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mode?: Prisma.StringFieldUpdateOperationsInput | string
  viewTypeId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type TeamPerformanceStatCreateManyTournamentInput = {
  id?: number
  teamId: number
  category: string
  rank: number
  matchesPlayed: number
  winPercentage: number
  drawPercentage: number
  lossPercentage: number
  goalsForPg: number
  goalsAgainstPg: number
  pointsPg: number
  createdAt?: Date | string
  updatedAt: Date | string
  mode?: string
  viewTypeId: number
}

export type TeamPerformanceStatUpdateWithoutTournamentInput = {
  category?: Prisma.StringFieldUpdateOperationsInput | string
  rank?: Prisma.IntFieldUpdateOperationsInput | number
  matchesPlayed?: Prisma.IntFieldUpdateOperationsInput | number
  winPercentage?: Prisma.IntFieldUpdateOperationsInput | number
  drawPercentage?: Prisma.IntFieldUpdateOperationsInput | number
  lossPercentage?: Prisma.IntFieldUpdateOperationsInput | number
  goalsForPg?: Prisma.FloatFieldUpdateOperationsInput | number
  goalsAgainstPg?: Prisma.FloatFieldUpdateOperationsInput | number
  pointsPg?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mode?: Prisma.StringFieldUpdateOperationsInput | string
  Team?: Prisma.TeamUpdateOneRequiredWithoutTeamPerformanceStatNestedInput
  TableType?: Prisma.TableTypeUpdateOneRequiredWithoutTeamPerformanceStatNestedInput
}

export type TeamPerformanceStatUncheckedUpdateWithoutTournamentInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  teamId?: Prisma.IntFieldUpdateOperationsInput | number
  category?: Prisma.StringFieldUpdateOperationsInput | string
  rank?: Prisma.IntFieldUpdateOperationsInput | number
  matchesPlayed?: Prisma.IntFieldUpdateOperationsInput | number
  winPercentage?: Prisma.IntFieldUpdateOperationsInput | number
  drawPercentage?: Prisma.IntFieldUpdateOperationsInput | number
  lossPercentage?: Prisma.IntFieldUpdateOperationsInput | number
  goalsForPg?: Prisma.FloatFieldUpdateOperationsInput | number
  goalsAgainstPg?: Prisma.FloatFieldUpdateOperationsInput | number
  pointsPg?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mode?: Prisma.StringFieldUpdateOperationsInput | string
  viewTypeId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type TeamPerformanceStatUncheckedUpdateManyWithoutTournamentInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  teamId?: Prisma.IntFieldUpdateOperationsInput | number
  category?: Prisma.StringFieldUpdateOperationsInput | string
  rank?: Prisma.IntFieldUpdateOperationsInput | number
  matchesPlayed?: Prisma.IntFieldUpdateOperationsInput | number
  winPercentage?: Prisma.IntFieldUpdateOperationsInput | number
  drawPercentage?: Prisma.IntFieldUpdateOperationsInput | number
  lossPercentage?: Prisma.IntFieldUpdateOperationsInput | number
  goalsForPg?: Prisma.FloatFieldUpdateOperationsInput | number
  goalsAgainstPg?: Prisma.FloatFieldUpdateOperationsInput | number
  pointsPg?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mode?: Prisma.StringFieldUpdateOperationsInput | string
  viewTypeId?: Prisma.IntFieldUpdateOperationsInput | number
}



export type TeamPerformanceStatSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tournamentId?: boolean
  teamId?: boolean
  category?: boolean
  rank?: boolean
  matchesPlayed?: boolean
  winPercentage?: boolean
  drawPercentage?: boolean
  lossPercentage?: boolean
  goalsForPg?: boolean
  goalsAgainstPg?: boolean
  pointsPg?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  mode?: boolean
  viewTypeId?: boolean
  Team?: boolean | Prisma.TeamDefaultArgs<ExtArgs>
  Tournament?: boolean | Prisma.TournamentDefaultArgs<ExtArgs>
  TableType?: boolean | Prisma.TableTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["teamPerformanceStat"]>

export type TeamPerformanceStatSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tournamentId?: boolean
  teamId?: boolean
  category?: boolean
  rank?: boolean
  matchesPlayed?: boolean
  winPercentage?: boolean
  drawPercentage?: boolean
  lossPercentage?: boolean
  goalsForPg?: boolean
  goalsAgainstPg?: boolean
  pointsPg?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  mode?: boolean
  viewTypeId?: boolean
  Team?: boolean | Prisma.TeamDefaultArgs<ExtArgs>
  Tournament?: boolean | Prisma.TournamentDefaultArgs<ExtArgs>
  TableType?: boolean | Prisma.TableTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["teamPerformanceStat"]>

export type TeamPerformanceStatSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tournamentId?: boolean
  teamId?: boolean
  category?: boolean
  rank?: boolean
  matchesPlayed?: boolean
  winPercentage?: boolean
  drawPercentage?: boolean
  lossPercentage?: boolean
  goalsForPg?: boolean
  goalsAgainstPg?: boolean
  pointsPg?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  mode?: boolean
  viewTypeId?: boolean
  Team?: boolean | Prisma.TeamDefaultArgs<ExtArgs>
  Tournament?: boolean | Prisma.TournamentDefaultArgs<ExtArgs>
  TableType?: boolean | Prisma.TableTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["teamPerformanceStat"]>

export type TeamPerformanceStatSelectScalar = {
  id?: boolean
  tournamentId?: boolean
  teamId?: boolean
  category?: boolean
  rank?: boolean
  matchesPlayed?: boolean
  winPercentage?: boolean
  drawPercentage?: boolean
  lossPercentage?: boolean
  goalsForPg?: boolean
  goalsAgainstPg?: boolean
  pointsPg?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  mode?: boolean
  viewTypeId?: boolean
}

export type TeamPerformanceStatOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "tournamentId" | "teamId" | "category" | "rank" | "matchesPlayed" | "winPercentage" | "drawPercentage" | "lossPercentage" | "goalsForPg" | "goalsAgainstPg" | "pointsPg" | "createdAt" | "updatedAt" | "mode" | "viewTypeId", ExtArgs["result"]["teamPerformanceStat"]>
export type TeamPerformanceStatInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Team?: boolean | Prisma.TeamDefaultArgs<ExtArgs>
  Tournament?: boolean | Prisma.TournamentDefaultArgs<ExtArgs>
  TableType?: boolean | Prisma.TableTypeDefaultArgs<ExtArgs>
}
export type TeamPerformanceStatIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Team?: boolean | Prisma.TeamDefaultArgs<ExtArgs>
  Tournament?: boolean | Prisma.TournamentDefaultArgs<ExtArgs>
  TableType?: boolean | Prisma.TableTypeDefaultArgs<ExtArgs>
}
export type TeamPerformanceStatIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Team?: boolean | Prisma.TeamDefaultArgs<ExtArgs>
  Tournament?: boolean | Prisma.TournamentDefaultArgs<ExtArgs>
  TableType?: boolean | Prisma.TableTypeDefaultArgs<ExtArgs>
}

export type $TeamPerformanceStatPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TeamPerformanceStat"
  objects: {
    Team: Prisma.$TeamPayload<ExtArgs>
    Tournament: Prisma.$TournamentPayload<ExtArgs>
    TableType: Prisma.$TableTypePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    tournamentId: number
    teamId: number
    category: string
    rank: number
    matchesPlayed: number
    winPercentage: number
    drawPercentage: number
    lossPercentage: number
    goalsForPg: number
    goalsAgainstPg: number
    pointsPg: number
    createdAt: Date
    updatedAt: Date
    mode: string
    viewTypeId: number
  }, ExtArgs["result"]["teamPerformanceStat"]>
  composites: {}
}

export type TeamPerformanceStatGetPayload<S extends boolean | null | undefined | TeamPerformanceStatDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TeamPerformanceStatPayload, S>

export type TeamPerformanceStatCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TeamPerformanceStatFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TeamPerformanceStatCountAggregateInputType | true
  }

export interface TeamPerformanceStatDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TeamPerformanceStat'], meta: { name: 'TeamPerformanceStat' } }
  /**
   * Find zero or one TeamPerformanceStat that matches the filter.
   * @param {TeamPerformanceStatFindUniqueArgs} args - Arguments to find a TeamPerformanceStat
   * @example
   * // Get one TeamPerformanceStat
   * const teamPerformanceStat = await prisma.teamPerformanceStat.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TeamPerformanceStatFindUniqueArgs>(args: Prisma.SelectSubset<T, TeamPerformanceStatFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TeamPerformanceStatClient<runtime.Types.Result.GetResult<Prisma.$TeamPerformanceStatPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TeamPerformanceStat that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TeamPerformanceStatFindUniqueOrThrowArgs} args - Arguments to find a TeamPerformanceStat
   * @example
   * // Get one TeamPerformanceStat
   * const teamPerformanceStat = await prisma.teamPerformanceStat.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TeamPerformanceStatFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TeamPerformanceStatFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TeamPerformanceStatClient<runtime.Types.Result.GetResult<Prisma.$TeamPerformanceStatPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TeamPerformanceStat that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TeamPerformanceStatFindFirstArgs} args - Arguments to find a TeamPerformanceStat
   * @example
   * // Get one TeamPerformanceStat
   * const teamPerformanceStat = await prisma.teamPerformanceStat.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TeamPerformanceStatFindFirstArgs>(args?: Prisma.SelectSubset<T, TeamPerformanceStatFindFirstArgs<ExtArgs>>): Prisma.Prisma__TeamPerformanceStatClient<runtime.Types.Result.GetResult<Prisma.$TeamPerformanceStatPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TeamPerformanceStat that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TeamPerformanceStatFindFirstOrThrowArgs} args - Arguments to find a TeamPerformanceStat
   * @example
   * // Get one TeamPerformanceStat
   * const teamPerformanceStat = await prisma.teamPerformanceStat.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TeamPerformanceStatFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TeamPerformanceStatFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TeamPerformanceStatClient<runtime.Types.Result.GetResult<Prisma.$TeamPerformanceStatPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TeamPerformanceStats that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TeamPerformanceStatFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TeamPerformanceStats
   * const teamPerformanceStats = await prisma.teamPerformanceStat.findMany()
   * 
   * // Get first 10 TeamPerformanceStats
   * const teamPerformanceStats = await prisma.teamPerformanceStat.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const teamPerformanceStatWithIdOnly = await prisma.teamPerformanceStat.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TeamPerformanceStatFindManyArgs>(args?: Prisma.SelectSubset<T, TeamPerformanceStatFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TeamPerformanceStatPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TeamPerformanceStat.
   * @param {TeamPerformanceStatCreateArgs} args - Arguments to create a TeamPerformanceStat.
   * @example
   * // Create one TeamPerformanceStat
   * const TeamPerformanceStat = await prisma.teamPerformanceStat.create({
   *   data: {
   *     // ... data to create a TeamPerformanceStat
   *   }
   * })
   * 
   */
  create<T extends TeamPerformanceStatCreateArgs>(args: Prisma.SelectSubset<T, TeamPerformanceStatCreateArgs<ExtArgs>>): Prisma.Prisma__TeamPerformanceStatClient<runtime.Types.Result.GetResult<Prisma.$TeamPerformanceStatPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TeamPerformanceStats.
   * @param {TeamPerformanceStatCreateManyArgs} args - Arguments to create many TeamPerformanceStats.
   * @example
   * // Create many TeamPerformanceStats
   * const teamPerformanceStat = await prisma.teamPerformanceStat.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TeamPerformanceStatCreateManyArgs>(args?: Prisma.SelectSubset<T, TeamPerformanceStatCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TeamPerformanceStats and returns the data saved in the database.
   * @param {TeamPerformanceStatCreateManyAndReturnArgs} args - Arguments to create many TeamPerformanceStats.
   * @example
   * // Create many TeamPerformanceStats
   * const teamPerformanceStat = await prisma.teamPerformanceStat.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TeamPerformanceStats and only return the `id`
   * const teamPerformanceStatWithIdOnly = await prisma.teamPerformanceStat.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TeamPerformanceStatCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TeamPerformanceStatCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TeamPerformanceStatPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TeamPerformanceStat.
   * @param {TeamPerformanceStatDeleteArgs} args - Arguments to delete one TeamPerformanceStat.
   * @example
   * // Delete one TeamPerformanceStat
   * const TeamPerformanceStat = await prisma.teamPerformanceStat.delete({
   *   where: {
   *     // ... filter to delete one TeamPerformanceStat
   *   }
   * })
   * 
   */
  delete<T extends TeamPerformanceStatDeleteArgs>(args: Prisma.SelectSubset<T, TeamPerformanceStatDeleteArgs<ExtArgs>>): Prisma.Prisma__TeamPerformanceStatClient<runtime.Types.Result.GetResult<Prisma.$TeamPerformanceStatPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TeamPerformanceStat.
   * @param {TeamPerformanceStatUpdateArgs} args - Arguments to update one TeamPerformanceStat.
   * @example
   * // Update one TeamPerformanceStat
   * const teamPerformanceStat = await prisma.teamPerformanceStat.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TeamPerformanceStatUpdateArgs>(args: Prisma.SelectSubset<T, TeamPerformanceStatUpdateArgs<ExtArgs>>): Prisma.Prisma__TeamPerformanceStatClient<runtime.Types.Result.GetResult<Prisma.$TeamPerformanceStatPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TeamPerformanceStats.
   * @param {TeamPerformanceStatDeleteManyArgs} args - Arguments to filter TeamPerformanceStats to delete.
   * @example
   * // Delete a few TeamPerformanceStats
   * const { count } = await prisma.teamPerformanceStat.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TeamPerformanceStatDeleteManyArgs>(args?: Prisma.SelectSubset<T, TeamPerformanceStatDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TeamPerformanceStats.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TeamPerformanceStatUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TeamPerformanceStats
   * const teamPerformanceStat = await prisma.teamPerformanceStat.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TeamPerformanceStatUpdateManyArgs>(args: Prisma.SelectSubset<T, TeamPerformanceStatUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TeamPerformanceStats and returns the data updated in the database.
   * @param {TeamPerformanceStatUpdateManyAndReturnArgs} args - Arguments to update many TeamPerformanceStats.
   * @example
   * // Update many TeamPerformanceStats
   * const teamPerformanceStat = await prisma.teamPerformanceStat.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TeamPerformanceStats and only return the `id`
   * const teamPerformanceStatWithIdOnly = await prisma.teamPerformanceStat.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TeamPerformanceStatUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TeamPerformanceStatUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TeamPerformanceStatPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TeamPerformanceStat.
   * @param {TeamPerformanceStatUpsertArgs} args - Arguments to update or create a TeamPerformanceStat.
   * @example
   * // Update or create a TeamPerformanceStat
   * const teamPerformanceStat = await prisma.teamPerformanceStat.upsert({
   *   create: {
   *     // ... data to create a TeamPerformanceStat
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TeamPerformanceStat we want to update
   *   }
   * })
   */
  upsert<T extends TeamPerformanceStatUpsertArgs>(args: Prisma.SelectSubset<T, TeamPerformanceStatUpsertArgs<ExtArgs>>): Prisma.Prisma__TeamPerformanceStatClient<runtime.Types.Result.GetResult<Prisma.$TeamPerformanceStatPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TeamPerformanceStats.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TeamPerformanceStatCountArgs} args - Arguments to filter TeamPerformanceStats to count.
   * @example
   * // Count the number of TeamPerformanceStats
   * const count = await prisma.teamPerformanceStat.count({
   *   where: {
   *     // ... the filter for the TeamPerformanceStats we want to count
   *   }
   * })
  **/
  count<T extends TeamPerformanceStatCountArgs>(
    args?: Prisma.Subset<T, TeamPerformanceStatCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TeamPerformanceStatCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TeamPerformanceStat.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TeamPerformanceStatAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TeamPerformanceStatAggregateArgs>(args: Prisma.Subset<T, TeamPerformanceStatAggregateArgs>): Prisma.PrismaPromise<GetTeamPerformanceStatAggregateType<T>>

  /**
   * Group by TeamPerformanceStat.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TeamPerformanceStatGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TeamPerformanceStatGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TeamPerformanceStatGroupByArgs['orderBy'] }
      : { orderBy?: TeamPerformanceStatGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TeamPerformanceStatGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTeamPerformanceStatGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TeamPerformanceStat model
 */
readonly fields: TeamPerformanceStatFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TeamPerformanceStat.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TeamPerformanceStatClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  Team<T extends Prisma.TeamDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TeamDefaultArgs<ExtArgs>>): Prisma.Prisma__TeamClient<runtime.Types.Result.GetResult<Prisma.$TeamPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  Tournament<T extends Prisma.TournamentDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TournamentDefaultArgs<ExtArgs>>): Prisma.Prisma__TournamentClient<runtime.Types.Result.GetResult<Prisma.$TournamentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  TableType<T extends Prisma.TableTypeDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TableTypeDefaultArgs<ExtArgs>>): Prisma.Prisma__TableTypeClient<runtime.Types.Result.GetResult<Prisma.$TableTypePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TeamPerformanceStat model
 */
export interface TeamPerformanceStatFieldRefs {
  readonly id: Prisma.FieldRef<"TeamPerformanceStat", 'Int'>
  readonly tournamentId: Prisma.FieldRef<"TeamPerformanceStat", 'Int'>
  readonly teamId: Prisma.FieldRef<"TeamPerformanceStat", 'Int'>
  readonly category: Prisma.FieldRef<"TeamPerformanceStat", 'String'>
  readonly rank: Prisma.FieldRef<"TeamPerformanceStat", 'Int'>
  readonly matchesPlayed: Prisma.FieldRef<"TeamPerformanceStat", 'Int'>
  readonly winPercentage: Prisma.FieldRef<"TeamPerformanceStat", 'Int'>
  readonly drawPercentage: Prisma.FieldRef<"TeamPerformanceStat", 'Int'>
  readonly lossPercentage: Prisma.FieldRef<"TeamPerformanceStat", 'Int'>
  readonly goalsForPg: Prisma.FieldRef<"TeamPerformanceStat", 'Float'>
  readonly goalsAgainstPg: Prisma.FieldRef<"TeamPerformanceStat", 'Float'>
  readonly pointsPg: Prisma.FieldRef<"TeamPerformanceStat", 'Float'>
  readonly createdAt: Prisma.FieldRef<"TeamPerformanceStat", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"TeamPerformanceStat", 'DateTime'>
  readonly mode: Prisma.FieldRef<"TeamPerformanceStat", 'String'>
  readonly viewTypeId: Prisma.FieldRef<"TeamPerformanceStat", 'Int'>
}
    

// Custom InputTypes
/**
 * TeamPerformanceStat findUnique
 */
export type TeamPerformanceStatFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TeamPerformanceStat
   */
  select?: Prisma.TeamPerformanceStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TeamPerformanceStat
   */
  omit?: Prisma.TeamPerformanceStatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TeamPerformanceStatInclude<ExtArgs> | null
  /**
   * Filter, which TeamPerformanceStat to fetch.
   */
  where: Prisma.TeamPerformanceStatWhereUniqueInput
}

/**
 * TeamPerformanceStat findUniqueOrThrow
 */
export type TeamPerformanceStatFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TeamPerformanceStat
   */
  select?: Prisma.TeamPerformanceStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TeamPerformanceStat
   */
  omit?: Prisma.TeamPerformanceStatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TeamPerformanceStatInclude<ExtArgs> | null
  /**
   * Filter, which TeamPerformanceStat to fetch.
   */
  where: Prisma.TeamPerformanceStatWhereUniqueInput
}

/**
 * TeamPerformanceStat findFirst
 */
export type TeamPerformanceStatFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TeamPerformanceStat
   */
  select?: Prisma.TeamPerformanceStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TeamPerformanceStat
   */
  omit?: Prisma.TeamPerformanceStatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TeamPerformanceStatInclude<ExtArgs> | null
  /**
   * Filter, which TeamPerformanceStat to fetch.
   */
  where?: Prisma.TeamPerformanceStatWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TeamPerformanceStats to fetch.
   */
  orderBy?: Prisma.TeamPerformanceStatOrderByWithRelationInput | Prisma.TeamPerformanceStatOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TeamPerformanceStats.
   */
  cursor?: Prisma.TeamPerformanceStatWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TeamPerformanceStats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TeamPerformanceStats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TeamPerformanceStats.
   */
  distinct?: Prisma.TeamPerformanceStatScalarFieldEnum | Prisma.TeamPerformanceStatScalarFieldEnum[]
}

/**
 * TeamPerformanceStat findFirstOrThrow
 */
export type TeamPerformanceStatFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TeamPerformanceStat
   */
  select?: Prisma.TeamPerformanceStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TeamPerformanceStat
   */
  omit?: Prisma.TeamPerformanceStatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TeamPerformanceStatInclude<ExtArgs> | null
  /**
   * Filter, which TeamPerformanceStat to fetch.
   */
  where?: Prisma.TeamPerformanceStatWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TeamPerformanceStats to fetch.
   */
  orderBy?: Prisma.TeamPerformanceStatOrderByWithRelationInput | Prisma.TeamPerformanceStatOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TeamPerformanceStats.
   */
  cursor?: Prisma.TeamPerformanceStatWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TeamPerformanceStats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TeamPerformanceStats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TeamPerformanceStats.
   */
  distinct?: Prisma.TeamPerformanceStatScalarFieldEnum | Prisma.TeamPerformanceStatScalarFieldEnum[]
}

/**
 * TeamPerformanceStat findMany
 */
export type TeamPerformanceStatFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TeamPerformanceStat
   */
  select?: Prisma.TeamPerformanceStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TeamPerformanceStat
   */
  omit?: Prisma.TeamPerformanceStatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TeamPerformanceStatInclude<ExtArgs> | null
  /**
   * Filter, which TeamPerformanceStats to fetch.
   */
  where?: Prisma.TeamPerformanceStatWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TeamPerformanceStats to fetch.
   */
  orderBy?: Prisma.TeamPerformanceStatOrderByWithRelationInput | Prisma.TeamPerformanceStatOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TeamPerformanceStats.
   */
  cursor?: Prisma.TeamPerformanceStatWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TeamPerformanceStats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TeamPerformanceStats.
   */
  skip?: number
  distinct?: Prisma.TeamPerformanceStatScalarFieldEnum | Prisma.TeamPerformanceStatScalarFieldEnum[]
}

/**
 * TeamPerformanceStat create
 */
export type TeamPerformanceStatCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TeamPerformanceStat
   */
  select?: Prisma.TeamPerformanceStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TeamPerformanceStat
   */
  omit?: Prisma.TeamPerformanceStatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TeamPerformanceStatInclude<ExtArgs> | null
  /**
   * The data needed to create a TeamPerformanceStat.
   */
  data: Prisma.XOR<Prisma.TeamPerformanceStatCreateInput, Prisma.TeamPerformanceStatUncheckedCreateInput>
}

/**
 * TeamPerformanceStat createMany
 */
export type TeamPerformanceStatCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TeamPerformanceStats.
   */
  data: Prisma.TeamPerformanceStatCreateManyInput | Prisma.TeamPerformanceStatCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TeamPerformanceStat createManyAndReturn
 */
export type TeamPerformanceStatCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TeamPerformanceStat
   */
  select?: Prisma.TeamPerformanceStatSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TeamPerformanceStat
   */
  omit?: Prisma.TeamPerformanceStatOmit<ExtArgs> | null
  /**
   * The data used to create many TeamPerformanceStats.
   */
  data: Prisma.TeamPerformanceStatCreateManyInput | Prisma.TeamPerformanceStatCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TeamPerformanceStatIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * TeamPerformanceStat update
 */
export type TeamPerformanceStatUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TeamPerformanceStat
   */
  select?: Prisma.TeamPerformanceStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TeamPerformanceStat
   */
  omit?: Prisma.TeamPerformanceStatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TeamPerformanceStatInclude<ExtArgs> | null
  /**
   * The data needed to update a TeamPerformanceStat.
   */
  data: Prisma.XOR<Prisma.TeamPerformanceStatUpdateInput, Prisma.TeamPerformanceStatUncheckedUpdateInput>
  /**
   * Choose, which TeamPerformanceStat to update.
   */
  where: Prisma.TeamPerformanceStatWhereUniqueInput
}

/**
 * TeamPerformanceStat updateMany
 */
export type TeamPerformanceStatUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TeamPerformanceStats.
   */
  data: Prisma.XOR<Prisma.TeamPerformanceStatUpdateManyMutationInput, Prisma.TeamPerformanceStatUncheckedUpdateManyInput>
  /**
   * Filter which TeamPerformanceStats to update
   */
  where?: Prisma.TeamPerformanceStatWhereInput
  /**
   * Limit how many TeamPerformanceStats to update.
   */
  limit?: number
}

/**
 * TeamPerformanceStat updateManyAndReturn
 */
export type TeamPerformanceStatUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TeamPerformanceStat
   */
  select?: Prisma.TeamPerformanceStatSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TeamPerformanceStat
   */
  omit?: Prisma.TeamPerformanceStatOmit<ExtArgs> | null
  /**
   * The data used to update TeamPerformanceStats.
   */
  data: Prisma.XOR<Prisma.TeamPerformanceStatUpdateManyMutationInput, Prisma.TeamPerformanceStatUncheckedUpdateManyInput>
  /**
   * Filter which TeamPerformanceStats to update
   */
  where?: Prisma.TeamPerformanceStatWhereInput
  /**
   * Limit how many TeamPerformanceStats to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TeamPerformanceStatIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * TeamPerformanceStat upsert
 */
export type TeamPerformanceStatUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TeamPerformanceStat
   */
  select?: Prisma.TeamPerformanceStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TeamPerformanceStat
   */
  omit?: Prisma.TeamPerformanceStatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TeamPerformanceStatInclude<ExtArgs> | null
  /**
   * The filter to search for the TeamPerformanceStat to update in case it exists.
   */
  where: Prisma.TeamPerformanceStatWhereUniqueInput
  /**
   * In case the TeamPerformanceStat found by the `where` argument doesn't exist, create a new TeamPerformanceStat with this data.
   */
  create: Prisma.XOR<Prisma.TeamPerformanceStatCreateInput, Prisma.TeamPerformanceStatUncheckedCreateInput>
  /**
   * In case the TeamPerformanceStat was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TeamPerformanceStatUpdateInput, Prisma.TeamPerformanceStatUncheckedUpdateInput>
}

/**
 * TeamPerformanceStat delete
 */
export type TeamPerformanceStatDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TeamPerformanceStat
   */
  select?: Prisma.TeamPerformanceStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TeamPerformanceStat
   */
  omit?: Prisma.TeamPerformanceStatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TeamPerformanceStatInclude<ExtArgs> | null
  /**
   * Filter which TeamPerformanceStat to delete.
   */
  where: Prisma.TeamPerformanceStatWhereUniqueInput
}

/**
 * TeamPerformanceStat deleteMany
 */
export type TeamPerformanceStatDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TeamPerformanceStats to delete
   */
  where?: Prisma.TeamPerformanceStatWhereInput
  /**
   * Limit how many TeamPerformanceStats to delete.
   */
  limit?: number
}

/**
 * TeamPerformanceStat without action
 */
export type TeamPerformanceStatDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TeamPerformanceStat
   */
  select?: Prisma.TeamPerformanceStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TeamPerformanceStat
   */
  omit?: Prisma.TeamPerformanceStatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TeamPerformanceStatInclude<ExtArgs> | null
}
