
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TeamStreakStat` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model TeamStreakStat
 * 
 */
export type TeamStreakStatModel = runtime.Types.Result.DefaultSelection<Prisma.$TeamStreakStatPayload>

export type AggregateTeamStreakStat = {
  _count: TeamStreakStatCountAggregateOutputType | null
  _avg: TeamStreakStatAvgAggregateOutputType | null
  _sum: TeamStreakStatSumAggregateOutputType | null
  _min: TeamStreakStatMinAggregateOutputType | null
  _max: TeamStreakStatMaxAggregateOutputType | null
}

export type TeamStreakStatAvgAggregateOutputType = {
  id: number | null
  tournamentId: number | null
  teamId: number | null
  rank: number | null
  streakCount: number | null
  matchesPlayed: number | null
  viewTypeId: number | null
}

export type TeamStreakStatSumAggregateOutputType = {
  id: number | null
  tournamentId: number | null
  teamId: number | null
  rank: number | null
  streakCount: number | null
  matchesPlayed: number | null
  viewTypeId: number | null
}

export type TeamStreakStatMinAggregateOutputType = {
  id: number | null
  tournamentId: number | null
  teamId: number | null
  streakType: string | null
  scope: string | null
  rank: number | null
  streakCount: number | null
  matchesPlayed: number | null
  createdAt: Date | null
  updatedAt: Date | null
  mode: string | null
  viewTypeId: number | null
}

export type TeamStreakStatMaxAggregateOutputType = {
  id: number | null
  tournamentId: number | null
  teamId: number | null
  streakType: string | null
  scope: string | null
  rank: number | null
  streakCount: number | null
  matchesPlayed: number | null
  createdAt: Date | null
  updatedAt: Date | null
  mode: string | null
  viewTypeId: number | null
}

export type TeamStreakStatCountAggregateOutputType = {
  id: number
  tournamentId: number
  teamId: number
  streakType: number
  scope: number
  rank: number
  streakCount: number
  matchesPlayed: number
  createdAt: number
  updatedAt: number
  mode: number
  viewTypeId: number
  _all: number
}


export type TeamStreakStatAvgAggregateInputType = {
  id?: true
  tournamentId?: true
  teamId?: true
  rank?: true
  streakCount?: true
  matchesPlayed?: true
  viewTypeId?: true
}

export type TeamStreakStatSumAggregateInputType = {
  id?: true
  tournamentId?: true
  teamId?: true
  rank?: true
  streakCount?: true
  matchesPlayed?: true
  viewTypeId?: true
}

export type TeamStreakStatMinAggregateInputType = {
  id?: true
  tournamentId?: true
  teamId?: true
  streakType?: true
  scope?: true
  rank?: true
  streakCount?: true
  matchesPlayed?: true
  createdAt?: true
  updatedAt?: true
  mode?: true
  viewTypeId?: true
}

export type TeamStreakStatMaxAggregateInputType = {
  id?: true
  tournamentId?: true
  teamId?: true
  streakType?: true
  scope?: true
  rank?: true
  streakCount?: true
  matchesPlayed?: true
  createdAt?: true
  updatedAt?: true
  mode?: true
  viewTypeId?: true
}

export type TeamStreakStatCountAggregateInputType = {
  id?: true
  tournamentId?: true
  teamId?: true
  streakType?: true
  scope?: true
  rank?: true
  streakCount?: true
  matchesPlayed?: true
  createdAt?: true
  updatedAt?: true
  mode?: true
  viewTypeId?: true
  _all?: true
}

export type TeamStreakStatAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TeamStreakStat to aggregate.
   */
  where?: Prisma.TeamStreakStatWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TeamStreakStats to fetch.
   */
  orderBy?: Prisma.TeamStreakStatOrderByWithRelationInput | Prisma.TeamStreakStatOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TeamStreakStatWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TeamStreakStats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TeamStreakStats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TeamStreakStats
  **/
  _count?: true | TeamStreakStatCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TeamStreakStatAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TeamStreakStatSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TeamStreakStatMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TeamStreakStatMaxAggregateInputType
}

export type GetTeamStreakStatAggregateType<T extends TeamStreakStatAggregateArgs> = {
      [P in keyof T & keyof AggregateTeamStreakStat]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTeamStreakStat[P]>
    : Prisma.GetScalarType<T[P], AggregateTeamStreakStat[P]>
}




export type TeamStreakStatGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TeamStreakStatWhereInput
  orderBy?: Prisma.TeamStreakStatOrderByWithAggregationInput | Prisma.TeamStreakStatOrderByWithAggregationInput[]
  by: Prisma.TeamStreakStatScalarFieldEnum[] | Prisma.TeamStreakStatScalarFieldEnum
  having?: Prisma.TeamStreakStatScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TeamStreakStatCountAggregateInputType | true
  _avg?: TeamStreakStatAvgAggregateInputType
  _sum?: TeamStreakStatSumAggregateInputType
  _min?: TeamStreakStatMinAggregateInputType
  _max?: TeamStreakStatMaxAggregateInputType
}

export type TeamStreakStatGroupByOutputType = {
  id: number
  tournamentId: number
  teamId: number
  streakType: string
  scope: string
  rank: number
  streakCount: number
  matchesPlayed: number
  createdAt: Date
  updatedAt: Date
  mode: string
  viewTypeId: number
  _count: TeamStreakStatCountAggregateOutputType | null
  _avg: TeamStreakStatAvgAggregateOutputType | null
  _sum: TeamStreakStatSumAggregateOutputType | null
  _min: TeamStreakStatMinAggregateOutputType | null
  _max: TeamStreakStatMaxAggregateOutputType | null
}

type GetTeamStreakStatGroupByPayload<T extends TeamStreakStatGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TeamStreakStatGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TeamStreakStatGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TeamStreakStatGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TeamStreakStatGroupByOutputType[P]>
      }
    >
  >



export type TeamStreakStatWhereInput = {
  AND?: Prisma.TeamStreakStatWhereInput | Prisma.TeamStreakStatWhereInput[]
  OR?: Prisma.TeamStreakStatWhereInput[]
  NOT?: Prisma.TeamStreakStatWhereInput | Prisma.TeamStreakStatWhereInput[]
  id?: Prisma.IntFilter<"TeamStreakStat"> | number
  tournamentId?: Prisma.IntFilter<"TeamStreakStat"> | number
  teamId?: Prisma.IntFilter<"TeamStreakStat"> | number
  streakType?: Prisma.StringFilter<"TeamStreakStat"> | string
  scope?: Prisma.StringFilter<"TeamStreakStat"> | string
  rank?: Prisma.IntFilter<"TeamStreakStat"> | number
  streakCount?: Prisma.IntFilter<"TeamStreakStat"> | number
  matchesPlayed?: Prisma.IntFilter<"TeamStreakStat"> | number
  createdAt?: Prisma.DateTimeFilter<"TeamStreakStat"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TeamStreakStat"> | Date | string
  mode?: Prisma.StringFilter<"TeamStreakStat"> | string
  viewTypeId?: Prisma.IntFilter<"TeamStreakStat"> | number
  Team?: Prisma.XOR<Prisma.TeamScalarRelationFilter, Prisma.TeamWhereInput>
  Tournament?: Prisma.XOR<Prisma.TournamentScalarRelationFilter, Prisma.TournamentWhereInput>
  TableType?: Prisma.XOR<Prisma.TableTypeScalarRelationFilter, Prisma.TableTypeWhereInput>
}

export type TeamStreakStatOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  tournamentId?: Prisma.SortOrder
  teamId?: Prisma.SortOrder
  streakType?: Prisma.SortOrder
  scope?: Prisma.SortOrder
  rank?: Prisma.SortOrder
  streakCount?: Prisma.SortOrder
  matchesPlayed?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  mode?: Prisma.SortOrder
  viewTypeId?: Prisma.SortOrder
  Team?: Prisma.TeamOrderByWithRelationInput
  Tournament?: Prisma.TournamentOrderByWithRelationInput
  TableType?: Prisma.TableTypeOrderByWithRelationInput
}

export type TeamStreakStatWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  tournamentId_teamId_streakType_mode_scope_viewTypeId?: Prisma.TeamStreakStatTournamentIdTeamIdStreakTypeModeScopeViewTypeIdCompoundUniqueInput
  AND?: Prisma.TeamStreakStatWhereInput | Prisma.TeamStreakStatWhereInput[]
  OR?: Prisma.TeamStreakStatWhereInput[]
  NOT?: Prisma.TeamStreakStatWhereInput | Prisma.TeamStreakStatWhereInput[]
  tournamentId?: Prisma.IntFilter<"TeamStreakStat"> | number
  teamId?: Prisma.IntFilter<"TeamStreakStat"> | number
  streakType?: Prisma.StringFilter<"TeamStreakStat"> | string
  scope?: Prisma.StringFilter<"TeamStreakStat"> | string
  rank?: Prisma.IntFilter<"TeamStreakStat"> | number
  streakCount?: Prisma.IntFilter<"TeamStreakStat"> | number
  matchesPlayed?: Prisma.IntFilter<"TeamStreakStat"> | number
  createdAt?: Prisma.DateTimeFilter<"TeamStreakStat"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TeamStreakStat"> | Date | string
  mode?: Prisma.StringFilter<"TeamStreakStat"> | string
  viewTypeId?: Prisma.IntFilter<"TeamStreakStat"> | number
  Team?: Prisma.XOR<Prisma.TeamScalarRelationFilter, Prisma.TeamWhereInput>
  Tournament?: Prisma.XOR<Prisma.TournamentScalarRelationFilter, Prisma.TournamentWhereInput>
  TableType?: Prisma.XOR<Prisma.TableTypeScalarRelationFilter, Prisma.TableTypeWhereInput>
}, "id" | "tournamentId_teamId_streakType_mode_scope_viewTypeId">

export type TeamStreakStatOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  tournamentId?: Prisma.SortOrder
  teamId?: Prisma.SortOrder
  streakType?: Prisma.SortOrder
  scope?: Prisma.SortOrder
  rank?: Prisma.SortOrder
  streakCount?: Prisma.SortOrder
  matchesPlayed?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  mode?: Prisma.SortOrder
  viewTypeId?: Prisma.SortOrder
  _count?: Prisma.TeamStreakStatCountOrderByAggregateInput
  _avg?: Prisma.TeamStreakStatAvgOrderByAggregateInput
  _max?: Prisma.TeamStreakStatMaxOrderByAggregateInput
  _min?: Prisma.TeamStreakStatMinOrderByAggregateInput
  _sum?: Prisma.TeamStreakStatSumOrderByAggregateInput
}

export type TeamStreakStatScalarWhereWithAggregatesInput = {
  AND?: Prisma.TeamStreakStatScalarWhereWithAggregatesInput | Prisma.TeamStreakStatScalarWhereWithAggregatesInput[]
  OR?: Prisma.TeamStreakStatScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TeamStreakStatScalarWhereWithAggregatesInput | Prisma.TeamStreakStatScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"TeamStreakStat"> | number
  tournamentId?: Prisma.IntWithAggregatesFilter<"TeamStreakStat"> | number
  teamId?: Prisma.IntWithAggregatesFilter<"TeamStreakStat"> | number
  streakType?: Prisma.StringWithAggregatesFilter<"TeamStreakStat"> | string
  scope?: Prisma.StringWithAggregatesFilter<"TeamStreakStat"> | string
  rank?: Prisma.IntWithAggregatesFilter<"TeamStreakStat"> | number
  streakCount?: Prisma.IntWithAggregatesFilter<"TeamStreakStat"> | number
  matchesPlayed?: Prisma.IntWithAggregatesFilter<"TeamStreakStat"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"TeamStreakStat"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"TeamStreakStat"> | Date | string
  mode?: Prisma.StringWithAggregatesFilter<"TeamStreakStat"> | string
  viewTypeId?: Prisma.IntWithAggregatesFilter<"TeamStreakStat"> | number
}

export type TeamStreakStatCreateInput = {
  streakType: string
  scope?: string
  rank: number
  streakCount: number
  matchesPlayed: number
  createdAt?: Date | string
  updatedAt: Date | string
  mode?: string
  Team: Prisma.TeamCreateNestedOneWithoutTeamStreakStatInput
  Tournament: Prisma.TournamentCreateNestedOneWithoutTeamStreakStatInput
  TableType: Prisma.TableTypeCreateNestedOneWithoutTeamStreakStatInput
}

export type TeamStreakStatUncheckedCreateInput = {
  id?: number
  tournamentId: number
  teamId: number
  streakType: string
  scope?: string
  rank: number
  streakCount: number
  matchesPlayed: number
  createdAt?: Date | string
  updatedAt: Date | string
  mode?: string
  viewTypeId: number
}

export type TeamStreakStatUpdateInput = {
  streakType?: Prisma.StringFieldUpdateOperationsInput | string
  scope?: Prisma.StringFieldUpdateOperationsInput | string
  rank?: Prisma.IntFieldUpdateOperationsInput | number
  streakCount?: Prisma.IntFieldUpdateOperationsInput | number
  matchesPlayed?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mode?: Prisma.StringFieldUpdateOperationsInput | string
  Team?: Prisma.TeamUpdateOneRequiredWithoutTeamStreakStatNestedInput
  Tournament?: Prisma.TournamentUpdateOneRequiredWithoutTeamStreakStatNestedInput
  TableType?: Prisma.TableTypeUpdateOneRequiredWithoutTeamStreakStatNestedInput
}

export type TeamStreakStatUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  tournamentId?: Prisma.IntFieldUpdateOperationsInput | number
  teamId?: Prisma.IntFieldUpdateOperationsInput | number
  streakType?: Prisma.StringFieldUpdateOperationsInput | string
  scope?: Prisma.StringFieldUpdateOperationsInput | string
  rank?: Prisma.IntFieldUpdateOperationsInput | number
  streakCount?: Prisma.IntFieldUpdateOperationsInput | number
  matchesPlayed?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mode?: Prisma.StringFieldUpdateOperationsInput | string
  viewTypeId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type TeamStreakStatCreateManyInput = {
  id?: number
  tournamentId: number
  teamId: number
  streakType: string
  scope?: string
  rank: number
  streakCount: number
  matchesPlayed: number
  createdAt?: Date | string
  updatedAt: Date | string
  mode?: string
  viewTypeId: number
}

export type TeamStreakStatUpdateManyMutationInput = {
  streakType?: Prisma.StringFieldUpdateOperationsInput | string
  scope?: Prisma.StringFieldUpdateOperationsInput | string
  rank?: Prisma.IntFieldUpdateOperationsInput | number
  streakCount?: Prisma.IntFieldUpdateOperationsInput | number
  matchesPlayed?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mode?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TeamStreakStatUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  tournamentId?: Prisma.IntFieldUpdateOperationsInput | number
  teamId?: Prisma.IntFieldUpdateOperationsInput | number
  streakType?: Prisma.StringFieldUpdateOperationsInput | string
  scope?: Prisma.StringFieldUpdateOperationsInput | string
  rank?: Prisma.IntFieldUpdateOperationsInput | number
  streakCount?: Prisma.IntFieldUpdateOperationsInput | number
  matchesPlayed?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mode?: Prisma.StringFieldUpdateOperationsInput | string
  viewTypeId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type TeamStreakStatListRelationFilter = {
  every?: Prisma.TeamStreakStatWhereInput
  some?: Prisma.TeamStreakStatWhereInput
  none?: Prisma.TeamStreakStatWhereInput
}

export type TeamStreakStatOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TeamStreakStatTournamentIdTeamIdStreakTypeModeScopeViewTypeIdCompoundUniqueInput = {
  tournamentId: number
  teamId: number
  streakType: string
  mode: string
  scope: string
  viewTypeId: number
}

export type TeamStreakStatCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tournamentId?: Prisma.SortOrder
  teamId?: Prisma.SortOrder
  streakType?: Prisma.SortOrder
  scope?: Prisma.SortOrder
  rank?: Prisma.SortOrder
  streakCount?: Prisma.SortOrder
  matchesPlayed?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  mode?: Prisma.SortOrder
  viewTypeId?: Prisma.SortOrder
}

export type TeamStreakStatAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tournamentId?: Prisma.SortOrder
  teamId?: Prisma.SortOrder
  rank?: Prisma.SortOrder
  streakCount?: Prisma.SortOrder
  matchesPlayed?: Prisma.SortOrder
  viewTypeId?: Prisma.SortOrder
}

export type TeamStreakStatMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tournamentId?: Prisma.SortOrder
  teamId?: Prisma.SortOrder
  streakType?: Prisma.SortOrder
  scope?: Prisma.SortOrder
  rank?: Prisma.SortOrder
  streakCount?: Prisma.SortOrder
  matchesPlayed?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  mode?: Prisma.SortOrder
  viewTypeId?: Prisma.SortOrder
}

export type TeamStreakStatMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tournamentId?: Prisma.SortOrder
  teamId?: Prisma.SortOrder
  streakType?: Prisma.SortOrder
  scope?: Prisma.SortOrder
  rank?: Prisma.SortOrder
  streakCount?: Prisma.SortOrder
  matchesPlayed?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  mode?: Prisma.SortOrder
  viewTypeId?: Prisma.SortOrder
}

export type TeamStreakStatSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tournamentId?: Prisma.SortOrder
  teamId?: Prisma.SortOrder
  rank?: Prisma.SortOrder
  streakCount?: Prisma.SortOrder
  matchesPlayed?: Prisma.SortOrder
  viewTypeId?: Prisma.SortOrder
}

export type TeamStreakStatCreateNestedManyWithoutTableTypeInput = {
  create?: Prisma.XOR<Prisma.TeamStreakStatCreateWithoutTableTypeInput, Prisma.TeamStreakStatUncheckedCreateWithoutTableTypeInput> | Prisma.TeamStreakStatCreateWithoutTableTypeInput[] | Prisma.TeamStreakStatUncheckedCreateWithoutTableTypeInput[]
  connectOrCreate?: Prisma.TeamStreakStatCreateOrConnectWithoutTableTypeInput | Prisma.TeamStreakStatCreateOrConnectWithoutTableTypeInput[]
  createMany?: Prisma.TeamStreakStatCreateManyTableTypeInputEnvelope
  connect?: Prisma.TeamStreakStatWhereUniqueInput | Prisma.TeamStreakStatWhereUniqueInput[]
}

export type TeamStreakStatUncheckedCreateNestedManyWithoutTableTypeInput = {
  create?: Prisma.XOR<Prisma.TeamStreakStatCreateWithoutTableTypeInput, Prisma.TeamStreakStatUncheckedCreateWithoutTableTypeInput> | Prisma.TeamStreakStatCreateWithoutTableTypeInput[] | Prisma.TeamStreakStatUncheckedCreateWithoutTableTypeInput[]
  connectOrCreate?: Prisma.TeamStreakStatCreateOrConnectWithoutTableTypeInput | Prisma.TeamStreakStatCreateOrConnectWithoutTableTypeInput[]
  createMany?: Prisma.TeamStreakStatCreateManyTableTypeInputEnvelope
  connect?: Prisma.TeamStreakStatWhereUniqueInput | Prisma.TeamStreakStatWhereUniqueInput[]
}

export type TeamStreakStatUpdateManyWithoutTableTypeNestedInput = {
  create?: Prisma.XOR<Prisma.TeamStreakStatCreateWithoutTableTypeInput, Prisma.TeamStreakStatUncheckedCreateWithoutTableTypeInput> | Prisma.TeamStreakStatCreateWithoutTableTypeInput[] | Prisma.TeamStreakStatUncheckedCreateWithoutTableTypeInput[]
  connectOrCreate?: Prisma.TeamStreakStatCreateOrConnectWithoutTableTypeInput | Prisma.TeamStreakStatCreateOrConnectWithoutTableTypeInput[]
  upsert?: Prisma.TeamStreakStatUpsertWithWhereUniqueWithoutTableTypeInput | Prisma.TeamStreakStatUpsertWithWhereUniqueWithoutTableTypeInput[]
  createMany?: Prisma.TeamStreakStatCreateManyTableTypeInputEnvelope
  set?: Prisma.TeamStreakStatWhereUniqueInput | Prisma.TeamStreakStatWhereUniqueInput[]
  disconnect?: Prisma.TeamStreakStatWhereUniqueInput | Prisma.TeamStreakStatWhereUniqueInput[]
  delete?: Prisma.TeamStreakStatWhereUniqueInput | Prisma.TeamStreakStatWhereUniqueInput[]
  connect?: Prisma.TeamStreakStatWhereUniqueInput | Prisma.TeamStreakStatWhereUniqueInput[]
  update?: Prisma.TeamStreakStatUpdateWithWhereUniqueWithoutTableTypeInput | Prisma.TeamStreakStatUpdateWithWhereUniqueWithoutTableTypeInput[]
  updateMany?: Prisma.TeamStreakStatUpdateManyWithWhereWithoutTableTypeInput | Prisma.TeamStreakStatUpdateManyWithWhereWithoutTableTypeInput[]
  deleteMany?: Prisma.TeamStreakStatScalarWhereInput | Prisma.TeamStreakStatScalarWhereInput[]
}

export type TeamStreakStatUncheckedUpdateManyWithoutTableTypeNestedInput = {
  create?: Prisma.XOR<Prisma.TeamStreakStatCreateWithoutTableTypeInput, Prisma.TeamStreakStatUncheckedCreateWithoutTableTypeInput> | Prisma.TeamStreakStatCreateWithoutTableTypeInput[] | Prisma.TeamStreakStatUncheckedCreateWithoutTableTypeInput[]
  connectOrCreate?: Prisma.TeamStreakStatCreateOrConnectWithoutTableTypeInput | Prisma.TeamStreakStatCreateOrConnectWithoutTableTypeInput[]
  upsert?: Prisma.TeamStreakStatUpsertWithWhereUniqueWithoutTableTypeInput | Prisma.TeamStreakStatUpsertWithWhereUniqueWithoutTableTypeInput[]
  createMany?: Prisma.TeamStreakStatCreateManyTableTypeInputEnvelope
  set?: Prisma.TeamStreakStatWhereUniqueInput | Prisma.TeamStreakStatWhereUniqueInput[]
  disconnect?: Prisma.TeamStreakStatWhereUniqueInput | Prisma.TeamStreakStatWhereUniqueInput[]
  delete?: Prisma.TeamStreakStatWhereUniqueInput | Prisma.TeamStreakStatWhereUniqueInput[]
  connect?: Prisma.TeamStreakStatWhereUniqueInput | Prisma.TeamStreakStatWhereUniqueInput[]
  update?: Prisma.TeamStreakStatUpdateWithWhereUniqueWithoutTableTypeInput | Prisma.TeamStreakStatUpdateWithWhereUniqueWithoutTableTypeInput[]
  updateMany?: Prisma.TeamStreakStatUpdateManyWithWhereWithoutTableTypeInput | Prisma.TeamStreakStatUpdateManyWithWhereWithoutTableTypeInput[]
  deleteMany?: Prisma.TeamStreakStatScalarWhereInput | Prisma.TeamStreakStatScalarWhereInput[]
}

export type TeamStreakStatCreateNestedManyWithoutTeamInput = {
  create?: Prisma.XOR<Prisma.TeamStreakStatCreateWithoutTeamInput, Prisma.TeamStreakStatUncheckedCreateWithoutTeamInput> | Prisma.TeamStreakStatCreateWithoutTeamInput[] | Prisma.TeamStreakStatUncheckedCreateWithoutTeamInput[]
  connectOrCreate?: Prisma.TeamStreakStatCreateOrConnectWithoutTeamInput | Prisma.TeamStreakStatCreateOrConnectWithoutTeamInput[]
  createMany?: Prisma.TeamStreakStatCreateManyTeamInputEnvelope
  connect?: Prisma.TeamStreakStatWhereUniqueInput | Prisma.TeamStreakStatWhereUniqueInput[]
}

export type TeamStreakStatUncheckedCreateNestedManyWithoutTeamInput = {
  create?: Prisma.XOR<Prisma.TeamStreakStatCreateWithoutTeamInput, Prisma.TeamStreakStatUncheckedCreateWithoutTeamInput> | Prisma.TeamStreakStatCreateWithoutTeamInput[] | Prisma.TeamStreakStatUncheckedCreateWithoutTeamInput[]
  connectOrCreate?: Prisma.TeamStreakStatCreateOrConnectWithoutTeamInput | Prisma.TeamStreakStatCreateOrConnectWithoutTeamInput[]
  createMany?: Prisma.TeamStreakStatCreateManyTeamInputEnvelope
  connect?: Prisma.TeamStreakStatWhereUniqueInput | Prisma.TeamStreakStatWhereUniqueInput[]
}

export type TeamStreakStatUpdateManyWithoutTeamNestedInput = {
  create?: Prisma.XOR<Prisma.TeamStreakStatCreateWithoutTeamInput, Prisma.TeamStreakStatUncheckedCreateWithoutTeamInput> | Prisma.TeamStreakStatCreateWithoutTeamInput[] | Prisma.TeamStreakStatUncheckedCreateWithoutTeamInput[]
  connectOrCreate?: Prisma.TeamStreakStatCreateOrConnectWithoutTeamInput | Prisma.TeamStreakStatCreateOrConnectWithoutTeamInput[]
  upsert?: Prisma.TeamStreakStatUpsertWithWhereUniqueWithoutTeamInput | Prisma.TeamStreakStatUpsertWithWhereUniqueWithoutTeamInput[]
  createMany?: Prisma.TeamStreakStatCreateManyTeamInputEnvelope
  set?: Prisma.TeamStreakStatWhereUniqueInput | Prisma.TeamStreakStatWhereUniqueInput[]
  disconnect?: Prisma.TeamStreakStatWhereUniqueInput | Prisma.TeamStreakStatWhereUniqueInput[]
  delete?: Prisma.TeamStreakStatWhereUniqueInput | Prisma.TeamStreakStatWhereUniqueInput[]
  connect?: Prisma.TeamStreakStatWhereUniqueInput | Prisma.TeamStreakStatWhereUniqueInput[]
  update?: Prisma.TeamStreakStatUpdateWithWhereUniqueWithoutTeamInput | Prisma.TeamStreakStatUpdateWithWhereUniqueWithoutTeamInput[]
  updateMany?: Prisma.TeamStreakStatUpdateManyWithWhereWithoutTeamInput | Prisma.TeamStreakStatUpdateManyWithWhereWithoutTeamInput[]
  deleteMany?: Prisma.TeamStreakStatScalarWhereInput | Prisma.TeamStreakStatScalarWhereInput[]
}

export type TeamStreakStatUncheckedUpdateManyWithoutTeamNestedInput = {
  create?: Prisma.XOR<Prisma.TeamStreakStatCreateWithoutTeamInput, Prisma.TeamStreakStatUncheckedCreateWithoutTeamInput> | Prisma.TeamStreakStatCreateWithoutTeamInput[] | Prisma.TeamStreakStatUncheckedCreateWithoutTeamInput[]
  connectOrCreate?: Prisma.TeamStreakStatCreateOrConnectWithoutTeamInput | Prisma.TeamStreakStatCreateOrConnectWithoutTeamInput[]
  upsert?: Prisma.TeamStreakStatUpsertWithWhereUniqueWithoutTeamInput | Prisma.TeamStreakStatUpsertWithWhereUniqueWithoutTeamInput[]
  createMany?: Prisma.TeamStreakStatCreateManyTeamInputEnvelope
  set?: Prisma.TeamStreakStatWhereUniqueInput | Prisma.TeamStreakStatWhereUniqueInput[]
  disconnect?: Prisma.TeamStreakStatWhereUniqueInput | Prisma.TeamStreakStatWhereUniqueInput[]
  delete?: Prisma.TeamStreakStatWhereUniqueInput | Prisma.TeamStreakStatWhereUniqueInput[]
  connect?: Prisma.TeamStreakStatWhereUniqueInput | Prisma.TeamStreakStatWhereUniqueInput[]
  update?: Prisma.TeamStreakStatUpdateWithWhereUniqueWithoutTeamInput | Prisma.TeamStreakStatUpdateWithWhereUniqueWithoutTeamInput[]
  updateMany?: Prisma.TeamStreakStatUpdateManyWithWhereWithoutTeamInput | Prisma.TeamStreakStatUpdateManyWithWhereWithoutTeamInput[]
  deleteMany?: Prisma.TeamStreakStatScalarWhereInput | Prisma.TeamStreakStatScalarWhereInput[]
}

export type TeamStreakStatCreateNestedManyWithoutTournamentInput = {
  create?: Prisma.XOR<Prisma.TeamStreakStatCreateWithoutTournamentInput, Prisma.TeamStreakStatUncheckedCreateWithoutTournamentInput> | Prisma.TeamStreakStatCreateWithoutTournamentInput[] | Prisma.TeamStreakStatUncheckedCreateWithoutTournamentInput[]
  connectOrCreate?: Prisma.TeamStreakStatCreateOrConnectWithoutTournamentInput | Prisma.TeamStreakStatCreateOrConnectWithoutTournamentInput[]
  createMany?: Prisma.TeamStreakStatCreateManyTournamentInputEnvelope
  connect?: Prisma.TeamStreakStatWhereUniqueInput | Prisma.TeamStreakStatWhereUniqueInput[]
}

export type TeamStreakStatUncheckedCreateNestedManyWithoutTournamentInput = {
  create?: Prisma.XOR<Prisma.TeamStreakStatCreateWithoutTournamentInput, Prisma.TeamStreakStatUncheckedCreateWithoutTournamentInput> | Prisma.TeamStreakStatCreateWithoutTournamentInput[] | Prisma.TeamStreakStatUncheckedCreateWithoutTournamentInput[]
  connectOrCreate?: Prisma.TeamStreakStatCreateOrConnectWithoutTournamentInput | Prisma.TeamStreakStatCreateOrConnectWithoutTournamentInput[]
  createMany?: Prisma.TeamStreakStatCreateManyTournamentInputEnvelope
  connect?: Prisma.TeamStreakStatWhereUniqueInput | Prisma.TeamStreakStatWhereUniqueInput[]
}

export type TeamStreakStatUpdateManyWithoutTournamentNestedInput = {
  create?: Prisma.XOR<Prisma.TeamStreakStatCreateWithoutTournamentInput, Prisma.TeamStreakStatUncheckedCreateWithoutTournamentInput> | Prisma.TeamStreakStatCreateWithoutTournamentInput[] | Prisma.TeamStreakStatUncheckedCreateWithoutTournamentInput[]
  connectOrCreate?: Prisma.TeamStreakStatCreateOrConnectWithoutTournamentInput | Prisma.TeamStreakStatCreateOrConnectWithoutTournamentInput[]
  upsert?: Prisma.TeamStreakStatUpsertWithWhereUniqueWithoutTournamentInput | Prisma.TeamStreakStatUpsertWithWhereUniqueWithoutTournamentInput[]
  createMany?: Prisma.TeamStreakStatCreateManyTournamentInputEnvelope
  set?: Prisma.TeamStreakStatWhereUniqueInput | Prisma.TeamStreakStatWhereUniqueInput[]
  disconnect?: Prisma.TeamStreakStatWhereUniqueInput | Prisma.TeamStreakStatWhereUniqueInput[]
  delete?: Prisma.TeamStreakStatWhereUniqueInput | Prisma.TeamStreakStatWhereUniqueInput[]
  connect?: Prisma.TeamStreakStatWhereUniqueInput | Prisma.TeamStreakStatWhereUniqueInput[]
  update?: Prisma.TeamStreakStatUpdateWithWhereUniqueWithoutTournamentInput | Prisma.TeamStreakStatUpdateWithWhereUniqueWithoutTournamentInput[]
  updateMany?: Prisma.TeamStreakStatUpdateManyWithWhereWithoutTournamentInput | Prisma.TeamStreakStatUpdateManyWithWhereWithoutTournamentInput[]
  deleteMany?: Prisma.TeamStreakStatScalarWhereInput | Prisma.TeamStreakStatScalarWhereInput[]
}

export type TeamStreakStatUncheckedUpdateManyWithoutTournamentNestedInput = {
  create?: Prisma.XOR<Prisma.TeamStreakStatCreateWithoutTournamentInput, Prisma.TeamStreakStatUncheckedCreateWithoutTournamentInput> | Prisma.TeamStreakStatCreateWithoutTournamentInput[] | Prisma.TeamStreakStatUncheckedCreateWithoutTournamentInput[]
  connectOrCreate?: Prisma.TeamStreakStatCreateOrConnectWithoutTournamentInput | Prisma.TeamStreakStatCreateOrConnectWithoutTournamentInput[]
  upsert?: Prisma.TeamStreakStatUpsertWithWhereUniqueWithoutTournamentInput | Prisma.TeamStreakStatUpsertWithWhereUniqueWithoutTournamentInput[]
  createMany?: Prisma.TeamStreakStatCreateManyTournamentInputEnvelope
  set?: Prisma.TeamStreakStatWhereUniqueInput | Prisma.TeamStreakStatWhereUniqueInput[]
  disconnect?: Prisma.TeamStreakStatWhereUniqueInput | Prisma.TeamStreakStatWhereUniqueInput[]
  delete?: Prisma.TeamStreakStatWhereUniqueInput | Prisma.TeamStreakStatWhereUniqueInput[]
  connect?: Prisma.TeamStreakStatWhereUniqueInput | Prisma.TeamStreakStatWhereUniqueInput[]
  update?: Prisma.TeamStreakStatUpdateWithWhereUniqueWithoutTournamentInput | Prisma.TeamStreakStatUpdateWithWhereUniqueWithoutTournamentInput[]
  updateMany?: Prisma.TeamStreakStatUpdateManyWithWhereWithoutTournamentInput | Prisma.TeamStreakStatUpdateManyWithWhereWithoutTournamentInput[]
  deleteMany?: Prisma.TeamStreakStatScalarWhereInput | Prisma.TeamStreakStatScalarWhereInput[]
}

export type TeamStreakStatCreateWithoutTableTypeInput = {
  streakType: string
  scope?: string
  rank: number
  streakCount: number
  matchesPlayed: number
  createdAt?: Date | string
  updatedAt: Date | string
  mode?: string
  Team: Prisma.TeamCreateNestedOneWithoutTeamStreakStatInput
  Tournament: Prisma.TournamentCreateNestedOneWithoutTeamStreakStatInput
}

export type TeamStreakStatUncheckedCreateWithoutTableTypeInput = {
  id?: number
  tournamentId: number
  teamId: number
  streakType: string
  scope?: string
  rank: number
  streakCount: number
  matchesPlayed: number
  createdAt?: Date | string
  updatedAt: Date | string
  mode?: string
}

export type TeamStreakStatCreateOrConnectWithoutTableTypeInput = {
  where: Prisma.TeamStreakStatWhereUniqueInput
  create: Prisma.XOR<Prisma.TeamStreakStatCreateWithoutTableTypeInput, Prisma.TeamStreakStatUncheckedCreateWithoutTableTypeInput>
}

export type TeamStreakStatCreateManyTableTypeInputEnvelope = {
  data: Prisma.TeamStreakStatCreateManyTableTypeInput | Prisma.TeamStreakStatCreateManyTableTypeInput[]
  skipDuplicates?: boolean
}

export type TeamStreakStatUpsertWithWhereUniqueWithoutTableTypeInput = {
  where: Prisma.TeamStreakStatWhereUniqueInput
  update: Prisma.XOR<Prisma.TeamStreakStatUpdateWithoutTableTypeInput, Prisma.TeamStreakStatUncheckedUpdateWithoutTableTypeInput>
  create: Prisma.XOR<Prisma.TeamStreakStatCreateWithoutTableTypeInput, Prisma.TeamStreakStatUncheckedCreateWithoutTableTypeInput>
}

export type TeamStreakStatUpdateWithWhereUniqueWithoutTableTypeInput = {
  where: Prisma.TeamStreakStatWhereUniqueInput
  data: Prisma.XOR<Prisma.TeamStreakStatUpdateWithoutTableTypeInput, Prisma.TeamStreakStatUncheckedUpdateWithoutTableTypeInput>
}

export type TeamStreakStatUpdateManyWithWhereWithoutTableTypeInput = {
  where: Prisma.TeamStreakStatScalarWhereInput
  data: Prisma.XOR<Prisma.TeamStreakStatUpdateManyMutationInput, Prisma.TeamStreakStatUncheckedUpdateManyWithoutTableTypeInput>
}

export type TeamStreakStatScalarWhereInput = {
  AND?: Prisma.TeamStreakStatScalarWhereInput | Prisma.TeamStreakStatScalarWhereInput[]
  OR?: Prisma.TeamStreakStatScalarWhereInput[]
  NOT?: Prisma.TeamStreakStatScalarWhereInput | Prisma.TeamStreakStatScalarWhereInput[]
  id?: Prisma.IntFilter<"TeamStreakStat"> | number
  tournamentId?: Prisma.IntFilter<"TeamStreakStat"> | number
  teamId?: Prisma.IntFilter<"TeamStreakStat"> | number
  streakType?: Prisma.StringFilter<"TeamStreakStat"> | string
  scope?: Prisma.StringFilter<"TeamStreakStat"> | string
  rank?: Prisma.IntFilter<"TeamStreakStat"> | number
  streakCount?: Prisma.IntFilter<"TeamStreakStat"> | number
  matchesPlayed?: Prisma.IntFilter<"TeamStreakStat"> | number
  createdAt?: Prisma.DateTimeFilter<"TeamStreakStat"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TeamStreakStat"> | Date | string
  mode?: Prisma.StringFilter<"TeamStreakStat"> | string
  viewTypeId?: Prisma.IntFilter<"TeamStreakStat"> | number
}

export type TeamStreakStatCreateWithoutTeamInput = {
  streakType: string
  scope?: string
  rank: number
  streakCount: number
  matchesPlayed: number
  createdAt?: Date | string
  updatedAt: Date | string
  mode?: string
  Tournament: Prisma.TournamentCreateNestedOneWithoutTeamStreakStatInput
  TableType: Prisma.TableTypeCreateNestedOneWithoutTeamStreakStatInput
}

export type TeamStreakStatUncheckedCreateWithoutTeamInput = {
  id?: number
  tournamentId: number
  streakType: string
  scope?: string
  rank: number
  streakCount: number
  matchesPlayed: number
  createdAt?: Date | string
  updatedAt: Date | string
  mode?: string
  viewTypeId: number
}

export type TeamStreakStatCreateOrConnectWithoutTeamInput = {
  where: Prisma.TeamStreakStatWhereUniqueInput
  create: Prisma.XOR<Prisma.TeamStreakStatCreateWithoutTeamInput, Prisma.TeamStreakStatUncheckedCreateWithoutTeamInput>
}

export type TeamStreakStatCreateManyTeamInputEnvelope = {
  data: Prisma.TeamStreakStatCreateManyTeamInput | Prisma.TeamStreakStatCreateManyTeamInput[]
  skipDuplicates?: boolean
}

export type TeamStreakStatUpsertWithWhereUniqueWithoutTeamInput = {
  where: Prisma.TeamStreakStatWhereUniqueInput
  update: Prisma.XOR<Prisma.TeamStreakStatUpdateWithoutTeamInput, Prisma.TeamStreakStatUncheckedUpdateWithoutTeamInput>
  create: Prisma.XOR<Prisma.TeamStreakStatCreateWithoutTeamInput, Prisma.TeamStreakStatUncheckedCreateWithoutTeamInput>
}

export type TeamStreakStatUpdateWithWhereUniqueWithoutTeamInput = {
  where: Prisma.TeamStreakStatWhereUniqueInput
  data: Prisma.XOR<Prisma.TeamStreakStatUpdateWithoutTeamInput, Prisma.TeamStreakStatUncheckedUpdateWithoutTeamInput>
}

export type TeamStreakStatUpdateManyWithWhereWithoutTeamInput = {
  where: Prisma.TeamStreakStatScalarWhereInput
  data: Prisma.XOR<Prisma.TeamStreakStatUpdateManyMutationInput, Prisma.TeamStreakStatUncheckedUpdateManyWithoutTeamInput>
}

export type TeamStreakStatCreateWithoutTournamentInput = {
  streakType: string
  scope?: string
  rank: number
  streakCount: number
  matchesPlayed: number
  createdAt?: Date | string
  updatedAt: Date | string
  mode?: string
  Team: Prisma.TeamCreateNestedOneWithoutTeamStreakStatInput
  TableType: Prisma.TableTypeCreateNestedOneWithoutTeamStreakStatInput
}

export type TeamStreakStatUncheckedCreateWithoutTournamentInput = {
  id?: number
  teamId: number
  streakType: string
  scope?: string
  rank: number
  streakCount: number
  matchesPlayed: number
  createdAt?: Date | string
  updatedAt: Date | string
  mode?: string
  viewTypeId: number
}

export type TeamStreakStatCreateOrConnectWithoutTournamentInput = {
  where: Prisma.TeamStreakStatWhereUniqueInput
  create: Prisma.XOR<Prisma.TeamStreakStatCreateWithoutTournamentInput, Prisma.TeamStreakStatUncheckedCreateWithoutTournamentInput>
}

export type TeamStreakStatCreateManyTournamentInputEnvelope = {
  data: Prisma.TeamStreakStatCreateManyTournamentInput | Prisma.TeamStreakStatCreateManyTournamentInput[]
  skipDuplicates?: boolean
}

export type TeamStreakStatUpsertWithWhereUniqueWithoutTournamentInput = {
  where: Prisma.TeamStreakStatWhereUniqueInput
  update: Prisma.XOR<Prisma.TeamStreakStatUpdateWithoutTournamentInput, Prisma.TeamStreakStatUncheckedUpdateWithoutTournamentInput>
  create: Prisma.XOR<Prisma.TeamStreakStatCreateWithoutTournamentInput, Prisma.TeamStreakStatUncheckedCreateWithoutTournamentInput>
}

export type TeamStreakStatUpdateWithWhereUniqueWithoutTournamentInput = {
  where: Prisma.TeamStreakStatWhereUniqueInput
  data: Prisma.XOR<Prisma.TeamStreakStatUpdateWithoutTournamentInput, Prisma.TeamStreakStatUncheckedUpdateWithoutTournamentInput>
}

export type TeamStreakStatUpdateManyWithWhereWithoutTournamentInput = {
  where: Prisma.TeamStreakStatScalarWhereInput
  data: Prisma.XOR<Prisma.TeamStreakStatUpdateManyMutationInput, Prisma.TeamStreakStatUncheckedUpdateManyWithoutTournamentInput>
}

export type TeamStreakStatCreateManyTableTypeInput = {
  id?: number
  tournamentId: number
  teamId: number
  streakType: string
  scope?: string
  rank: number
  streakCount: number
  matchesPlayed: number
  createdAt?: Date | string
  updatedAt: Date | string
  mode?: string
}

export type TeamStreakStatUpdateWithoutTableTypeInput = {
  streakType?: Prisma.StringFieldUpdateOperationsInput | string
  scope?: Prisma.StringFieldUpdateOperationsInput | string
  rank?: Prisma.IntFieldUpdateOperationsInput | number
  streakCount?: Prisma.IntFieldUpdateOperationsInput | number
  matchesPlayed?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mode?: Prisma.StringFieldUpdateOperationsInput | string
  Team?: Prisma.TeamUpdateOneRequiredWithoutTeamStreakStatNestedInput
  Tournament?: Prisma.TournamentUpdateOneRequiredWithoutTeamStreakStatNestedInput
}

export type TeamStreakStatUncheckedUpdateWithoutTableTypeInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  tournamentId?: Prisma.IntFieldUpdateOperationsInput | number
  teamId?: Prisma.IntFieldUpdateOperationsInput | number
  streakType?: Prisma.StringFieldUpdateOperationsInput | string
  scope?: Prisma.StringFieldUpdateOperationsInput | string
  rank?: Prisma.IntFieldUpdateOperationsInput | number
  streakCount?: Prisma.IntFieldUpdateOperationsInput | number
  matchesPlayed?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mode?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TeamStreakStatUncheckedUpdateManyWithoutTableTypeInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  tournamentId?: Prisma.IntFieldUpdateOperationsInput | number
  teamId?: Prisma.IntFieldUpdateOperationsInput | number
  streakType?: Prisma.StringFieldUpdateOperationsInput | string
  scope?: Prisma.StringFieldUpdateOperationsInput | string
  rank?: Prisma.IntFieldUpdateOperationsInput | number
  streakCount?: Prisma.IntFieldUpdateOperationsInput | number
  matchesPlayed?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mode?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TeamStreakStatCreateManyTeamInput = {
  id?: number
  tournamentId: number
  streakType: string
  scope?: string
  rank: number
  streakCount: number
  matchesPlayed: number
  createdAt?: Date | string
  updatedAt: Date | string
  mode?: string
  viewTypeId: number
}

export type TeamStreakStatUpdateWithoutTeamInput = {
  streakType?: Prisma.StringFieldUpdateOperationsInput | string
  scope?: Prisma.StringFieldUpdateOperationsInput | string
  rank?: Prisma.IntFieldUpdateOperationsInput | number
  streakCount?: Prisma.IntFieldUpdateOperationsInput | number
  matchesPlayed?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mode?: Prisma.StringFieldUpdateOperationsInput | string
  Tournament?: Prisma.TournamentUpdateOneRequiredWithoutTeamStreakStatNestedInput
  TableType?: Prisma.TableTypeUpdateOneRequiredWithoutTeamStreakStatNestedInput
}

export type TeamStreakStatUncheckedUpdateWithoutTeamInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  tournamentId?: Prisma.IntFieldUpdateOperationsInput | number
  streakType?: Prisma.StringFieldUpdateOperationsInput | string
  scope?: Prisma.StringFieldUpdateOperationsInput | string
  rank?: Prisma.IntFieldUpdateOperationsInput | number
  streakCount?: Prisma.IntFieldUpdateOperationsInput | number
  matchesPlayed?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mode?: Prisma.StringFieldUpdateOperationsInput | string
  viewTypeId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type TeamStreakStatUncheckedUpdateManyWithoutTeamInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  tournamentId?: Prisma.IntFieldUpdateOperationsInput | number
  streakType?: Prisma.StringFieldUpdateOperationsInput | string
  scope?: Prisma.StringFieldUpdateOperationsInput | string
  rank?: Prisma.IntFieldUpdateOperationsInput | number
  streakCount?: Prisma.IntFieldUpdateOperationsInput | number
  matchesPlayed?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mode?: Prisma.StringFieldUpdateOperationsInput | string
  viewTypeId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type TeamStreakStatCreateManyTournamentInput = {
  id?: number
  teamId: number
  streakType: string
  scope?: string
  rank: number
  streakCount: number
  matchesPlayed: number
  createdAt?: Date | string
  updatedAt: Date | string
  mode?: string
  viewTypeId: number
}

export type TeamStreakStatUpdateWithoutTournamentInput = {
  streakType?: Prisma.StringFieldUpdateOperationsInput | string
  scope?: Prisma.StringFieldUpdateOperationsInput | string
  rank?: Prisma.IntFieldUpdateOperationsInput | number
  streakCount?: Prisma.IntFieldUpdateOperationsInput | number
  matchesPlayed?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mode?: Prisma.StringFieldUpdateOperationsInput | string
  Team?: Prisma.TeamUpdateOneRequiredWithoutTeamStreakStatNestedInput
  TableType?: Prisma.TableTypeUpdateOneRequiredWithoutTeamStreakStatNestedInput
}

export type TeamStreakStatUncheckedUpdateWithoutTournamentInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  teamId?: Prisma.IntFieldUpdateOperationsInput | number
  streakType?: Prisma.StringFieldUpdateOperationsInput | string
  scope?: Prisma.StringFieldUpdateOperationsInput | string
  rank?: Prisma.IntFieldUpdateOperationsInput | number
  streakCount?: Prisma.IntFieldUpdateOperationsInput | number
  matchesPlayed?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mode?: Prisma.StringFieldUpdateOperationsInput | string
  viewTypeId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type TeamStreakStatUncheckedUpdateManyWithoutTournamentInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  teamId?: Prisma.IntFieldUpdateOperationsInput | number
  streakType?: Prisma.StringFieldUpdateOperationsInput | string
  scope?: Prisma.StringFieldUpdateOperationsInput | string
  rank?: Prisma.IntFieldUpdateOperationsInput | number
  streakCount?: Prisma.IntFieldUpdateOperationsInput | number
  matchesPlayed?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mode?: Prisma.StringFieldUpdateOperationsInput | string
  viewTypeId?: Prisma.IntFieldUpdateOperationsInput | number
}



export type TeamStreakStatSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tournamentId?: boolean
  teamId?: boolean
  streakType?: boolean
  scope?: boolean
  rank?: boolean
  streakCount?: boolean
  matchesPlayed?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  mode?: boolean
  viewTypeId?: boolean
  Team?: boolean | Prisma.TeamDefaultArgs<ExtArgs>
  Tournament?: boolean | Prisma.TournamentDefaultArgs<ExtArgs>
  TableType?: boolean | Prisma.TableTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["teamStreakStat"]>

export type TeamStreakStatSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tournamentId?: boolean
  teamId?: boolean
  streakType?: boolean
  scope?: boolean
  rank?: boolean
  streakCount?: boolean
  matchesPlayed?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  mode?: boolean
  viewTypeId?: boolean
  Team?: boolean | Prisma.TeamDefaultArgs<ExtArgs>
  Tournament?: boolean | Prisma.TournamentDefaultArgs<ExtArgs>
  TableType?: boolean | Prisma.TableTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["teamStreakStat"]>

export type TeamStreakStatSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tournamentId?: boolean
  teamId?: boolean
  streakType?: boolean
  scope?: boolean
  rank?: boolean
  streakCount?: boolean
  matchesPlayed?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  mode?: boolean
  viewTypeId?: boolean
  Team?: boolean | Prisma.TeamDefaultArgs<ExtArgs>
  Tournament?: boolean | Prisma.TournamentDefaultArgs<ExtArgs>
  TableType?: boolean | Prisma.TableTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["teamStreakStat"]>

export type TeamStreakStatSelectScalar = {
  id?: boolean
  tournamentId?: boolean
  teamId?: boolean
  streakType?: boolean
  scope?: boolean
  rank?: boolean
  streakCount?: boolean
  matchesPlayed?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  mode?: boolean
  viewTypeId?: boolean
}

export type TeamStreakStatOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "tournamentId" | "teamId" | "streakType" | "scope" | "rank" | "streakCount" | "matchesPlayed" | "createdAt" | "updatedAt" | "mode" | "viewTypeId", ExtArgs["result"]["teamStreakStat"]>
export type TeamStreakStatInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Team?: boolean | Prisma.TeamDefaultArgs<ExtArgs>
  Tournament?: boolean | Prisma.TournamentDefaultArgs<ExtArgs>
  TableType?: boolean | Prisma.TableTypeDefaultArgs<ExtArgs>
}
export type TeamStreakStatIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Team?: boolean | Prisma.TeamDefaultArgs<ExtArgs>
  Tournament?: boolean | Prisma.TournamentDefaultArgs<ExtArgs>
  TableType?: boolean | Prisma.TableTypeDefaultArgs<ExtArgs>
}
export type TeamStreakStatIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Team?: boolean | Prisma.TeamDefaultArgs<ExtArgs>
  Tournament?: boolean | Prisma.TournamentDefaultArgs<ExtArgs>
  TableType?: boolean | Prisma.TableTypeDefaultArgs<ExtArgs>
}

export type $TeamStreakStatPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TeamStreakStat"
  objects: {
    Team: Prisma.$TeamPayload<ExtArgs>
    Tournament: Prisma.$TournamentPayload<ExtArgs>
    TableType: Prisma.$TableTypePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    tournamentId: number
    teamId: number
    streakType: string
    scope: string
    rank: number
    streakCount: number
    matchesPlayed: number
    createdAt: Date
    updatedAt: Date
    mode: string
    viewTypeId: number
  }, ExtArgs["result"]["teamStreakStat"]>
  composites: {}
}

export type TeamStreakStatGetPayload<S extends boolean | null | undefined | TeamStreakStatDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TeamStreakStatPayload, S>

export type TeamStreakStatCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TeamStreakStatFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TeamStreakStatCountAggregateInputType | true
  }

export interface TeamStreakStatDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TeamStreakStat'], meta: { name: 'TeamStreakStat' } }
  /**
   * Find zero or one TeamStreakStat that matches the filter.
   * @param {TeamStreakStatFindUniqueArgs} args - Arguments to find a TeamStreakStat
   * @example
   * // Get one TeamStreakStat
   * const teamStreakStat = await prisma.teamStreakStat.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TeamStreakStatFindUniqueArgs>(args: Prisma.SelectSubset<T, TeamStreakStatFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TeamStreakStatClient<runtime.Types.Result.GetResult<Prisma.$TeamStreakStatPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TeamStreakStat that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TeamStreakStatFindUniqueOrThrowArgs} args - Arguments to find a TeamStreakStat
   * @example
   * // Get one TeamStreakStat
   * const teamStreakStat = await prisma.teamStreakStat.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TeamStreakStatFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TeamStreakStatFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TeamStreakStatClient<runtime.Types.Result.GetResult<Prisma.$TeamStreakStatPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TeamStreakStat that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TeamStreakStatFindFirstArgs} args - Arguments to find a TeamStreakStat
   * @example
   * // Get one TeamStreakStat
   * const teamStreakStat = await prisma.teamStreakStat.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TeamStreakStatFindFirstArgs>(args?: Prisma.SelectSubset<T, TeamStreakStatFindFirstArgs<ExtArgs>>): Prisma.Prisma__TeamStreakStatClient<runtime.Types.Result.GetResult<Prisma.$TeamStreakStatPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TeamStreakStat that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TeamStreakStatFindFirstOrThrowArgs} args - Arguments to find a TeamStreakStat
   * @example
   * // Get one TeamStreakStat
   * const teamStreakStat = await prisma.teamStreakStat.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TeamStreakStatFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TeamStreakStatFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TeamStreakStatClient<runtime.Types.Result.GetResult<Prisma.$TeamStreakStatPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TeamStreakStats that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TeamStreakStatFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TeamStreakStats
   * const teamStreakStats = await prisma.teamStreakStat.findMany()
   * 
   * // Get first 10 TeamStreakStats
   * const teamStreakStats = await prisma.teamStreakStat.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const teamStreakStatWithIdOnly = await prisma.teamStreakStat.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TeamStreakStatFindManyArgs>(args?: Prisma.SelectSubset<T, TeamStreakStatFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TeamStreakStatPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TeamStreakStat.
   * @param {TeamStreakStatCreateArgs} args - Arguments to create a TeamStreakStat.
   * @example
   * // Create one TeamStreakStat
   * const TeamStreakStat = await prisma.teamStreakStat.create({
   *   data: {
   *     // ... data to create a TeamStreakStat
   *   }
   * })
   * 
   */
  create<T extends TeamStreakStatCreateArgs>(args: Prisma.SelectSubset<T, TeamStreakStatCreateArgs<ExtArgs>>): Prisma.Prisma__TeamStreakStatClient<runtime.Types.Result.GetResult<Prisma.$TeamStreakStatPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TeamStreakStats.
   * @param {TeamStreakStatCreateManyArgs} args - Arguments to create many TeamStreakStats.
   * @example
   * // Create many TeamStreakStats
   * const teamStreakStat = await prisma.teamStreakStat.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TeamStreakStatCreateManyArgs>(args?: Prisma.SelectSubset<T, TeamStreakStatCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TeamStreakStats and returns the data saved in the database.
   * @param {TeamStreakStatCreateManyAndReturnArgs} args - Arguments to create many TeamStreakStats.
   * @example
   * // Create many TeamStreakStats
   * const teamStreakStat = await prisma.teamStreakStat.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TeamStreakStats and only return the `id`
   * const teamStreakStatWithIdOnly = await prisma.teamStreakStat.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TeamStreakStatCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TeamStreakStatCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TeamStreakStatPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TeamStreakStat.
   * @param {TeamStreakStatDeleteArgs} args - Arguments to delete one TeamStreakStat.
   * @example
   * // Delete one TeamStreakStat
   * const TeamStreakStat = await prisma.teamStreakStat.delete({
   *   where: {
   *     // ... filter to delete one TeamStreakStat
   *   }
   * })
   * 
   */
  delete<T extends TeamStreakStatDeleteArgs>(args: Prisma.SelectSubset<T, TeamStreakStatDeleteArgs<ExtArgs>>): Prisma.Prisma__TeamStreakStatClient<runtime.Types.Result.GetResult<Prisma.$TeamStreakStatPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TeamStreakStat.
   * @param {TeamStreakStatUpdateArgs} args - Arguments to update one TeamStreakStat.
   * @example
   * // Update one TeamStreakStat
   * const teamStreakStat = await prisma.teamStreakStat.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TeamStreakStatUpdateArgs>(args: Prisma.SelectSubset<T, TeamStreakStatUpdateArgs<ExtArgs>>): Prisma.Prisma__TeamStreakStatClient<runtime.Types.Result.GetResult<Prisma.$TeamStreakStatPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TeamStreakStats.
   * @param {TeamStreakStatDeleteManyArgs} args - Arguments to filter TeamStreakStats to delete.
   * @example
   * // Delete a few TeamStreakStats
   * const { count } = await prisma.teamStreakStat.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TeamStreakStatDeleteManyArgs>(args?: Prisma.SelectSubset<T, TeamStreakStatDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TeamStreakStats.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TeamStreakStatUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TeamStreakStats
   * const teamStreakStat = await prisma.teamStreakStat.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TeamStreakStatUpdateManyArgs>(args: Prisma.SelectSubset<T, TeamStreakStatUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TeamStreakStats and returns the data updated in the database.
   * @param {TeamStreakStatUpdateManyAndReturnArgs} args - Arguments to update many TeamStreakStats.
   * @example
   * // Update many TeamStreakStats
   * const teamStreakStat = await prisma.teamStreakStat.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TeamStreakStats and only return the `id`
   * const teamStreakStatWithIdOnly = await prisma.teamStreakStat.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TeamStreakStatUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TeamStreakStatUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TeamStreakStatPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TeamStreakStat.
   * @param {TeamStreakStatUpsertArgs} args - Arguments to update or create a TeamStreakStat.
   * @example
   * // Update or create a TeamStreakStat
   * const teamStreakStat = await prisma.teamStreakStat.upsert({
   *   create: {
   *     // ... data to create a TeamStreakStat
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TeamStreakStat we want to update
   *   }
   * })
   */
  upsert<T extends TeamStreakStatUpsertArgs>(args: Prisma.SelectSubset<T, TeamStreakStatUpsertArgs<ExtArgs>>): Prisma.Prisma__TeamStreakStatClient<runtime.Types.Result.GetResult<Prisma.$TeamStreakStatPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TeamStreakStats.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TeamStreakStatCountArgs} args - Arguments to filter TeamStreakStats to count.
   * @example
   * // Count the number of TeamStreakStats
   * const count = await prisma.teamStreakStat.count({
   *   where: {
   *     // ... the filter for the TeamStreakStats we want to count
   *   }
   * })
  **/
  count<T extends TeamStreakStatCountArgs>(
    args?: Prisma.Subset<T, TeamStreakStatCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TeamStreakStatCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TeamStreakStat.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TeamStreakStatAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TeamStreakStatAggregateArgs>(args: Prisma.Subset<T, TeamStreakStatAggregateArgs>): Prisma.PrismaPromise<GetTeamStreakStatAggregateType<T>>

  /**
   * Group by TeamStreakStat.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TeamStreakStatGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TeamStreakStatGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TeamStreakStatGroupByArgs['orderBy'] }
      : { orderBy?: TeamStreakStatGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TeamStreakStatGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTeamStreakStatGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TeamStreakStat model
 */
readonly fields: TeamStreakStatFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TeamStreakStat.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TeamStreakStatClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  Team<T extends Prisma.TeamDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TeamDefaultArgs<ExtArgs>>): Prisma.Prisma__TeamClient<runtime.Types.Result.GetResult<Prisma.$TeamPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  Tournament<T extends Prisma.TournamentDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TournamentDefaultArgs<ExtArgs>>): Prisma.Prisma__TournamentClient<runtime.Types.Result.GetResult<Prisma.$TournamentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  TableType<T extends Prisma.TableTypeDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TableTypeDefaultArgs<ExtArgs>>): Prisma.Prisma__TableTypeClient<runtime.Types.Result.GetResult<Prisma.$TableTypePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TeamStreakStat model
 */
export interface TeamStreakStatFieldRefs {
  readonly id: Prisma.FieldRef<"TeamStreakStat", 'Int'>
  readonly tournamentId: Prisma.FieldRef<"TeamStreakStat", 'Int'>
  readonly teamId: Prisma.FieldRef<"TeamStreakStat", 'Int'>
  readonly streakType: Prisma.FieldRef<"TeamStreakStat", 'String'>
  readonly scope: Prisma.FieldRef<"TeamStreakStat", 'String'>
  readonly rank: Prisma.FieldRef<"TeamStreakStat", 'Int'>
  readonly streakCount: Prisma.FieldRef<"TeamStreakStat", 'Int'>
  readonly matchesPlayed: Prisma.FieldRef<"TeamStreakStat", 'Int'>
  readonly createdAt: Prisma.FieldRef<"TeamStreakStat", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"TeamStreakStat", 'DateTime'>
  readonly mode: Prisma.FieldRef<"TeamStreakStat", 'String'>
  readonly viewTypeId: Prisma.FieldRef<"TeamStreakStat", 'Int'>
}
    

// Custom InputTypes
/**
 * TeamStreakStat findUnique
 */
export type TeamStreakStatFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TeamStreakStat
   */
  select?: Prisma.TeamStreakStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TeamStreakStat
   */
  omit?: Prisma.TeamStreakStatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TeamStreakStatInclude<ExtArgs> | null
  /**
   * Filter, which TeamStreakStat to fetch.
   */
  where: Prisma.TeamStreakStatWhereUniqueInput
}

/**
 * TeamStreakStat findUniqueOrThrow
 */
export type TeamStreakStatFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TeamStreakStat
   */
  select?: Prisma.TeamStreakStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TeamStreakStat
   */
  omit?: Prisma.TeamStreakStatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TeamStreakStatInclude<ExtArgs> | null
  /**
   * Filter, which TeamStreakStat to fetch.
   */
  where: Prisma.TeamStreakStatWhereUniqueInput
}

/**
 * TeamStreakStat findFirst
 */
export type TeamStreakStatFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TeamStreakStat
   */
  select?: Prisma.TeamStreakStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TeamStreakStat
   */
  omit?: Prisma.TeamStreakStatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TeamStreakStatInclude<ExtArgs> | null
  /**
   * Filter, which TeamStreakStat to fetch.
   */
  where?: Prisma.TeamStreakStatWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TeamStreakStats to fetch.
   */
  orderBy?: Prisma.TeamStreakStatOrderByWithRelationInput | Prisma.TeamStreakStatOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TeamStreakStats.
   */
  cursor?: Prisma.TeamStreakStatWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TeamStreakStats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TeamStreakStats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TeamStreakStats.
   */
  distinct?: Prisma.TeamStreakStatScalarFieldEnum | Prisma.TeamStreakStatScalarFieldEnum[]
}

/**
 * TeamStreakStat findFirstOrThrow
 */
export type TeamStreakStatFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TeamStreakStat
   */
  select?: Prisma.TeamStreakStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TeamStreakStat
   */
  omit?: Prisma.TeamStreakStatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TeamStreakStatInclude<ExtArgs> | null
  /**
   * Filter, which TeamStreakStat to fetch.
   */
  where?: Prisma.TeamStreakStatWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TeamStreakStats to fetch.
   */
  orderBy?: Prisma.TeamStreakStatOrderByWithRelationInput | Prisma.TeamStreakStatOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TeamStreakStats.
   */
  cursor?: Prisma.TeamStreakStatWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TeamStreakStats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TeamStreakStats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TeamStreakStats.
   */
  distinct?: Prisma.TeamStreakStatScalarFieldEnum | Prisma.TeamStreakStatScalarFieldEnum[]
}

/**
 * TeamStreakStat findMany
 */
export type TeamStreakStatFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TeamStreakStat
   */
  select?: Prisma.TeamStreakStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TeamStreakStat
   */
  omit?: Prisma.TeamStreakStatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TeamStreakStatInclude<ExtArgs> | null
  /**
   * Filter, which TeamStreakStats to fetch.
   */
  where?: Prisma.TeamStreakStatWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TeamStreakStats to fetch.
   */
  orderBy?: Prisma.TeamStreakStatOrderByWithRelationInput | Prisma.TeamStreakStatOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TeamStreakStats.
   */
  cursor?: Prisma.TeamStreakStatWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TeamStreakStats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TeamStreakStats.
   */
  skip?: number
  distinct?: Prisma.TeamStreakStatScalarFieldEnum | Prisma.TeamStreakStatScalarFieldEnum[]
}

/**
 * TeamStreakStat create
 */
export type TeamStreakStatCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TeamStreakStat
   */
  select?: Prisma.TeamStreakStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TeamStreakStat
   */
  omit?: Prisma.TeamStreakStatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TeamStreakStatInclude<ExtArgs> | null
  /**
   * The data needed to create a TeamStreakStat.
   */
  data: Prisma.XOR<Prisma.TeamStreakStatCreateInput, Prisma.TeamStreakStatUncheckedCreateInput>
}

/**
 * TeamStreakStat createMany
 */
export type TeamStreakStatCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TeamStreakStats.
   */
  data: Prisma.TeamStreakStatCreateManyInput | Prisma.TeamStreakStatCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TeamStreakStat createManyAndReturn
 */
export type TeamStreakStatCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TeamStreakStat
   */
  select?: Prisma.TeamStreakStatSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TeamStreakStat
   */
  omit?: Prisma.TeamStreakStatOmit<ExtArgs> | null
  /**
   * The data used to create many TeamStreakStats.
   */
  data: Prisma.TeamStreakStatCreateManyInput | Prisma.TeamStreakStatCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TeamStreakStatIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * TeamStreakStat update
 */
export type TeamStreakStatUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TeamStreakStat
   */
  select?: Prisma.TeamStreakStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TeamStreakStat
   */
  omit?: Prisma.TeamStreakStatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TeamStreakStatInclude<ExtArgs> | null
  /**
   * The data needed to update a TeamStreakStat.
   */
  data: Prisma.XOR<Prisma.TeamStreakStatUpdateInput, Prisma.TeamStreakStatUncheckedUpdateInput>
  /**
   * Choose, which TeamStreakStat to update.
   */
  where: Prisma.TeamStreakStatWhereUniqueInput
}

/**
 * TeamStreakStat updateMany
 */
export type TeamStreakStatUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TeamStreakStats.
   */
  data: Prisma.XOR<Prisma.TeamStreakStatUpdateManyMutationInput, Prisma.TeamStreakStatUncheckedUpdateManyInput>
  /**
   * Filter which TeamStreakStats to update
   */
  where?: Prisma.TeamStreakStatWhereInput
  /**
   * Limit how many TeamStreakStats to update.
   */
  limit?: number
}

/**
 * TeamStreakStat updateManyAndReturn
 */
export type TeamStreakStatUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TeamStreakStat
   */
  select?: Prisma.TeamStreakStatSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TeamStreakStat
   */
  omit?: Prisma.TeamStreakStatOmit<ExtArgs> | null
  /**
   * The data used to update TeamStreakStats.
   */
  data: Prisma.XOR<Prisma.TeamStreakStatUpdateManyMutationInput, Prisma.TeamStreakStatUncheckedUpdateManyInput>
  /**
   * Filter which TeamStreakStats to update
   */
  where?: Prisma.TeamStreakStatWhereInput
  /**
   * Limit how many TeamStreakStats to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TeamStreakStatIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * TeamStreakStat upsert
 */
export type TeamStreakStatUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TeamStreakStat
   */
  select?: Prisma.TeamStreakStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TeamStreakStat
   */
  omit?: Prisma.TeamStreakStatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TeamStreakStatInclude<ExtArgs> | null
  /**
   * The filter to search for the TeamStreakStat to update in case it exists.
   */
  where: Prisma.TeamStreakStatWhereUniqueInput
  /**
   * In case the TeamStreakStat found by the `where` argument doesn't exist, create a new TeamStreakStat with this data.
   */
  create: Prisma.XOR<Prisma.TeamStreakStatCreateInput, Prisma.TeamStreakStatUncheckedCreateInput>
  /**
   * In case the TeamStreakStat was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TeamStreakStatUpdateInput, Prisma.TeamStreakStatUncheckedUpdateInput>
}

/**
 * TeamStreakStat delete
 */
export type TeamStreakStatDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TeamStreakStat
   */
  select?: Prisma.TeamStreakStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TeamStreakStat
   */
  omit?: Prisma.TeamStreakStatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TeamStreakStatInclude<ExtArgs> | null
  /**
   * Filter which TeamStreakStat to delete.
   */
  where: Prisma.TeamStreakStatWhereUniqueInput
}

/**
 * TeamStreakStat deleteMany
 */
export type TeamStreakStatDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TeamStreakStats to delete
   */
  where?: Prisma.TeamStreakStatWhereInput
  /**
   * Limit how many TeamStreakStats to delete.
   */
  limit?: number
}

/**
 * TeamStreakStat without action
 */
export type TeamStreakStatDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TeamStreakStat
   */
  select?: Prisma.TeamStreakStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TeamStreakStat
   */
  omit?: Prisma.TeamStreakStatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TeamStreakStatInclude<ExtArgs> | null
}
