
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TopPlayerAggression` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model TopPlayerAggression
 * 
 */
export type TopPlayerAggressionModel = runtime.Types.Result.DefaultSelection<Prisma.$TopPlayerAggressionPayload>

export type AggregateTopPlayerAggression = {
  _count: TopPlayerAggressionCountAggregateOutputType | null
  _avg: TopPlayerAggressionAvgAggregateOutputType | null
  _sum: TopPlayerAggressionSumAggregateOutputType | null
  _min: TopPlayerAggressionMinAggregateOutputType | null
  _max: TopPlayerAggressionMaxAggregateOutputType | null
}

export type TopPlayerAggressionAvgAggregateOutputType = {
  id: number | null
  tournamentId: number | null
  teamId: number | null
  playerId: number | null
  rank: number | null
  yellowCards: number | null
  redCards: number | null
  viewTypeId: number | null
}

export type TopPlayerAggressionSumAggregateOutputType = {
  id: number | null
  tournamentId: number | null
  teamId: number | null
  playerId: number | null
  rank: number | null
  yellowCards: number | null
  redCards: number | null
  viewTypeId: number | null
}

export type TopPlayerAggressionMinAggregateOutputType = {
  id: number | null
  tournamentId: number | null
  teamId: number | null
  playerId: number | null
  rank: number | null
  yellowCards: number | null
  redCards: number | null
  createdAt: Date | null
  updatedAt: Date | null
  viewTypeId: number | null
}

export type TopPlayerAggressionMaxAggregateOutputType = {
  id: number | null
  tournamentId: number | null
  teamId: number | null
  playerId: number | null
  rank: number | null
  yellowCards: number | null
  redCards: number | null
  createdAt: Date | null
  updatedAt: Date | null
  viewTypeId: number | null
}

export type TopPlayerAggressionCountAggregateOutputType = {
  id: number
  tournamentId: number
  teamId: number
  playerId: number
  rank: number
  yellowCards: number
  redCards: number
  createdAt: number
  updatedAt: number
  viewTypeId: number
  _all: number
}


export type TopPlayerAggressionAvgAggregateInputType = {
  id?: true
  tournamentId?: true
  teamId?: true
  playerId?: true
  rank?: true
  yellowCards?: true
  redCards?: true
  viewTypeId?: true
}

export type TopPlayerAggressionSumAggregateInputType = {
  id?: true
  tournamentId?: true
  teamId?: true
  playerId?: true
  rank?: true
  yellowCards?: true
  redCards?: true
  viewTypeId?: true
}

export type TopPlayerAggressionMinAggregateInputType = {
  id?: true
  tournamentId?: true
  teamId?: true
  playerId?: true
  rank?: true
  yellowCards?: true
  redCards?: true
  createdAt?: true
  updatedAt?: true
  viewTypeId?: true
}

export type TopPlayerAggressionMaxAggregateInputType = {
  id?: true
  tournamentId?: true
  teamId?: true
  playerId?: true
  rank?: true
  yellowCards?: true
  redCards?: true
  createdAt?: true
  updatedAt?: true
  viewTypeId?: true
}

export type TopPlayerAggressionCountAggregateInputType = {
  id?: true
  tournamentId?: true
  teamId?: true
  playerId?: true
  rank?: true
  yellowCards?: true
  redCards?: true
  createdAt?: true
  updatedAt?: true
  viewTypeId?: true
  _all?: true
}

export type TopPlayerAggressionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TopPlayerAggression to aggregate.
   */
  where?: Prisma.TopPlayerAggressionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TopPlayerAggressions to fetch.
   */
  orderBy?: Prisma.TopPlayerAggressionOrderByWithRelationInput | Prisma.TopPlayerAggressionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TopPlayerAggressionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TopPlayerAggressions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TopPlayerAggressions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TopPlayerAggressions
  **/
  _count?: true | TopPlayerAggressionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TopPlayerAggressionAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TopPlayerAggressionSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TopPlayerAggressionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TopPlayerAggressionMaxAggregateInputType
}

export type GetTopPlayerAggressionAggregateType<T extends TopPlayerAggressionAggregateArgs> = {
      [P in keyof T & keyof AggregateTopPlayerAggression]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTopPlayerAggression[P]>
    : Prisma.GetScalarType<T[P], AggregateTopPlayerAggression[P]>
}




export type TopPlayerAggressionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TopPlayerAggressionWhereInput
  orderBy?: Prisma.TopPlayerAggressionOrderByWithAggregationInput | Prisma.TopPlayerAggressionOrderByWithAggregationInput[]
  by: Prisma.TopPlayerAggressionScalarFieldEnum[] | Prisma.TopPlayerAggressionScalarFieldEnum
  having?: Prisma.TopPlayerAggressionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TopPlayerAggressionCountAggregateInputType | true
  _avg?: TopPlayerAggressionAvgAggregateInputType
  _sum?: TopPlayerAggressionSumAggregateInputType
  _min?: TopPlayerAggressionMinAggregateInputType
  _max?: TopPlayerAggressionMaxAggregateInputType
}

export type TopPlayerAggressionGroupByOutputType = {
  id: number
  tournamentId: number
  teamId: number
  playerId: number
  rank: number | null
  yellowCards: number | null
  redCards: number | null
  createdAt: Date
  updatedAt: Date
  viewTypeId: number
  _count: TopPlayerAggressionCountAggregateOutputType | null
  _avg: TopPlayerAggressionAvgAggregateOutputType | null
  _sum: TopPlayerAggressionSumAggregateOutputType | null
  _min: TopPlayerAggressionMinAggregateOutputType | null
  _max: TopPlayerAggressionMaxAggregateOutputType | null
}

type GetTopPlayerAggressionGroupByPayload<T extends TopPlayerAggressionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TopPlayerAggressionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TopPlayerAggressionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TopPlayerAggressionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TopPlayerAggressionGroupByOutputType[P]>
      }
    >
  >



export type TopPlayerAggressionWhereInput = {
  AND?: Prisma.TopPlayerAggressionWhereInput | Prisma.TopPlayerAggressionWhereInput[]
  OR?: Prisma.TopPlayerAggressionWhereInput[]
  NOT?: Prisma.TopPlayerAggressionWhereInput | Prisma.TopPlayerAggressionWhereInput[]
  id?: Prisma.IntFilter<"TopPlayerAggression"> | number
  tournamentId?: Prisma.IntFilter<"TopPlayerAggression"> | number
  teamId?: Prisma.IntFilter<"TopPlayerAggression"> | number
  playerId?: Prisma.IntFilter<"TopPlayerAggression"> | number
  rank?: Prisma.IntNullableFilter<"TopPlayerAggression"> | number | null
  yellowCards?: Prisma.IntNullableFilter<"TopPlayerAggression"> | number | null
  redCards?: Prisma.IntNullableFilter<"TopPlayerAggression"> | number | null
  createdAt?: Prisma.DateTimeFilter<"TopPlayerAggression"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TopPlayerAggression"> | Date | string
  viewTypeId?: Prisma.IntFilter<"TopPlayerAggression"> | number
  Player?: Prisma.XOR<Prisma.PlayerScalarRelationFilter, Prisma.PlayerWhereInput>
  Team?: Prisma.XOR<Prisma.TeamScalarRelationFilter, Prisma.TeamWhereInput>
  Tournament?: Prisma.XOR<Prisma.TournamentScalarRelationFilter, Prisma.TournamentWhereInput>
  TableType?: Prisma.XOR<Prisma.TableTypeScalarRelationFilter, Prisma.TableTypeWhereInput>
}

export type TopPlayerAggressionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  tournamentId?: Prisma.SortOrder
  teamId?: Prisma.SortOrder
  playerId?: Prisma.SortOrder
  rank?: Prisma.SortOrderInput | Prisma.SortOrder
  yellowCards?: Prisma.SortOrderInput | Prisma.SortOrder
  redCards?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  viewTypeId?: Prisma.SortOrder
  Player?: Prisma.PlayerOrderByWithRelationInput
  Team?: Prisma.TeamOrderByWithRelationInput
  Tournament?: Prisma.TournamentOrderByWithRelationInput
  TableType?: Prisma.TableTypeOrderByWithRelationInput
}

export type TopPlayerAggressionWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  tournamentId_playerId_viewTypeId?: Prisma.TopPlayerAggressionTournamentIdPlayerIdViewTypeIdCompoundUniqueInput
  AND?: Prisma.TopPlayerAggressionWhereInput | Prisma.TopPlayerAggressionWhereInput[]
  OR?: Prisma.TopPlayerAggressionWhereInput[]
  NOT?: Prisma.TopPlayerAggressionWhereInput | Prisma.TopPlayerAggressionWhereInput[]
  tournamentId?: Prisma.IntFilter<"TopPlayerAggression"> | number
  teamId?: Prisma.IntFilter<"TopPlayerAggression"> | number
  playerId?: Prisma.IntFilter<"TopPlayerAggression"> | number
  rank?: Prisma.IntNullableFilter<"TopPlayerAggression"> | number | null
  yellowCards?: Prisma.IntNullableFilter<"TopPlayerAggression"> | number | null
  redCards?: Prisma.IntNullableFilter<"TopPlayerAggression"> | number | null
  createdAt?: Prisma.DateTimeFilter<"TopPlayerAggression"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TopPlayerAggression"> | Date | string
  viewTypeId?: Prisma.IntFilter<"TopPlayerAggression"> | number
  Player?: Prisma.XOR<Prisma.PlayerScalarRelationFilter, Prisma.PlayerWhereInput>
  Team?: Prisma.XOR<Prisma.TeamScalarRelationFilter, Prisma.TeamWhereInput>
  Tournament?: Prisma.XOR<Prisma.TournamentScalarRelationFilter, Prisma.TournamentWhereInput>
  TableType?: Prisma.XOR<Prisma.TableTypeScalarRelationFilter, Prisma.TableTypeWhereInput>
}, "id" | "tournamentId_playerId_viewTypeId">

export type TopPlayerAggressionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  tournamentId?: Prisma.SortOrder
  teamId?: Prisma.SortOrder
  playerId?: Prisma.SortOrder
  rank?: Prisma.SortOrderInput | Prisma.SortOrder
  yellowCards?: Prisma.SortOrderInput | Prisma.SortOrder
  redCards?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  viewTypeId?: Prisma.SortOrder
  _count?: Prisma.TopPlayerAggressionCountOrderByAggregateInput
  _avg?: Prisma.TopPlayerAggressionAvgOrderByAggregateInput
  _max?: Prisma.TopPlayerAggressionMaxOrderByAggregateInput
  _min?: Prisma.TopPlayerAggressionMinOrderByAggregateInput
  _sum?: Prisma.TopPlayerAggressionSumOrderByAggregateInput
}

export type TopPlayerAggressionScalarWhereWithAggregatesInput = {
  AND?: Prisma.TopPlayerAggressionScalarWhereWithAggregatesInput | Prisma.TopPlayerAggressionScalarWhereWithAggregatesInput[]
  OR?: Prisma.TopPlayerAggressionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TopPlayerAggressionScalarWhereWithAggregatesInput | Prisma.TopPlayerAggressionScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"TopPlayerAggression"> | number
  tournamentId?: Prisma.IntWithAggregatesFilter<"TopPlayerAggression"> | number
  teamId?: Prisma.IntWithAggregatesFilter<"TopPlayerAggression"> | number
  playerId?: Prisma.IntWithAggregatesFilter<"TopPlayerAggression"> | number
  rank?: Prisma.IntNullableWithAggregatesFilter<"TopPlayerAggression"> | number | null
  yellowCards?: Prisma.IntNullableWithAggregatesFilter<"TopPlayerAggression"> | number | null
  redCards?: Prisma.IntNullableWithAggregatesFilter<"TopPlayerAggression"> | number | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"TopPlayerAggression"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"TopPlayerAggression"> | Date | string
  viewTypeId?: Prisma.IntWithAggregatesFilter<"TopPlayerAggression"> | number
}

export type TopPlayerAggressionCreateInput = {
  rank?: number | null
  yellowCards?: number | null
  redCards?: number | null
  createdAt?: Date | string
  updatedAt: Date | string
  Player: Prisma.PlayerCreateNestedOneWithoutTopPlayerAggressionInput
  Team: Prisma.TeamCreateNestedOneWithoutTopPlayerAggressionInput
  Tournament: Prisma.TournamentCreateNestedOneWithoutTopPlayerAggressionInput
  TableType: Prisma.TableTypeCreateNestedOneWithoutTopPlayerAggressionInput
}

export type TopPlayerAggressionUncheckedCreateInput = {
  id?: number
  tournamentId: number
  teamId: number
  playerId: number
  rank?: number | null
  yellowCards?: number | null
  redCards?: number | null
  createdAt?: Date | string
  updatedAt: Date | string
  viewTypeId: number
}

export type TopPlayerAggressionUpdateInput = {
  rank?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  yellowCards?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  redCards?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Player?: Prisma.PlayerUpdateOneRequiredWithoutTopPlayerAggressionNestedInput
  Team?: Prisma.TeamUpdateOneRequiredWithoutTopPlayerAggressionNestedInput
  Tournament?: Prisma.TournamentUpdateOneRequiredWithoutTopPlayerAggressionNestedInput
  TableType?: Prisma.TableTypeUpdateOneRequiredWithoutTopPlayerAggressionNestedInput
}

export type TopPlayerAggressionUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  tournamentId?: Prisma.IntFieldUpdateOperationsInput | number
  teamId?: Prisma.IntFieldUpdateOperationsInput | number
  playerId?: Prisma.IntFieldUpdateOperationsInput | number
  rank?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  yellowCards?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  redCards?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  viewTypeId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type TopPlayerAggressionCreateManyInput = {
  id?: number
  tournamentId: number
  teamId: number
  playerId: number
  rank?: number | null
  yellowCards?: number | null
  redCards?: number | null
  createdAt?: Date | string
  updatedAt: Date | string
  viewTypeId: number
}

export type TopPlayerAggressionUpdateManyMutationInput = {
  rank?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  yellowCards?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  redCards?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TopPlayerAggressionUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  tournamentId?: Prisma.IntFieldUpdateOperationsInput | number
  teamId?: Prisma.IntFieldUpdateOperationsInput | number
  playerId?: Prisma.IntFieldUpdateOperationsInput | number
  rank?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  yellowCards?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  redCards?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  viewTypeId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type TopPlayerAggressionListRelationFilter = {
  every?: Prisma.TopPlayerAggressionWhereInput
  some?: Prisma.TopPlayerAggressionWhereInput
  none?: Prisma.TopPlayerAggressionWhereInput
}

export type TopPlayerAggressionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TopPlayerAggressionTournamentIdPlayerIdViewTypeIdCompoundUniqueInput = {
  tournamentId: number
  playerId: number
  viewTypeId: number
}

export type TopPlayerAggressionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tournamentId?: Prisma.SortOrder
  teamId?: Prisma.SortOrder
  playerId?: Prisma.SortOrder
  rank?: Prisma.SortOrder
  yellowCards?: Prisma.SortOrder
  redCards?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  viewTypeId?: Prisma.SortOrder
}

export type TopPlayerAggressionAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tournamentId?: Prisma.SortOrder
  teamId?: Prisma.SortOrder
  playerId?: Prisma.SortOrder
  rank?: Prisma.SortOrder
  yellowCards?: Prisma.SortOrder
  redCards?: Prisma.SortOrder
  viewTypeId?: Prisma.SortOrder
}

export type TopPlayerAggressionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tournamentId?: Prisma.SortOrder
  teamId?: Prisma.SortOrder
  playerId?: Prisma.SortOrder
  rank?: Prisma.SortOrder
  yellowCards?: Prisma.SortOrder
  redCards?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  viewTypeId?: Prisma.SortOrder
}

export type TopPlayerAggressionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tournamentId?: Prisma.SortOrder
  teamId?: Prisma.SortOrder
  playerId?: Prisma.SortOrder
  rank?: Prisma.SortOrder
  yellowCards?: Prisma.SortOrder
  redCards?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  viewTypeId?: Prisma.SortOrder
}

export type TopPlayerAggressionSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tournamentId?: Prisma.SortOrder
  teamId?: Prisma.SortOrder
  playerId?: Prisma.SortOrder
  rank?: Prisma.SortOrder
  yellowCards?: Prisma.SortOrder
  redCards?: Prisma.SortOrder
  viewTypeId?: Prisma.SortOrder
}

export type TopPlayerAggressionCreateNestedManyWithoutPlayerInput = {
  create?: Prisma.XOR<Prisma.TopPlayerAggressionCreateWithoutPlayerInput, Prisma.TopPlayerAggressionUncheckedCreateWithoutPlayerInput> | Prisma.TopPlayerAggressionCreateWithoutPlayerInput[] | Prisma.TopPlayerAggressionUncheckedCreateWithoutPlayerInput[]
  connectOrCreate?: Prisma.TopPlayerAggressionCreateOrConnectWithoutPlayerInput | Prisma.TopPlayerAggressionCreateOrConnectWithoutPlayerInput[]
  createMany?: Prisma.TopPlayerAggressionCreateManyPlayerInputEnvelope
  connect?: Prisma.TopPlayerAggressionWhereUniqueInput | Prisma.TopPlayerAggressionWhereUniqueInput[]
}

export type TopPlayerAggressionUncheckedCreateNestedManyWithoutPlayerInput = {
  create?: Prisma.XOR<Prisma.TopPlayerAggressionCreateWithoutPlayerInput, Prisma.TopPlayerAggressionUncheckedCreateWithoutPlayerInput> | Prisma.TopPlayerAggressionCreateWithoutPlayerInput[] | Prisma.TopPlayerAggressionUncheckedCreateWithoutPlayerInput[]
  connectOrCreate?: Prisma.TopPlayerAggressionCreateOrConnectWithoutPlayerInput | Prisma.TopPlayerAggressionCreateOrConnectWithoutPlayerInput[]
  createMany?: Prisma.TopPlayerAggressionCreateManyPlayerInputEnvelope
  connect?: Prisma.TopPlayerAggressionWhereUniqueInput | Prisma.TopPlayerAggressionWhereUniqueInput[]
}

export type TopPlayerAggressionUpdateManyWithoutPlayerNestedInput = {
  create?: Prisma.XOR<Prisma.TopPlayerAggressionCreateWithoutPlayerInput, Prisma.TopPlayerAggressionUncheckedCreateWithoutPlayerInput> | Prisma.TopPlayerAggressionCreateWithoutPlayerInput[] | Prisma.TopPlayerAggressionUncheckedCreateWithoutPlayerInput[]
  connectOrCreate?: Prisma.TopPlayerAggressionCreateOrConnectWithoutPlayerInput | Prisma.TopPlayerAggressionCreateOrConnectWithoutPlayerInput[]
  upsert?: Prisma.TopPlayerAggressionUpsertWithWhereUniqueWithoutPlayerInput | Prisma.TopPlayerAggressionUpsertWithWhereUniqueWithoutPlayerInput[]
  createMany?: Prisma.TopPlayerAggressionCreateManyPlayerInputEnvelope
  set?: Prisma.TopPlayerAggressionWhereUniqueInput | Prisma.TopPlayerAggressionWhereUniqueInput[]
  disconnect?: Prisma.TopPlayerAggressionWhereUniqueInput | Prisma.TopPlayerAggressionWhereUniqueInput[]
  delete?: Prisma.TopPlayerAggressionWhereUniqueInput | Prisma.TopPlayerAggressionWhereUniqueInput[]
  connect?: Prisma.TopPlayerAggressionWhereUniqueInput | Prisma.TopPlayerAggressionWhereUniqueInput[]
  update?: Prisma.TopPlayerAggressionUpdateWithWhereUniqueWithoutPlayerInput | Prisma.TopPlayerAggressionUpdateWithWhereUniqueWithoutPlayerInput[]
  updateMany?: Prisma.TopPlayerAggressionUpdateManyWithWhereWithoutPlayerInput | Prisma.TopPlayerAggressionUpdateManyWithWhereWithoutPlayerInput[]
  deleteMany?: Prisma.TopPlayerAggressionScalarWhereInput | Prisma.TopPlayerAggressionScalarWhereInput[]
}

export type TopPlayerAggressionUncheckedUpdateManyWithoutPlayerNestedInput = {
  create?: Prisma.XOR<Prisma.TopPlayerAggressionCreateWithoutPlayerInput, Prisma.TopPlayerAggressionUncheckedCreateWithoutPlayerInput> | Prisma.TopPlayerAggressionCreateWithoutPlayerInput[] | Prisma.TopPlayerAggressionUncheckedCreateWithoutPlayerInput[]
  connectOrCreate?: Prisma.TopPlayerAggressionCreateOrConnectWithoutPlayerInput | Prisma.TopPlayerAggressionCreateOrConnectWithoutPlayerInput[]
  upsert?: Prisma.TopPlayerAggressionUpsertWithWhereUniqueWithoutPlayerInput | Prisma.TopPlayerAggressionUpsertWithWhereUniqueWithoutPlayerInput[]
  createMany?: Prisma.TopPlayerAggressionCreateManyPlayerInputEnvelope
  set?: Prisma.TopPlayerAggressionWhereUniqueInput | Prisma.TopPlayerAggressionWhereUniqueInput[]
  disconnect?: Prisma.TopPlayerAggressionWhereUniqueInput | Prisma.TopPlayerAggressionWhereUniqueInput[]
  delete?: Prisma.TopPlayerAggressionWhereUniqueInput | Prisma.TopPlayerAggressionWhereUniqueInput[]
  connect?: Prisma.TopPlayerAggressionWhereUniqueInput | Prisma.TopPlayerAggressionWhereUniqueInput[]
  update?: Prisma.TopPlayerAggressionUpdateWithWhereUniqueWithoutPlayerInput | Prisma.TopPlayerAggressionUpdateWithWhereUniqueWithoutPlayerInput[]
  updateMany?: Prisma.TopPlayerAggressionUpdateManyWithWhereWithoutPlayerInput | Prisma.TopPlayerAggressionUpdateManyWithWhereWithoutPlayerInput[]
  deleteMany?: Prisma.TopPlayerAggressionScalarWhereInput | Prisma.TopPlayerAggressionScalarWhereInput[]
}

export type TopPlayerAggressionCreateNestedManyWithoutTableTypeInput = {
  create?: Prisma.XOR<Prisma.TopPlayerAggressionCreateWithoutTableTypeInput, Prisma.TopPlayerAggressionUncheckedCreateWithoutTableTypeInput> | Prisma.TopPlayerAggressionCreateWithoutTableTypeInput[] | Prisma.TopPlayerAggressionUncheckedCreateWithoutTableTypeInput[]
  connectOrCreate?: Prisma.TopPlayerAggressionCreateOrConnectWithoutTableTypeInput | Prisma.TopPlayerAggressionCreateOrConnectWithoutTableTypeInput[]
  createMany?: Prisma.TopPlayerAggressionCreateManyTableTypeInputEnvelope
  connect?: Prisma.TopPlayerAggressionWhereUniqueInput | Prisma.TopPlayerAggressionWhereUniqueInput[]
}

export type TopPlayerAggressionUncheckedCreateNestedManyWithoutTableTypeInput = {
  create?: Prisma.XOR<Prisma.TopPlayerAggressionCreateWithoutTableTypeInput, Prisma.TopPlayerAggressionUncheckedCreateWithoutTableTypeInput> | Prisma.TopPlayerAggressionCreateWithoutTableTypeInput[] | Prisma.TopPlayerAggressionUncheckedCreateWithoutTableTypeInput[]
  connectOrCreate?: Prisma.TopPlayerAggressionCreateOrConnectWithoutTableTypeInput | Prisma.TopPlayerAggressionCreateOrConnectWithoutTableTypeInput[]
  createMany?: Prisma.TopPlayerAggressionCreateManyTableTypeInputEnvelope
  connect?: Prisma.TopPlayerAggressionWhereUniqueInput | Prisma.TopPlayerAggressionWhereUniqueInput[]
}

export type TopPlayerAggressionUpdateManyWithoutTableTypeNestedInput = {
  create?: Prisma.XOR<Prisma.TopPlayerAggressionCreateWithoutTableTypeInput, Prisma.TopPlayerAggressionUncheckedCreateWithoutTableTypeInput> | Prisma.TopPlayerAggressionCreateWithoutTableTypeInput[] | Prisma.TopPlayerAggressionUncheckedCreateWithoutTableTypeInput[]
  connectOrCreate?: Prisma.TopPlayerAggressionCreateOrConnectWithoutTableTypeInput | Prisma.TopPlayerAggressionCreateOrConnectWithoutTableTypeInput[]
  upsert?: Prisma.TopPlayerAggressionUpsertWithWhereUniqueWithoutTableTypeInput | Prisma.TopPlayerAggressionUpsertWithWhereUniqueWithoutTableTypeInput[]
  createMany?: Prisma.TopPlayerAggressionCreateManyTableTypeInputEnvelope
  set?: Prisma.TopPlayerAggressionWhereUniqueInput | Prisma.TopPlayerAggressionWhereUniqueInput[]
  disconnect?: Prisma.TopPlayerAggressionWhereUniqueInput | Prisma.TopPlayerAggressionWhereUniqueInput[]
  delete?: Prisma.TopPlayerAggressionWhereUniqueInput | Prisma.TopPlayerAggressionWhereUniqueInput[]
  connect?: Prisma.TopPlayerAggressionWhereUniqueInput | Prisma.TopPlayerAggressionWhereUniqueInput[]
  update?: Prisma.TopPlayerAggressionUpdateWithWhereUniqueWithoutTableTypeInput | Prisma.TopPlayerAggressionUpdateWithWhereUniqueWithoutTableTypeInput[]
  updateMany?: Prisma.TopPlayerAggressionUpdateManyWithWhereWithoutTableTypeInput | Prisma.TopPlayerAggressionUpdateManyWithWhereWithoutTableTypeInput[]
  deleteMany?: Prisma.TopPlayerAggressionScalarWhereInput | Prisma.TopPlayerAggressionScalarWhereInput[]
}

export type TopPlayerAggressionUncheckedUpdateManyWithoutTableTypeNestedInput = {
  create?: Prisma.XOR<Prisma.TopPlayerAggressionCreateWithoutTableTypeInput, Prisma.TopPlayerAggressionUncheckedCreateWithoutTableTypeInput> | Prisma.TopPlayerAggressionCreateWithoutTableTypeInput[] | Prisma.TopPlayerAggressionUncheckedCreateWithoutTableTypeInput[]
  connectOrCreate?: Prisma.TopPlayerAggressionCreateOrConnectWithoutTableTypeInput | Prisma.TopPlayerAggressionCreateOrConnectWithoutTableTypeInput[]
  upsert?: Prisma.TopPlayerAggressionUpsertWithWhereUniqueWithoutTableTypeInput | Prisma.TopPlayerAggressionUpsertWithWhereUniqueWithoutTableTypeInput[]
  createMany?: Prisma.TopPlayerAggressionCreateManyTableTypeInputEnvelope
  set?: Prisma.TopPlayerAggressionWhereUniqueInput | Prisma.TopPlayerAggressionWhereUniqueInput[]
  disconnect?: Prisma.TopPlayerAggressionWhereUniqueInput | Prisma.TopPlayerAggressionWhereUniqueInput[]
  delete?: Prisma.TopPlayerAggressionWhereUniqueInput | Prisma.TopPlayerAggressionWhereUniqueInput[]
  connect?: Prisma.TopPlayerAggressionWhereUniqueInput | Prisma.TopPlayerAggressionWhereUniqueInput[]
  update?: Prisma.TopPlayerAggressionUpdateWithWhereUniqueWithoutTableTypeInput | Prisma.TopPlayerAggressionUpdateWithWhereUniqueWithoutTableTypeInput[]
  updateMany?: Prisma.TopPlayerAggressionUpdateManyWithWhereWithoutTableTypeInput | Prisma.TopPlayerAggressionUpdateManyWithWhereWithoutTableTypeInput[]
  deleteMany?: Prisma.TopPlayerAggressionScalarWhereInput | Prisma.TopPlayerAggressionScalarWhereInput[]
}

export type TopPlayerAggressionCreateNestedManyWithoutTeamInput = {
  create?: Prisma.XOR<Prisma.TopPlayerAggressionCreateWithoutTeamInput, Prisma.TopPlayerAggressionUncheckedCreateWithoutTeamInput> | Prisma.TopPlayerAggressionCreateWithoutTeamInput[] | Prisma.TopPlayerAggressionUncheckedCreateWithoutTeamInput[]
  connectOrCreate?: Prisma.TopPlayerAggressionCreateOrConnectWithoutTeamInput | Prisma.TopPlayerAggressionCreateOrConnectWithoutTeamInput[]
  createMany?: Prisma.TopPlayerAggressionCreateManyTeamInputEnvelope
  connect?: Prisma.TopPlayerAggressionWhereUniqueInput | Prisma.TopPlayerAggressionWhereUniqueInput[]
}

export type TopPlayerAggressionUncheckedCreateNestedManyWithoutTeamInput = {
  create?: Prisma.XOR<Prisma.TopPlayerAggressionCreateWithoutTeamInput, Prisma.TopPlayerAggressionUncheckedCreateWithoutTeamInput> | Prisma.TopPlayerAggressionCreateWithoutTeamInput[] | Prisma.TopPlayerAggressionUncheckedCreateWithoutTeamInput[]
  connectOrCreate?: Prisma.TopPlayerAggressionCreateOrConnectWithoutTeamInput | Prisma.TopPlayerAggressionCreateOrConnectWithoutTeamInput[]
  createMany?: Prisma.TopPlayerAggressionCreateManyTeamInputEnvelope
  connect?: Prisma.TopPlayerAggressionWhereUniqueInput | Prisma.TopPlayerAggressionWhereUniqueInput[]
}

export type TopPlayerAggressionUpdateManyWithoutTeamNestedInput = {
  create?: Prisma.XOR<Prisma.TopPlayerAggressionCreateWithoutTeamInput, Prisma.TopPlayerAggressionUncheckedCreateWithoutTeamInput> | Prisma.TopPlayerAggressionCreateWithoutTeamInput[] | Prisma.TopPlayerAggressionUncheckedCreateWithoutTeamInput[]
  connectOrCreate?: Prisma.TopPlayerAggressionCreateOrConnectWithoutTeamInput | Prisma.TopPlayerAggressionCreateOrConnectWithoutTeamInput[]
  upsert?: Prisma.TopPlayerAggressionUpsertWithWhereUniqueWithoutTeamInput | Prisma.TopPlayerAggressionUpsertWithWhereUniqueWithoutTeamInput[]
  createMany?: Prisma.TopPlayerAggressionCreateManyTeamInputEnvelope
  set?: Prisma.TopPlayerAggressionWhereUniqueInput | Prisma.TopPlayerAggressionWhereUniqueInput[]
  disconnect?: Prisma.TopPlayerAggressionWhereUniqueInput | Prisma.TopPlayerAggressionWhereUniqueInput[]
  delete?: Prisma.TopPlayerAggressionWhereUniqueInput | Prisma.TopPlayerAggressionWhereUniqueInput[]
  connect?: Prisma.TopPlayerAggressionWhereUniqueInput | Prisma.TopPlayerAggressionWhereUniqueInput[]
  update?: Prisma.TopPlayerAggressionUpdateWithWhereUniqueWithoutTeamInput | Prisma.TopPlayerAggressionUpdateWithWhereUniqueWithoutTeamInput[]
  updateMany?: Prisma.TopPlayerAggressionUpdateManyWithWhereWithoutTeamInput | Prisma.TopPlayerAggressionUpdateManyWithWhereWithoutTeamInput[]
  deleteMany?: Prisma.TopPlayerAggressionScalarWhereInput | Prisma.TopPlayerAggressionScalarWhereInput[]
}

export type TopPlayerAggressionUncheckedUpdateManyWithoutTeamNestedInput = {
  create?: Prisma.XOR<Prisma.TopPlayerAggressionCreateWithoutTeamInput, Prisma.TopPlayerAggressionUncheckedCreateWithoutTeamInput> | Prisma.TopPlayerAggressionCreateWithoutTeamInput[] | Prisma.TopPlayerAggressionUncheckedCreateWithoutTeamInput[]
  connectOrCreate?: Prisma.TopPlayerAggressionCreateOrConnectWithoutTeamInput | Prisma.TopPlayerAggressionCreateOrConnectWithoutTeamInput[]
  upsert?: Prisma.TopPlayerAggressionUpsertWithWhereUniqueWithoutTeamInput | Prisma.TopPlayerAggressionUpsertWithWhereUniqueWithoutTeamInput[]
  createMany?: Prisma.TopPlayerAggressionCreateManyTeamInputEnvelope
  set?: Prisma.TopPlayerAggressionWhereUniqueInput | Prisma.TopPlayerAggressionWhereUniqueInput[]
  disconnect?: Prisma.TopPlayerAggressionWhereUniqueInput | Prisma.TopPlayerAggressionWhereUniqueInput[]
  delete?: Prisma.TopPlayerAggressionWhereUniqueInput | Prisma.TopPlayerAggressionWhereUniqueInput[]
  connect?: Prisma.TopPlayerAggressionWhereUniqueInput | Prisma.TopPlayerAggressionWhereUniqueInput[]
  update?: Prisma.TopPlayerAggressionUpdateWithWhereUniqueWithoutTeamInput | Prisma.TopPlayerAggressionUpdateWithWhereUniqueWithoutTeamInput[]
  updateMany?: Prisma.TopPlayerAggressionUpdateManyWithWhereWithoutTeamInput | Prisma.TopPlayerAggressionUpdateManyWithWhereWithoutTeamInput[]
  deleteMany?: Prisma.TopPlayerAggressionScalarWhereInput | Prisma.TopPlayerAggressionScalarWhereInput[]
}

export type TopPlayerAggressionCreateNestedManyWithoutTournamentInput = {
  create?: Prisma.XOR<Prisma.TopPlayerAggressionCreateWithoutTournamentInput, Prisma.TopPlayerAggressionUncheckedCreateWithoutTournamentInput> | Prisma.TopPlayerAggressionCreateWithoutTournamentInput[] | Prisma.TopPlayerAggressionUncheckedCreateWithoutTournamentInput[]
  connectOrCreate?: Prisma.TopPlayerAggressionCreateOrConnectWithoutTournamentInput | Prisma.TopPlayerAggressionCreateOrConnectWithoutTournamentInput[]
  createMany?: Prisma.TopPlayerAggressionCreateManyTournamentInputEnvelope
  connect?: Prisma.TopPlayerAggressionWhereUniqueInput | Prisma.TopPlayerAggressionWhereUniqueInput[]
}

export type TopPlayerAggressionUncheckedCreateNestedManyWithoutTournamentInput = {
  create?: Prisma.XOR<Prisma.TopPlayerAggressionCreateWithoutTournamentInput, Prisma.TopPlayerAggressionUncheckedCreateWithoutTournamentInput> | Prisma.TopPlayerAggressionCreateWithoutTournamentInput[] | Prisma.TopPlayerAggressionUncheckedCreateWithoutTournamentInput[]
  connectOrCreate?: Prisma.TopPlayerAggressionCreateOrConnectWithoutTournamentInput | Prisma.TopPlayerAggressionCreateOrConnectWithoutTournamentInput[]
  createMany?: Prisma.TopPlayerAggressionCreateManyTournamentInputEnvelope
  connect?: Prisma.TopPlayerAggressionWhereUniqueInput | Prisma.TopPlayerAggressionWhereUniqueInput[]
}

export type TopPlayerAggressionUpdateManyWithoutTournamentNestedInput = {
  create?: Prisma.XOR<Prisma.TopPlayerAggressionCreateWithoutTournamentInput, Prisma.TopPlayerAggressionUncheckedCreateWithoutTournamentInput> | Prisma.TopPlayerAggressionCreateWithoutTournamentInput[] | Prisma.TopPlayerAggressionUncheckedCreateWithoutTournamentInput[]
  connectOrCreate?: Prisma.TopPlayerAggressionCreateOrConnectWithoutTournamentInput | Prisma.TopPlayerAggressionCreateOrConnectWithoutTournamentInput[]
  upsert?: Prisma.TopPlayerAggressionUpsertWithWhereUniqueWithoutTournamentInput | Prisma.TopPlayerAggressionUpsertWithWhereUniqueWithoutTournamentInput[]
  createMany?: Prisma.TopPlayerAggressionCreateManyTournamentInputEnvelope
  set?: Prisma.TopPlayerAggressionWhereUniqueInput | Prisma.TopPlayerAggressionWhereUniqueInput[]
  disconnect?: Prisma.TopPlayerAggressionWhereUniqueInput | Prisma.TopPlayerAggressionWhereUniqueInput[]
  delete?: Prisma.TopPlayerAggressionWhereUniqueInput | Prisma.TopPlayerAggressionWhereUniqueInput[]
  connect?: Prisma.TopPlayerAggressionWhereUniqueInput | Prisma.TopPlayerAggressionWhereUniqueInput[]
  update?: Prisma.TopPlayerAggressionUpdateWithWhereUniqueWithoutTournamentInput | Prisma.TopPlayerAggressionUpdateWithWhereUniqueWithoutTournamentInput[]
  updateMany?: Prisma.TopPlayerAggressionUpdateManyWithWhereWithoutTournamentInput | Prisma.TopPlayerAggressionUpdateManyWithWhereWithoutTournamentInput[]
  deleteMany?: Prisma.TopPlayerAggressionScalarWhereInput | Prisma.TopPlayerAggressionScalarWhereInput[]
}

export type TopPlayerAggressionUncheckedUpdateManyWithoutTournamentNestedInput = {
  create?: Prisma.XOR<Prisma.TopPlayerAggressionCreateWithoutTournamentInput, Prisma.TopPlayerAggressionUncheckedCreateWithoutTournamentInput> | Prisma.TopPlayerAggressionCreateWithoutTournamentInput[] | Prisma.TopPlayerAggressionUncheckedCreateWithoutTournamentInput[]
  connectOrCreate?: Prisma.TopPlayerAggressionCreateOrConnectWithoutTournamentInput | Prisma.TopPlayerAggressionCreateOrConnectWithoutTournamentInput[]
  upsert?: Prisma.TopPlayerAggressionUpsertWithWhereUniqueWithoutTournamentInput | Prisma.TopPlayerAggressionUpsertWithWhereUniqueWithoutTournamentInput[]
  createMany?: Prisma.TopPlayerAggressionCreateManyTournamentInputEnvelope
  set?: Prisma.TopPlayerAggressionWhereUniqueInput | Prisma.TopPlayerAggressionWhereUniqueInput[]
  disconnect?: Prisma.TopPlayerAggressionWhereUniqueInput | Prisma.TopPlayerAggressionWhereUniqueInput[]
  delete?: Prisma.TopPlayerAggressionWhereUniqueInput | Prisma.TopPlayerAggressionWhereUniqueInput[]
  connect?: Prisma.TopPlayerAggressionWhereUniqueInput | Prisma.TopPlayerAggressionWhereUniqueInput[]
  update?: Prisma.TopPlayerAggressionUpdateWithWhereUniqueWithoutTournamentInput | Prisma.TopPlayerAggressionUpdateWithWhereUniqueWithoutTournamentInput[]
  updateMany?: Prisma.TopPlayerAggressionUpdateManyWithWhereWithoutTournamentInput | Prisma.TopPlayerAggressionUpdateManyWithWhereWithoutTournamentInput[]
  deleteMany?: Prisma.TopPlayerAggressionScalarWhereInput | Prisma.TopPlayerAggressionScalarWhereInput[]
}

export type TopPlayerAggressionCreateWithoutPlayerInput = {
  rank?: number | null
  yellowCards?: number | null
  redCards?: number | null
  createdAt?: Date | string
  updatedAt: Date | string
  Team: Prisma.TeamCreateNestedOneWithoutTopPlayerAggressionInput
  Tournament: Prisma.TournamentCreateNestedOneWithoutTopPlayerAggressionInput
  TableType: Prisma.TableTypeCreateNestedOneWithoutTopPlayerAggressionInput
}

export type TopPlayerAggressionUncheckedCreateWithoutPlayerInput = {
  id?: number
  tournamentId: number
  teamId: number
  rank?: number | null
  yellowCards?: number | null
  redCards?: number | null
  createdAt?: Date | string
  updatedAt: Date | string
  viewTypeId: number
}

export type TopPlayerAggressionCreateOrConnectWithoutPlayerInput = {
  where: Prisma.TopPlayerAggressionWhereUniqueInput
  create: Prisma.XOR<Prisma.TopPlayerAggressionCreateWithoutPlayerInput, Prisma.TopPlayerAggressionUncheckedCreateWithoutPlayerInput>
}

export type TopPlayerAggressionCreateManyPlayerInputEnvelope = {
  data: Prisma.TopPlayerAggressionCreateManyPlayerInput | Prisma.TopPlayerAggressionCreateManyPlayerInput[]
  skipDuplicates?: boolean
}

export type TopPlayerAggressionUpsertWithWhereUniqueWithoutPlayerInput = {
  where: Prisma.TopPlayerAggressionWhereUniqueInput
  update: Prisma.XOR<Prisma.TopPlayerAggressionUpdateWithoutPlayerInput, Prisma.TopPlayerAggressionUncheckedUpdateWithoutPlayerInput>
  create: Prisma.XOR<Prisma.TopPlayerAggressionCreateWithoutPlayerInput, Prisma.TopPlayerAggressionUncheckedCreateWithoutPlayerInput>
}

export type TopPlayerAggressionUpdateWithWhereUniqueWithoutPlayerInput = {
  where: Prisma.TopPlayerAggressionWhereUniqueInput
  data: Prisma.XOR<Prisma.TopPlayerAggressionUpdateWithoutPlayerInput, Prisma.TopPlayerAggressionUncheckedUpdateWithoutPlayerInput>
}

export type TopPlayerAggressionUpdateManyWithWhereWithoutPlayerInput = {
  where: Prisma.TopPlayerAggressionScalarWhereInput
  data: Prisma.XOR<Prisma.TopPlayerAggressionUpdateManyMutationInput, Prisma.TopPlayerAggressionUncheckedUpdateManyWithoutPlayerInput>
}

export type TopPlayerAggressionScalarWhereInput = {
  AND?: Prisma.TopPlayerAggressionScalarWhereInput | Prisma.TopPlayerAggressionScalarWhereInput[]
  OR?: Prisma.TopPlayerAggressionScalarWhereInput[]
  NOT?: Prisma.TopPlayerAggressionScalarWhereInput | Prisma.TopPlayerAggressionScalarWhereInput[]
  id?: Prisma.IntFilter<"TopPlayerAggression"> | number
  tournamentId?: Prisma.IntFilter<"TopPlayerAggression"> | number
  teamId?: Prisma.IntFilter<"TopPlayerAggression"> | number
  playerId?: Prisma.IntFilter<"TopPlayerAggression"> | number
  rank?: Prisma.IntNullableFilter<"TopPlayerAggression"> | number | null
  yellowCards?: Prisma.IntNullableFilter<"TopPlayerAggression"> | number | null
  redCards?: Prisma.IntNullableFilter<"TopPlayerAggression"> | number | null
  createdAt?: Prisma.DateTimeFilter<"TopPlayerAggression"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TopPlayerAggression"> | Date | string
  viewTypeId?: Prisma.IntFilter<"TopPlayerAggression"> | number
}

export type TopPlayerAggressionCreateWithoutTableTypeInput = {
  rank?: number | null
  yellowCards?: number | null
  redCards?: number | null
  createdAt?: Date | string
  updatedAt: Date | string
  Player: Prisma.PlayerCreateNestedOneWithoutTopPlayerAggressionInput
  Team: Prisma.TeamCreateNestedOneWithoutTopPlayerAggressionInput
  Tournament: Prisma.TournamentCreateNestedOneWithoutTopPlayerAggressionInput
}

export type TopPlayerAggressionUncheckedCreateWithoutTableTypeInput = {
  id?: number
  tournamentId: number
  teamId: number
  playerId: number
  rank?: number | null
  yellowCards?: number | null
  redCards?: number | null
  createdAt?: Date | string
  updatedAt: Date | string
}

export type TopPlayerAggressionCreateOrConnectWithoutTableTypeInput = {
  where: Prisma.TopPlayerAggressionWhereUniqueInput
  create: Prisma.XOR<Prisma.TopPlayerAggressionCreateWithoutTableTypeInput, Prisma.TopPlayerAggressionUncheckedCreateWithoutTableTypeInput>
}

export type TopPlayerAggressionCreateManyTableTypeInputEnvelope = {
  data: Prisma.TopPlayerAggressionCreateManyTableTypeInput | Prisma.TopPlayerAggressionCreateManyTableTypeInput[]
  skipDuplicates?: boolean
}

export type TopPlayerAggressionUpsertWithWhereUniqueWithoutTableTypeInput = {
  where: Prisma.TopPlayerAggressionWhereUniqueInput
  update: Prisma.XOR<Prisma.TopPlayerAggressionUpdateWithoutTableTypeInput, Prisma.TopPlayerAggressionUncheckedUpdateWithoutTableTypeInput>
  create: Prisma.XOR<Prisma.TopPlayerAggressionCreateWithoutTableTypeInput, Prisma.TopPlayerAggressionUncheckedCreateWithoutTableTypeInput>
}

export type TopPlayerAggressionUpdateWithWhereUniqueWithoutTableTypeInput = {
  where: Prisma.TopPlayerAggressionWhereUniqueInput
  data: Prisma.XOR<Prisma.TopPlayerAggressionUpdateWithoutTableTypeInput, Prisma.TopPlayerAggressionUncheckedUpdateWithoutTableTypeInput>
}

export type TopPlayerAggressionUpdateManyWithWhereWithoutTableTypeInput = {
  where: Prisma.TopPlayerAggressionScalarWhereInput
  data: Prisma.XOR<Prisma.TopPlayerAggressionUpdateManyMutationInput, Prisma.TopPlayerAggressionUncheckedUpdateManyWithoutTableTypeInput>
}

export type TopPlayerAggressionCreateWithoutTeamInput = {
  rank?: number | null
  yellowCards?: number | null
  redCards?: number | null
  createdAt?: Date | string
  updatedAt: Date | string
  Player: Prisma.PlayerCreateNestedOneWithoutTopPlayerAggressionInput
  Tournament: Prisma.TournamentCreateNestedOneWithoutTopPlayerAggressionInput
  TableType: Prisma.TableTypeCreateNestedOneWithoutTopPlayerAggressionInput
}

export type TopPlayerAggressionUncheckedCreateWithoutTeamInput = {
  id?: number
  tournamentId: number
  playerId: number
  rank?: number | null
  yellowCards?: number | null
  redCards?: number | null
  createdAt?: Date | string
  updatedAt: Date | string
  viewTypeId: number
}

export type TopPlayerAggressionCreateOrConnectWithoutTeamInput = {
  where: Prisma.TopPlayerAggressionWhereUniqueInput
  create: Prisma.XOR<Prisma.TopPlayerAggressionCreateWithoutTeamInput, Prisma.TopPlayerAggressionUncheckedCreateWithoutTeamInput>
}

export type TopPlayerAggressionCreateManyTeamInputEnvelope = {
  data: Prisma.TopPlayerAggressionCreateManyTeamInput | Prisma.TopPlayerAggressionCreateManyTeamInput[]
  skipDuplicates?: boolean
}

export type TopPlayerAggressionUpsertWithWhereUniqueWithoutTeamInput = {
  where: Prisma.TopPlayerAggressionWhereUniqueInput
  update: Prisma.XOR<Prisma.TopPlayerAggressionUpdateWithoutTeamInput, Prisma.TopPlayerAggressionUncheckedUpdateWithoutTeamInput>
  create: Prisma.XOR<Prisma.TopPlayerAggressionCreateWithoutTeamInput, Prisma.TopPlayerAggressionUncheckedCreateWithoutTeamInput>
}

export type TopPlayerAggressionUpdateWithWhereUniqueWithoutTeamInput = {
  where: Prisma.TopPlayerAggressionWhereUniqueInput
  data: Prisma.XOR<Prisma.TopPlayerAggressionUpdateWithoutTeamInput, Prisma.TopPlayerAggressionUncheckedUpdateWithoutTeamInput>
}

export type TopPlayerAggressionUpdateManyWithWhereWithoutTeamInput = {
  where: Prisma.TopPlayerAggressionScalarWhereInput
  data: Prisma.XOR<Prisma.TopPlayerAggressionUpdateManyMutationInput, Prisma.TopPlayerAggressionUncheckedUpdateManyWithoutTeamInput>
}

export type TopPlayerAggressionCreateWithoutTournamentInput = {
  rank?: number | null
  yellowCards?: number | null
  redCards?: number | null
  createdAt?: Date | string
  updatedAt: Date | string
  Player: Prisma.PlayerCreateNestedOneWithoutTopPlayerAggressionInput
  Team: Prisma.TeamCreateNestedOneWithoutTopPlayerAggressionInput
  TableType: Prisma.TableTypeCreateNestedOneWithoutTopPlayerAggressionInput
}

export type TopPlayerAggressionUncheckedCreateWithoutTournamentInput = {
  id?: number
  teamId: number
  playerId: number
  rank?: number | null
  yellowCards?: number | null
  redCards?: number | null
  createdAt?: Date | string
  updatedAt: Date | string
  viewTypeId: number
}

export type TopPlayerAggressionCreateOrConnectWithoutTournamentInput = {
  where: Prisma.TopPlayerAggressionWhereUniqueInput
  create: Prisma.XOR<Prisma.TopPlayerAggressionCreateWithoutTournamentInput, Prisma.TopPlayerAggressionUncheckedCreateWithoutTournamentInput>
}

export type TopPlayerAggressionCreateManyTournamentInputEnvelope = {
  data: Prisma.TopPlayerAggressionCreateManyTournamentInput | Prisma.TopPlayerAggressionCreateManyTournamentInput[]
  skipDuplicates?: boolean
}

export type TopPlayerAggressionUpsertWithWhereUniqueWithoutTournamentInput = {
  where: Prisma.TopPlayerAggressionWhereUniqueInput
  update: Prisma.XOR<Prisma.TopPlayerAggressionUpdateWithoutTournamentInput, Prisma.TopPlayerAggressionUncheckedUpdateWithoutTournamentInput>
  create: Prisma.XOR<Prisma.TopPlayerAggressionCreateWithoutTournamentInput, Prisma.TopPlayerAggressionUncheckedCreateWithoutTournamentInput>
}

export type TopPlayerAggressionUpdateWithWhereUniqueWithoutTournamentInput = {
  where: Prisma.TopPlayerAggressionWhereUniqueInput
  data: Prisma.XOR<Prisma.TopPlayerAggressionUpdateWithoutTournamentInput, Prisma.TopPlayerAggressionUncheckedUpdateWithoutTournamentInput>
}

export type TopPlayerAggressionUpdateManyWithWhereWithoutTournamentInput = {
  where: Prisma.TopPlayerAggressionScalarWhereInput
  data: Prisma.XOR<Prisma.TopPlayerAggressionUpdateManyMutationInput, Prisma.TopPlayerAggressionUncheckedUpdateManyWithoutTournamentInput>
}

export type TopPlayerAggressionCreateManyPlayerInput = {
  id?: number
  tournamentId: number
  teamId: number
  rank?: number | null
  yellowCards?: number | null
  redCards?: number | null
  createdAt?: Date | string
  updatedAt: Date | string
  viewTypeId: number
}

export type TopPlayerAggressionUpdateWithoutPlayerInput = {
  rank?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  yellowCards?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  redCards?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Team?: Prisma.TeamUpdateOneRequiredWithoutTopPlayerAggressionNestedInput
  Tournament?: Prisma.TournamentUpdateOneRequiredWithoutTopPlayerAggressionNestedInput
  TableType?: Prisma.TableTypeUpdateOneRequiredWithoutTopPlayerAggressionNestedInput
}

export type TopPlayerAggressionUncheckedUpdateWithoutPlayerInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  tournamentId?: Prisma.IntFieldUpdateOperationsInput | number
  teamId?: Prisma.IntFieldUpdateOperationsInput | number
  rank?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  yellowCards?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  redCards?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  viewTypeId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type TopPlayerAggressionUncheckedUpdateManyWithoutPlayerInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  tournamentId?: Prisma.IntFieldUpdateOperationsInput | number
  teamId?: Prisma.IntFieldUpdateOperationsInput | number
  rank?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  yellowCards?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  redCards?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  viewTypeId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type TopPlayerAggressionCreateManyTableTypeInput = {
  id?: number
  tournamentId: number
  teamId: number
  playerId: number
  rank?: number | null
  yellowCards?: number | null
  redCards?: number | null
  createdAt?: Date | string
  updatedAt: Date | string
}

export type TopPlayerAggressionUpdateWithoutTableTypeInput = {
  rank?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  yellowCards?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  redCards?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Player?: Prisma.PlayerUpdateOneRequiredWithoutTopPlayerAggressionNestedInput
  Team?: Prisma.TeamUpdateOneRequiredWithoutTopPlayerAggressionNestedInput
  Tournament?: Prisma.TournamentUpdateOneRequiredWithoutTopPlayerAggressionNestedInput
}

export type TopPlayerAggressionUncheckedUpdateWithoutTableTypeInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  tournamentId?: Prisma.IntFieldUpdateOperationsInput | number
  teamId?: Prisma.IntFieldUpdateOperationsInput | number
  playerId?: Prisma.IntFieldUpdateOperationsInput | number
  rank?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  yellowCards?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  redCards?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TopPlayerAggressionUncheckedUpdateManyWithoutTableTypeInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  tournamentId?: Prisma.IntFieldUpdateOperationsInput | number
  teamId?: Prisma.IntFieldUpdateOperationsInput | number
  playerId?: Prisma.IntFieldUpdateOperationsInput | number
  rank?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  yellowCards?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  redCards?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TopPlayerAggressionCreateManyTeamInput = {
  id?: number
  tournamentId: number
  playerId: number
  rank?: number | null
  yellowCards?: number | null
  redCards?: number | null
  createdAt?: Date | string
  updatedAt: Date | string
  viewTypeId: number
}

export type TopPlayerAggressionUpdateWithoutTeamInput = {
  rank?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  yellowCards?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  redCards?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Player?: Prisma.PlayerUpdateOneRequiredWithoutTopPlayerAggressionNestedInput
  Tournament?: Prisma.TournamentUpdateOneRequiredWithoutTopPlayerAggressionNestedInput
  TableType?: Prisma.TableTypeUpdateOneRequiredWithoutTopPlayerAggressionNestedInput
}

export type TopPlayerAggressionUncheckedUpdateWithoutTeamInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  tournamentId?: Prisma.IntFieldUpdateOperationsInput | number
  playerId?: Prisma.IntFieldUpdateOperationsInput | number
  rank?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  yellowCards?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  redCards?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  viewTypeId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type TopPlayerAggressionUncheckedUpdateManyWithoutTeamInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  tournamentId?: Prisma.IntFieldUpdateOperationsInput | number
  playerId?: Prisma.IntFieldUpdateOperationsInput | number
  rank?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  yellowCards?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  redCards?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  viewTypeId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type TopPlayerAggressionCreateManyTournamentInput = {
  id?: number
  teamId: number
  playerId: number
  rank?: number | null
  yellowCards?: number | null
  redCards?: number | null
  createdAt?: Date | string
  updatedAt: Date | string
  viewTypeId: number
}

export type TopPlayerAggressionUpdateWithoutTournamentInput = {
  rank?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  yellowCards?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  redCards?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Player?: Prisma.PlayerUpdateOneRequiredWithoutTopPlayerAggressionNestedInput
  Team?: Prisma.TeamUpdateOneRequiredWithoutTopPlayerAggressionNestedInput
  TableType?: Prisma.TableTypeUpdateOneRequiredWithoutTopPlayerAggressionNestedInput
}

export type TopPlayerAggressionUncheckedUpdateWithoutTournamentInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  teamId?: Prisma.IntFieldUpdateOperationsInput | number
  playerId?: Prisma.IntFieldUpdateOperationsInput | number
  rank?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  yellowCards?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  redCards?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  viewTypeId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type TopPlayerAggressionUncheckedUpdateManyWithoutTournamentInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  teamId?: Prisma.IntFieldUpdateOperationsInput | number
  playerId?: Prisma.IntFieldUpdateOperationsInput | number
  rank?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  yellowCards?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  redCards?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  viewTypeId?: Prisma.IntFieldUpdateOperationsInput | number
}



export type TopPlayerAggressionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tournamentId?: boolean
  teamId?: boolean
  playerId?: boolean
  rank?: boolean
  yellowCards?: boolean
  redCards?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  viewTypeId?: boolean
  Player?: boolean | Prisma.PlayerDefaultArgs<ExtArgs>
  Team?: boolean | Prisma.TeamDefaultArgs<ExtArgs>
  Tournament?: boolean | Prisma.TournamentDefaultArgs<ExtArgs>
  TableType?: boolean | Prisma.TableTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["topPlayerAggression"]>

export type TopPlayerAggressionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tournamentId?: boolean
  teamId?: boolean
  playerId?: boolean
  rank?: boolean
  yellowCards?: boolean
  redCards?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  viewTypeId?: boolean
  Player?: boolean | Prisma.PlayerDefaultArgs<ExtArgs>
  Team?: boolean | Prisma.TeamDefaultArgs<ExtArgs>
  Tournament?: boolean | Prisma.TournamentDefaultArgs<ExtArgs>
  TableType?: boolean | Prisma.TableTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["topPlayerAggression"]>

export type TopPlayerAggressionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tournamentId?: boolean
  teamId?: boolean
  playerId?: boolean
  rank?: boolean
  yellowCards?: boolean
  redCards?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  viewTypeId?: boolean
  Player?: boolean | Prisma.PlayerDefaultArgs<ExtArgs>
  Team?: boolean | Prisma.TeamDefaultArgs<ExtArgs>
  Tournament?: boolean | Prisma.TournamentDefaultArgs<ExtArgs>
  TableType?: boolean | Prisma.TableTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["topPlayerAggression"]>

export type TopPlayerAggressionSelectScalar = {
  id?: boolean
  tournamentId?: boolean
  teamId?: boolean
  playerId?: boolean
  rank?: boolean
  yellowCards?: boolean
  redCards?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  viewTypeId?: boolean
}

export type TopPlayerAggressionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "tournamentId" | "teamId" | "playerId" | "rank" | "yellowCards" | "redCards" | "createdAt" | "updatedAt" | "viewTypeId", ExtArgs["result"]["topPlayerAggression"]>
export type TopPlayerAggressionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Player?: boolean | Prisma.PlayerDefaultArgs<ExtArgs>
  Team?: boolean | Prisma.TeamDefaultArgs<ExtArgs>
  Tournament?: boolean | Prisma.TournamentDefaultArgs<ExtArgs>
  TableType?: boolean | Prisma.TableTypeDefaultArgs<ExtArgs>
}
export type TopPlayerAggressionIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Player?: boolean | Prisma.PlayerDefaultArgs<ExtArgs>
  Team?: boolean | Prisma.TeamDefaultArgs<ExtArgs>
  Tournament?: boolean | Prisma.TournamentDefaultArgs<ExtArgs>
  TableType?: boolean | Prisma.TableTypeDefaultArgs<ExtArgs>
}
export type TopPlayerAggressionIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Player?: boolean | Prisma.PlayerDefaultArgs<ExtArgs>
  Team?: boolean | Prisma.TeamDefaultArgs<ExtArgs>
  Tournament?: boolean | Prisma.TournamentDefaultArgs<ExtArgs>
  TableType?: boolean | Prisma.TableTypeDefaultArgs<ExtArgs>
}

export type $TopPlayerAggressionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TopPlayerAggression"
  objects: {
    Player: Prisma.$PlayerPayload<ExtArgs>
    Team: Prisma.$TeamPayload<ExtArgs>
    Tournament: Prisma.$TournamentPayload<ExtArgs>
    TableType: Prisma.$TableTypePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    tournamentId: number
    teamId: number
    playerId: number
    rank: number | null
    yellowCards: number | null
    redCards: number | null
    createdAt: Date
    updatedAt: Date
    viewTypeId: number
  }, ExtArgs["result"]["topPlayerAggression"]>
  composites: {}
}

export type TopPlayerAggressionGetPayload<S extends boolean | null | undefined | TopPlayerAggressionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TopPlayerAggressionPayload, S>

export type TopPlayerAggressionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TopPlayerAggressionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TopPlayerAggressionCountAggregateInputType | true
  }

export interface TopPlayerAggressionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TopPlayerAggression'], meta: { name: 'TopPlayerAggression' } }
  /**
   * Find zero or one TopPlayerAggression that matches the filter.
   * @param {TopPlayerAggressionFindUniqueArgs} args - Arguments to find a TopPlayerAggression
   * @example
   * // Get one TopPlayerAggression
   * const topPlayerAggression = await prisma.topPlayerAggression.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TopPlayerAggressionFindUniqueArgs>(args: Prisma.SelectSubset<T, TopPlayerAggressionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TopPlayerAggressionClient<runtime.Types.Result.GetResult<Prisma.$TopPlayerAggressionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TopPlayerAggression that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TopPlayerAggressionFindUniqueOrThrowArgs} args - Arguments to find a TopPlayerAggression
   * @example
   * // Get one TopPlayerAggression
   * const topPlayerAggression = await prisma.topPlayerAggression.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TopPlayerAggressionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TopPlayerAggressionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TopPlayerAggressionClient<runtime.Types.Result.GetResult<Prisma.$TopPlayerAggressionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TopPlayerAggression that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TopPlayerAggressionFindFirstArgs} args - Arguments to find a TopPlayerAggression
   * @example
   * // Get one TopPlayerAggression
   * const topPlayerAggression = await prisma.topPlayerAggression.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TopPlayerAggressionFindFirstArgs>(args?: Prisma.SelectSubset<T, TopPlayerAggressionFindFirstArgs<ExtArgs>>): Prisma.Prisma__TopPlayerAggressionClient<runtime.Types.Result.GetResult<Prisma.$TopPlayerAggressionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TopPlayerAggression that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TopPlayerAggressionFindFirstOrThrowArgs} args - Arguments to find a TopPlayerAggression
   * @example
   * // Get one TopPlayerAggression
   * const topPlayerAggression = await prisma.topPlayerAggression.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TopPlayerAggressionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TopPlayerAggressionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TopPlayerAggressionClient<runtime.Types.Result.GetResult<Prisma.$TopPlayerAggressionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TopPlayerAggressions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TopPlayerAggressionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TopPlayerAggressions
   * const topPlayerAggressions = await prisma.topPlayerAggression.findMany()
   * 
   * // Get first 10 TopPlayerAggressions
   * const topPlayerAggressions = await prisma.topPlayerAggression.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const topPlayerAggressionWithIdOnly = await prisma.topPlayerAggression.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TopPlayerAggressionFindManyArgs>(args?: Prisma.SelectSubset<T, TopPlayerAggressionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TopPlayerAggressionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TopPlayerAggression.
   * @param {TopPlayerAggressionCreateArgs} args - Arguments to create a TopPlayerAggression.
   * @example
   * // Create one TopPlayerAggression
   * const TopPlayerAggression = await prisma.topPlayerAggression.create({
   *   data: {
   *     // ... data to create a TopPlayerAggression
   *   }
   * })
   * 
   */
  create<T extends TopPlayerAggressionCreateArgs>(args: Prisma.SelectSubset<T, TopPlayerAggressionCreateArgs<ExtArgs>>): Prisma.Prisma__TopPlayerAggressionClient<runtime.Types.Result.GetResult<Prisma.$TopPlayerAggressionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TopPlayerAggressions.
   * @param {TopPlayerAggressionCreateManyArgs} args - Arguments to create many TopPlayerAggressions.
   * @example
   * // Create many TopPlayerAggressions
   * const topPlayerAggression = await prisma.topPlayerAggression.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TopPlayerAggressionCreateManyArgs>(args?: Prisma.SelectSubset<T, TopPlayerAggressionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TopPlayerAggressions and returns the data saved in the database.
   * @param {TopPlayerAggressionCreateManyAndReturnArgs} args - Arguments to create many TopPlayerAggressions.
   * @example
   * // Create many TopPlayerAggressions
   * const topPlayerAggression = await prisma.topPlayerAggression.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TopPlayerAggressions and only return the `id`
   * const topPlayerAggressionWithIdOnly = await prisma.topPlayerAggression.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TopPlayerAggressionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TopPlayerAggressionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TopPlayerAggressionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TopPlayerAggression.
   * @param {TopPlayerAggressionDeleteArgs} args - Arguments to delete one TopPlayerAggression.
   * @example
   * // Delete one TopPlayerAggression
   * const TopPlayerAggression = await prisma.topPlayerAggression.delete({
   *   where: {
   *     // ... filter to delete one TopPlayerAggression
   *   }
   * })
   * 
   */
  delete<T extends TopPlayerAggressionDeleteArgs>(args: Prisma.SelectSubset<T, TopPlayerAggressionDeleteArgs<ExtArgs>>): Prisma.Prisma__TopPlayerAggressionClient<runtime.Types.Result.GetResult<Prisma.$TopPlayerAggressionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TopPlayerAggression.
   * @param {TopPlayerAggressionUpdateArgs} args - Arguments to update one TopPlayerAggression.
   * @example
   * // Update one TopPlayerAggression
   * const topPlayerAggression = await prisma.topPlayerAggression.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TopPlayerAggressionUpdateArgs>(args: Prisma.SelectSubset<T, TopPlayerAggressionUpdateArgs<ExtArgs>>): Prisma.Prisma__TopPlayerAggressionClient<runtime.Types.Result.GetResult<Prisma.$TopPlayerAggressionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TopPlayerAggressions.
   * @param {TopPlayerAggressionDeleteManyArgs} args - Arguments to filter TopPlayerAggressions to delete.
   * @example
   * // Delete a few TopPlayerAggressions
   * const { count } = await prisma.topPlayerAggression.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TopPlayerAggressionDeleteManyArgs>(args?: Prisma.SelectSubset<T, TopPlayerAggressionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TopPlayerAggressions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TopPlayerAggressionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TopPlayerAggressions
   * const topPlayerAggression = await prisma.topPlayerAggression.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TopPlayerAggressionUpdateManyArgs>(args: Prisma.SelectSubset<T, TopPlayerAggressionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TopPlayerAggressions and returns the data updated in the database.
   * @param {TopPlayerAggressionUpdateManyAndReturnArgs} args - Arguments to update many TopPlayerAggressions.
   * @example
   * // Update many TopPlayerAggressions
   * const topPlayerAggression = await prisma.topPlayerAggression.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TopPlayerAggressions and only return the `id`
   * const topPlayerAggressionWithIdOnly = await prisma.topPlayerAggression.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TopPlayerAggressionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TopPlayerAggressionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TopPlayerAggressionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TopPlayerAggression.
   * @param {TopPlayerAggressionUpsertArgs} args - Arguments to update or create a TopPlayerAggression.
   * @example
   * // Update or create a TopPlayerAggression
   * const topPlayerAggression = await prisma.topPlayerAggression.upsert({
   *   create: {
   *     // ... data to create a TopPlayerAggression
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TopPlayerAggression we want to update
   *   }
   * })
   */
  upsert<T extends TopPlayerAggressionUpsertArgs>(args: Prisma.SelectSubset<T, TopPlayerAggressionUpsertArgs<ExtArgs>>): Prisma.Prisma__TopPlayerAggressionClient<runtime.Types.Result.GetResult<Prisma.$TopPlayerAggressionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TopPlayerAggressions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TopPlayerAggressionCountArgs} args - Arguments to filter TopPlayerAggressions to count.
   * @example
   * // Count the number of TopPlayerAggressions
   * const count = await prisma.topPlayerAggression.count({
   *   where: {
   *     // ... the filter for the TopPlayerAggressions we want to count
   *   }
   * })
  **/
  count<T extends TopPlayerAggressionCountArgs>(
    args?: Prisma.Subset<T, TopPlayerAggressionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TopPlayerAggressionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TopPlayerAggression.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TopPlayerAggressionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TopPlayerAggressionAggregateArgs>(args: Prisma.Subset<T, TopPlayerAggressionAggregateArgs>): Prisma.PrismaPromise<GetTopPlayerAggressionAggregateType<T>>

  /**
   * Group by TopPlayerAggression.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TopPlayerAggressionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TopPlayerAggressionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TopPlayerAggressionGroupByArgs['orderBy'] }
      : { orderBy?: TopPlayerAggressionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TopPlayerAggressionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTopPlayerAggressionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TopPlayerAggression model
 */
readonly fields: TopPlayerAggressionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TopPlayerAggression.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TopPlayerAggressionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  Player<T extends Prisma.PlayerDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PlayerDefaultArgs<ExtArgs>>): Prisma.Prisma__PlayerClient<runtime.Types.Result.GetResult<Prisma.$PlayerPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  Team<T extends Prisma.TeamDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TeamDefaultArgs<ExtArgs>>): Prisma.Prisma__TeamClient<runtime.Types.Result.GetResult<Prisma.$TeamPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  Tournament<T extends Prisma.TournamentDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TournamentDefaultArgs<ExtArgs>>): Prisma.Prisma__TournamentClient<runtime.Types.Result.GetResult<Prisma.$TournamentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  TableType<T extends Prisma.TableTypeDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TableTypeDefaultArgs<ExtArgs>>): Prisma.Prisma__TableTypeClient<runtime.Types.Result.GetResult<Prisma.$TableTypePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TopPlayerAggression model
 */
export interface TopPlayerAggressionFieldRefs {
  readonly id: Prisma.FieldRef<"TopPlayerAggression", 'Int'>
  readonly tournamentId: Prisma.FieldRef<"TopPlayerAggression", 'Int'>
  readonly teamId: Prisma.FieldRef<"TopPlayerAggression", 'Int'>
  readonly playerId: Prisma.FieldRef<"TopPlayerAggression", 'Int'>
  readonly rank: Prisma.FieldRef<"TopPlayerAggression", 'Int'>
  readonly yellowCards: Prisma.FieldRef<"TopPlayerAggression", 'Int'>
  readonly redCards: Prisma.FieldRef<"TopPlayerAggression", 'Int'>
  readonly createdAt: Prisma.FieldRef<"TopPlayerAggression", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"TopPlayerAggression", 'DateTime'>
  readonly viewTypeId: Prisma.FieldRef<"TopPlayerAggression", 'Int'>
}
    

// Custom InputTypes
/**
 * TopPlayerAggression findUnique
 */
export type TopPlayerAggressionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TopPlayerAggression
   */
  select?: Prisma.TopPlayerAggressionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TopPlayerAggression
   */
  omit?: Prisma.TopPlayerAggressionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TopPlayerAggressionInclude<ExtArgs> | null
  /**
   * Filter, which TopPlayerAggression to fetch.
   */
  where: Prisma.TopPlayerAggressionWhereUniqueInput
}

/**
 * TopPlayerAggression findUniqueOrThrow
 */
export type TopPlayerAggressionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TopPlayerAggression
   */
  select?: Prisma.TopPlayerAggressionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TopPlayerAggression
   */
  omit?: Prisma.TopPlayerAggressionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TopPlayerAggressionInclude<ExtArgs> | null
  /**
   * Filter, which TopPlayerAggression to fetch.
   */
  where: Prisma.TopPlayerAggressionWhereUniqueInput
}

/**
 * TopPlayerAggression findFirst
 */
export type TopPlayerAggressionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TopPlayerAggression
   */
  select?: Prisma.TopPlayerAggressionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TopPlayerAggression
   */
  omit?: Prisma.TopPlayerAggressionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TopPlayerAggressionInclude<ExtArgs> | null
  /**
   * Filter, which TopPlayerAggression to fetch.
   */
  where?: Prisma.TopPlayerAggressionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TopPlayerAggressions to fetch.
   */
  orderBy?: Prisma.TopPlayerAggressionOrderByWithRelationInput | Prisma.TopPlayerAggressionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TopPlayerAggressions.
   */
  cursor?: Prisma.TopPlayerAggressionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TopPlayerAggressions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TopPlayerAggressions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TopPlayerAggressions.
   */
  distinct?: Prisma.TopPlayerAggressionScalarFieldEnum | Prisma.TopPlayerAggressionScalarFieldEnum[]
}

/**
 * TopPlayerAggression findFirstOrThrow
 */
export type TopPlayerAggressionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TopPlayerAggression
   */
  select?: Prisma.TopPlayerAggressionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TopPlayerAggression
   */
  omit?: Prisma.TopPlayerAggressionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TopPlayerAggressionInclude<ExtArgs> | null
  /**
   * Filter, which TopPlayerAggression to fetch.
   */
  where?: Prisma.TopPlayerAggressionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TopPlayerAggressions to fetch.
   */
  orderBy?: Prisma.TopPlayerAggressionOrderByWithRelationInput | Prisma.TopPlayerAggressionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TopPlayerAggressions.
   */
  cursor?: Prisma.TopPlayerAggressionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TopPlayerAggressions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TopPlayerAggressions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TopPlayerAggressions.
   */
  distinct?: Prisma.TopPlayerAggressionScalarFieldEnum | Prisma.TopPlayerAggressionScalarFieldEnum[]
}

/**
 * TopPlayerAggression findMany
 */
export type TopPlayerAggressionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TopPlayerAggression
   */
  select?: Prisma.TopPlayerAggressionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TopPlayerAggression
   */
  omit?: Prisma.TopPlayerAggressionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TopPlayerAggressionInclude<ExtArgs> | null
  /**
   * Filter, which TopPlayerAggressions to fetch.
   */
  where?: Prisma.TopPlayerAggressionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TopPlayerAggressions to fetch.
   */
  orderBy?: Prisma.TopPlayerAggressionOrderByWithRelationInput | Prisma.TopPlayerAggressionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TopPlayerAggressions.
   */
  cursor?: Prisma.TopPlayerAggressionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TopPlayerAggressions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TopPlayerAggressions.
   */
  skip?: number
  distinct?: Prisma.TopPlayerAggressionScalarFieldEnum | Prisma.TopPlayerAggressionScalarFieldEnum[]
}

/**
 * TopPlayerAggression create
 */
export type TopPlayerAggressionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TopPlayerAggression
   */
  select?: Prisma.TopPlayerAggressionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TopPlayerAggression
   */
  omit?: Prisma.TopPlayerAggressionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TopPlayerAggressionInclude<ExtArgs> | null
  /**
   * The data needed to create a TopPlayerAggression.
   */
  data: Prisma.XOR<Prisma.TopPlayerAggressionCreateInput, Prisma.TopPlayerAggressionUncheckedCreateInput>
}

/**
 * TopPlayerAggression createMany
 */
export type TopPlayerAggressionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TopPlayerAggressions.
   */
  data: Prisma.TopPlayerAggressionCreateManyInput | Prisma.TopPlayerAggressionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TopPlayerAggression createManyAndReturn
 */
export type TopPlayerAggressionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TopPlayerAggression
   */
  select?: Prisma.TopPlayerAggressionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TopPlayerAggression
   */
  omit?: Prisma.TopPlayerAggressionOmit<ExtArgs> | null
  /**
   * The data used to create many TopPlayerAggressions.
   */
  data: Prisma.TopPlayerAggressionCreateManyInput | Prisma.TopPlayerAggressionCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TopPlayerAggressionIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * TopPlayerAggression update
 */
export type TopPlayerAggressionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TopPlayerAggression
   */
  select?: Prisma.TopPlayerAggressionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TopPlayerAggression
   */
  omit?: Prisma.TopPlayerAggressionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TopPlayerAggressionInclude<ExtArgs> | null
  /**
   * The data needed to update a TopPlayerAggression.
   */
  data: Prisma.XOR<Prisma.TopPlayerAggressionUpdateInput, Prisma.TopPlayerAggressionUncheckedUpdateInput>
  /**
   * Choose, which TopPlayerAggression to update.
   */
  where: Prisma.TopPlayerAggressionWhereUniqueInput
}

/**
 * TopPlayerAggression updateMany
 */
export type TopPlayerAggressionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TopPlayerAggressions.
   */
  data: Prisma.XOR<Prisma.TopPlayerAggressionUpdateManyMutationInput, Prisma.TopPlayerAggressionUncheckedUpdateManyInput>
  /**
   * Filter which TopPlayerAggressions to update
   */
  where?: Prisma.TopPlayerAggressionWhereInput
  /**
   * Limit how many TopPlayerAggressions to update.
   */
  limit?: number
}

/**
 * TopPlayerAggression updateManyAndReturn
 */
export type TopPlayerAggressionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TopPlayerAggression
   */
  select?: Prisma.TopPlayerAggressionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TopPlayerAggression
   */
  omit?: Prisma.TopPlayerAggressionOmit<ExtArgs> | null
  /**
   * The data used to update TopPlayerAggressions.
   */
  data: Prisma.XOR<Prisma.TopPlayerAggressionUpdateManyMutationInput, Prisma.TopPlayerAggressionUncheckedUpdateManyInput>
  /**
   * Filter which TopPlayerAggressions to update
   */
  where?: Prisma.TopPlayerAggressionWhereInput
  /**
   * Limit how many TopPlayerAggressions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TopPlayerAggressionIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * TopPlayerAggression upsert
 */
export type TopPlayerAggressionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TopPlayerAggression
   */
  select?: Prisma.TopPlayerAggressionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TopPlayerAggression
   */
  omit?: Prisma.TopPlayerAggressionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TopPlayerAggressionInclude<ExtArgs> | null
  /**
   * The filter to search for the TopPlayerAggression to update in case it exists.
   */
  where: Prisma.TopPlayerAggressionWhereUniqueInput
  /**
   * In case the TopPlayerAggression found by the `where` argument doesn't exist, create a new TopPlayerAggression with this data.
   */
  create: Prisma.XOR<Prisma.TopPlayerAggressionCreateInput, Prisma.TopPlayerAggressionUncheckedCreateInput>
  /**
   * In case the TopPlayerAggression was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TopPlayerAggressionUpdateInput, Prisma.TopPlayerAggressionUncheckedUpdateInput>
}

/**
 * TopPlayerAggression delete
 */
export type TopPlayerAggressionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TopPlayerAggression
   */
  select?: Prisma.TopPlayerAggressionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TopPlayerAggression
   */
  omit?: Prisma.TopPlayerAggressionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TopPlayerAggressionInclude<ExtArgs> | null
  /**
   * Filter which TopPlayerAggression to delete.
   */
  where: Prisma.TopPlayerAggressionWhereUniqueInput
}

/**
 * TopPlayerAggression deleteMany
 */
export type TopPlayerAggressionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TopPlayerAggressions to delete
   */
  where?: Prisma.TopPlayerAggressionWhereInput
  /**
   * Limit how many TopPlayerAggressions to delete.
   */
  limit?: number
}

/**
 * TopPlayerAggression without action
 */
export type TopPlayerAggressionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TopPlayerAggression
   */
  select?: Prisma.TopPlayerAggressionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TopPlayerAggression
   */
  omit?: Prisma.TopPlayerAggressionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TopPlayerAggressionInclude<ExtArgs> | null
}
