
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser.js'
export { Prisma }
export * as $Enums from './enums.js'
export * from './enums.js';
/**
 * Model PushSubscription
 * 
 */
export type PushSubscription = Prisma.PushSubscriptionModel
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Favorite
 * 
 */
export type Favorite = Prisma.FavoriteModel
/**
 * Model NotificationSubscriber
 * 
 */
export type NotificationSubscriber = Prisma.NotificationSubscriberModel
/**
 * Model MatchSubscription
 * 
 */
export type MatchSubscription = Prisma.MatchSubscriptionModel
/**
 * Model EvolutionInstance
 * 
 */
export type EvolutionInstance = Prisma.EvolutionInstanceModel
/**
 * Model NewsCategory
 * 
 */
export type NewsCategory = Prisma.NewsCategoryModel
/**
 * Model News
 * 
 */
export type News = Prisma.NewsModel
/**
 * Model Post
 * 
 */
export type Post = Prisma.PostModel
